= LIST OF ISSUER IDENTIFIER NUMBERS FOR THE INTERNATIONAL TELECOMMUNICATION CHARGE CARD (IN ACCORDANCE WITH RECOMMENDATION ITU-T E.118 (05/2006))
:bureau: T
:docnumber: 1161
:published-date: 2018-12-01
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1161
:status: published
:doctype: service-publication
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== ملاحظة من مكتب تقييس الاتصالات

تحل هذه القائمة محل القائمة الملحقة بالنشرة التشغيلية رقم 1088 المؤرخة 2015.XI.15 . وتتضمن جميع أرقام تع رف جهات الإصدار (IIN)
التي سجلها الاتحاد وتم التبليغ عنها في النشرة التشغيلية للاتحاد حتى النشرة رقم 1161 المؤرخة 2018.XII.1 ، ضمناً.
وللعلم، سيجري تحديث هذه القائمة من خلال سلسلة مرقمة من التعديلات يتم نشرها في النشرة التشغيلية للاتحاد. وهذا الملحق متاح للتنزيل
المجاني في الموقع الإلكتروني للاتحاد.

ويستعمل رقم تع رف جهة الإصدار لتحديد شركة اتصالات في أحد البلدان تعمل في بيئة دولية. ووفقاً لمعيار المنظمة الدولية للتوحيد
القياسي 7812-2 ، تكون معايير الموافقة على الطلبات ورفضها كالآتي:

"1.3.4 معايير الموافقة على طلب بشأن رقم واحد لتع ر ف جهة الإصدار

يجب أن تفي الطلبات المتعلقة برقم واحد لتع رف جهة الإصدار بجميع معايير الموافقة المبينة أدناه وألا تمتثل لأ ي من معايير الرفض الواردة
:في الفقرة 2.3.4

. يجب ألا يكون لمقدم الطلب بشأن رقم واحد لتع رف هوية جهة الإصدار (IIN) رقم مخصص له بصفته الفردية )خارج إطار بطاقة معينة(؛
. يُستعمل رقم تع رف جهة الإصدار فوراً ويُفضل أن يكون في غضون 12 شهراً من تاريخ إصدار الرقم؛
. تُستخدم البطاقة التي يتم إصدارها في بيئة تبادل دولية )انظر المعيار ISO/IEC 7812-1
. يجب أن يكون مقدم الطلب أحد الكيانات التجارية التي تعمل بموجب لوائح تشريعية محددة.

2.3.4 معايير رفض طلب بشأن رقم واحد لتع ر ف جهة الإصدار

ترفض السلطة الراعية مقدم طلب بشأن رقم واحد لتع رف جهة الإصدار عند توفر أحد الشروط التالية:

. مقدم الطلب ليس جهة من جهات إصدار البطاقات؛
. تم تخصيص رقم تع رف جهة الإصدار مسبقاً لمقدم الطلب بصفته الفردية )خارج إطار العضوية في بطاقة معينة( ولا يزال مقدم الطلب يستعمل هذا الرقم ولم يقدم معلومات إضافية كافية لتبرير إصدار رقم إضافي )انظر الفقرة 2.4 ؛)
. لا تستخدم البطاقات التي يصدرها مقدم الطلب في بيئة تبادل دولي و/أو تبادل بين دوائر الصناعة؛
. سيُستعمل رقم تع رف جهة الإصدار لتحديد أو تمييز المنتجات واخددمات والتكنولوجيات )أي بما في لل بطاقات الدارات المتكاملة دون الاقتصار عليها(، أو فقط لتسهيل التسيير أو لتحديد الموقع الجغرافي؛
. سيُستعمل رقم تع رف جهة الإصدار لتحديد أو تمييز الفرو أو الشركات الفرعية داخل منظمة مقدم الطلب )أي أن هذه الفرو أو الشركات الفرعية ليست كيانات تجارية مستقلة(؛
. قام مقدم الطلب بطلب رقم محدد أو حجز رقم محدد في السجل أو تقدم بطلب خارج نطاق هذا الجزء من المعيار ISO/IEC 7812 ؛
. لن تصدر أي بطاقات للاستعمال الفوري، مثلاً في غضون 12 شهراً من تاريخ إصدار رقم تع رف جهة الإصدار."

ولاتحاد الدولي للاتصالات هو الهيئة المركزية لتسجيل رقم تعرف جهة الإصدار (IIN) ، مع معرِّف الصناعة الرئيسية (MII) بقيمة 89 ، لأغراض الاتصالات.

وبموجب الفقرة 2.4 د( من التوصية ITU-T E.118 ، يفرض الاتحاد رسم اً لمرة واحدة لقاء تخصيص وتسجيل كل رقم جديد من أرقام تع رف جهةالإصدار. ويبلغ هذا الرسم 150 فرنكاً سويسري اً منذ 1 يناير 2018

ومنذ 1 يناير 2018 ، يطبَّق على غير الأعضاء في قطاعيْ تقييس الاتصالات والاتصالات الراديوية رسم سنوي للتحديث قدره 100 فرن سويسري
لكل رقم مسجل. ولا يُطلب من أعضاء قطاعيْ تقييس الاتصالات والاتصالات الراديوية دفع رسم سنوي للتحديث.

ويُطلب من مقدمي طلب بشأن رقم واحد لتع رف جهة الإصدار ملء استمارة التسجيل وتقديمها إلى إدارة الاتصالات الوطنية )أو منظمة التنسيق
المخولة حسب الأصول في بلدهم( لاستكمالها قبل إرسالها إلى الاتحاد لتسجيلها، على أن تكون مشفوعة بما يثبت الدفع للاتحاد.

وبغية تحديث القائمة بصورة مستمرة، يُطلب من الشركات الواردة في القائمة أن ترسل جميع التعديلات المتعلقة بشركاتها وبمسؤول الاتصال اخداص
بها، بما في لل العنوان الكامل وعناوين البريد الإلكتروني، إلى الاتحاد، مكتب تقييس الاتصالات/النشرة التشغيلية وتخصيص موارد الترقيم: البريد

الإلكتروني: tsbtson@itu.int ؛ رقم الفاكس: 5853 730 22 +4 +
ويتعين على الإدارة الوطنية المصادقة على التحديثات أو إرسالها. +
للحصول على استمارة التسجيل والمزيد من المعلومات، انظر: +
link:https://www.itu.int/en/ITU-T/inr/forms/Pages/iin.aspx[www.itu.int/en/ITU-T/inr/forms/Pages/iin.aspx]


وجدير بالذكر أن التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تع بر عن أي رأي من جانب الاتحاد فيما يتعلق بالوضع القانوني لأي بلد
أو منطقة جغرافية أو لسلطات أ ي منهما.


== {blank}

[yaml2text,T-SP-E.118-2018.yaml,file]
----
{% assign lang = "ar" %}


[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}/{{ file.metadata.locale.company_address[lang] }}
| {{ file.metadata.locale.issue_id_number[lang] }}
| {{ file.metadata.locale.contact[lang] }}

{% for country_data in file.data -%}
    | *{{ country_data[1].country_or_area["en"] }}*
    | *{{ country_data[1].company_name }}* +
    {{ country_data[1].company_address_1 }} +
    {{ country_data[1].company_address_2 }}
    | *{{ country_data[0] }}*
    | {{ country_data[1].contact }} +
    {{ country_data[1].contact_address_1 }} +
    {{ country_data[1].contact_address_2 }} +
    Tel: {{ country_data[1].tel }} +
    Fax: {{ country_data[1].fax }} +
    E-mail: {{ country_data[1].email | join: "; " }}
{%- endfor %}
|===


== التعديلات

[cols="^,^,^,^",options="unnumbered"]
|===
| رقم التعديل
| رقم النشرة التشغيلية
| البلد/المنطقة الجغرافية
| رقم تع رف جهة الإصدار

{% for i in (1..33) -%}
    | {{ i }} | | |
{%- endfor %}
|===
----







