= Five-letter Code Groups for the use of the International Public Telegram Service
:bureau: T
:docnumber: 669
:series: FIVE LETTER CODE GROUPS* *FOR THE USE OF THE INTERNATIONAL PUBLIC TELEGRAM SERVICE
:series1: According to ITU-T Recommendation F.1 (03/98)
:published-date: 1998-06-01
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note from the TSB

[class=steps]
. By TSB Circular 104 of 23 March 1998, the TSB announced the approval of revised ITU-T Recommendation F.1, in accordance with Resolution 1, Section 8 of the WTSC-96 (Geneva 1996). Consequently, the TSB has prepared a new List of additional five-letter code groups for the use of the international public telegram service in conformity with ITU-T Recommendation F.1 (03/98), C98.

. This List, published as an Annex to ITU Operational Bulletin No. 669 of 1 June 1998, is based on the contributions (white documents) submitted to the former ITU-T Study Group 1. The List only incorporates five-letter code groups most commonly used in the operation of the international public telegram services which have been reviewed during the meetings of the former ITU-T Study Group 1 and then approved by the ITU-T Study Group 2 meeting held in Geneva, 3-13 March 1998.

. For practical convenience, this List contains two parts:

* In *Part I* (Decoding), all codes, irrespective of their function, are given in alphabetical order in the left-hand column. The significance of each code to which crossreferences are given is found in the right-hand column.

* In *Part II* (Coding), the codes are classified according to the fields of operation in which they are used.

. For information, the List is also available on the ITU home page (http://www.itu.int/itudoc/itu-t/ob-lists), and can be consulted by subscribers by remote access.


[yaml2text,data=../../datasets/669-F.1/data.yaml,metadata=../../datasets/669-F.1/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, boilerplates: boilerplates, lang: lang %}
----
