= Grupos de códigos de cinco letras para uso del servicio público internacional de telegramas
:bureau: T
:docnumber: 669
:series: GRUPOS DE CÓDIGOS DE CINCO LETRAS PARA USO DEL SERVICIO PÚBLICO INTERNACIONAL DE TELEGRAMAS
:series1: Según la Recomendación UIT-T F.1 (03/98)
:published-date: 1998-06-01
:status: published
:doctype: service-publication
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. En su circular TSB 104 de 23 de marzo de 1998, la TSB anunció la aprobación de la Recomendación UIT-T F.1, revisada de conformidad con el punto 8 de la Resolución 1 de la CMNT-96 (Ginebra, 1996). Por consiguiente, la TSB ha preparado una nueva lista de grupos adicionales de códigos de cinco letras para uso del servicio público internacional de telegramas de conformidad con la Recomendación UIT-T F.1 (03/98), C98.

. Esta lista, publicada en anexo al Boletín de Explotación de la UIT N.º 669 de 1 de junio de 1998, se basa en las contribuciones (documentos blancos) sometidos a la antigua Comisión de Estudio 1 del UIT-T. La lista sólo contiene los grupos de códigos de cinco letras más generalmente utilizados en la explotación del servicio público internacional de telegramas, examinados durante las reuniones de la antigua Comisión de Estudio 1 del UIT-T y aprobados por la Comisión de Estudio 2 del UIT-T en su reunión celebrada en Ginebra del 3 al 13 de marzo de 1998.

. Por razones prácticas, esta lista se divide en dos partes:

* En la *Parte I* (descodificación), los códigos figuran por orden alfabético en la columna de la izquierda independientemente de su función. El significado de cada código al que se hacen referencias cruzadas figura en la columna de la derecha.

* En la *Parte II* (codificación) los códigos se clasifican según los ramos de la explotación en que se los utiliza.

. Para información, la lista está también disponible en la página de entrada de la UIT (http://www.itu.int/itudoc/itu-t/ob-lists) y puede ser consultada en línea por los abonados mediante acceso a distancia.


[yaml2text,data=../../datasets/669-F.1/data.yaml,metadata=../../datasets/669-F.1/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----
