= Groupes d'expressions de codes à cinq lettres à l'usage du service public international des télégrammes
:bureau: T
:docnumber: 669
:series: GROUPES D'EXPRESSIONS DE CODES À CINQ LETTRES À L'USAGE DU SERVICE PUBLIC INTERNATIONAL DES TÉLÉGRAMMES
:series1: Selon la Recommandation UIT-T F.1 (03/98)
:published-date: 1998-06-01
:status: published
:doctype: service-publication
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note du TSB

. Par sa circulaire TSB 104 du 23 mars 1998, le TSB a annoncé que la Recommandation
UIT-T F.1 révisée avait été approuvée, conformément à la Résolution 1, section 8, de la CMNT-
96 (Genève, 1996). En conséquence, le TSB a établi une nouvelle liste de groupes d'expressions
de codes supplémentaires à cinq lettres à utiliser dans le service public international des
télégrammes, conformément à la Recommandation UIT-T F.1 (03/98), C98.

. Cette liste, publiée en tant qu'Annexe du Bulletin d'exploitation de l'UIT N° 669 du
1er juin 1998, est fondée sur les contributions (documents blancs) soumises à l’ancienne
Commission d'études 1 de l'UIT-T. La liste n’inclut que les groupes d'expressions de codes à cinq
lettres les plus couramment utilisés dans l'exploitation des services publics internationaux des
télégrammes et qui ont été passés en revue pendant les réunions de l’ancienne Commission
d'études 1 de l’UIT-T, puis approuvés par la Commission d'études 2 de l'UIT-T à sa réunion tenue
à Genève du 3 au 13 mars 1998.

. A des fins pratiques, la liste se compose de deux parties:

* dans la *Partie* I (décodage), toutes les expressions de codes, quelle que soit leur
fonction, sont énumérées par ordre alphabétique dans la colonne de gauche. La
signification de chaque expression de code faisant l'objet de renvois est indiquée dans la
colonne de droite.

* dans la *Partie* II (codage), les expressions de codes sont classées selon les
domaines de l’exploitation dans lesquels ils sont utilisées.

. A titre d'information, la liste est également disponible sur la page d’accueil de l'UIT
(http://www.itu.int/itudoc/itu-t/ob-lists), et peut être consultée à distance par les abonnés en ligne.


[yaml2text,T-SP-F.1-1998-MSW.yaml,file]
----
{% assign lang = "fr" %}


== Partie I - SECTION DE DÉCODAGE

Groupes d’expressions de codes à cinq lettres par ordre alphabétique:

{% for code in file.data %}
    {{- code.code }}:: {{ code.message[lang] | replace: "_", "&#95;" }}
{% endfor %}


== Partie II - SECTION DE CODAGE

Groupes d’expressions de codes à cinq lettres, classés alphabétiquement selon les domaines de
l’exploitation du service public international des télégrammes dans lesquels ils sont utilisés.

{% for field_name in file.metadata.locale %}
    {% unless field_name[0] == "coding" or field_name[0] == "decoding" %}
        {% assign field_names = field_names | append: field_name[1][lang] | append: "; " %}
    {% endunless %}
{% endfor %}

{% assign sorted_field_names = field_names | split: "; " | sort %}

{% for name in sorted_field_names %}
    {% for locale_item in file.metadata.locale %}
        {% if locale_item[1][lang] == name %}
            {% assign fields_string = fields_string | append: locale_item[0] | append: "; " %}
        {% endif %}
    {% endfor %}
{% endfor %}

{% assign fields = fields_string | split: "; " %}


{% for field in fields %}

{% assign field_data = file.data | where: "field", field %}
{% assign field_descriptions = field_data | map: "field_desc" | sort: lang | uniq %}

{% if field_descriptions.size == 0 -%}
[align=center]
*{{ file.metadata.locale[field][lang] }}*

{% for item in field_data %}
{{ item.code }}:: {{ item.message[lang] | replace: "_", "&#95;" }}
{% endfor %}

{% else -%}
[align=center]
*{{ file.metadata.locale[field][lang] }}* +
{% unless field == "enquiries" or
          field == "delivery"  or
          field == "errors_mutilations_omissions" or
          field == "repetitions_and_corrections"  or
          field == "miscellaneous" -%}
{%- if field == "addresses" or field == "disposal" -%}
(_{{ field_descriptions | map: lang | join: ", " }}, etc._)
{%- else -%}
(_{{ field_descriptions | map: lang | join: ", " }}_)
{%- endif -%}
{%- endunless %}

{% for desc in field_descriptions %}
_{{ desc[lang] }}_

{% for item in field_data %}
{% if item.field_desc[lang] == desc[lang] -%}
{{ item.code }}:: {{ item.message[lang] | replace: "_", "&#95;" }}
{%- endif %}
{% endfor %}
{% endfor %}

{% endif %}

{% endfor %}
----