= الرموز الدليلية للشبكات المتنقلة (MNC) فيما يتعلق بالخطة الدولية لتعرّف هوية الشبكات العمومية والاشتراكات )وفقاً للتوصية ITU-T E.212 (2016/09) )
:bureau: T
:docnumber: 1162
:published-date: 2018-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== ملاحظة من مكتب تقييس الاتصالات

. أعِدَّت في مكتب تقييس الاتصالات قائمة مركزية للرموز الدليلية للشبكات المتنقلة (MNC) فيما يتعلق بالخطة الدولية
لتعرّف هوية الشبكات العمومية والاشتراكات.

. تُنشَر قائمة الرموز الدليلية للشبكات المتنقلة (MNC) في ملحق بالنشرة التشغيلية للاتحاد رقم 1162 الصادرة
في 2018.XII.15 . ويُطلَب إلى الإدارات التحقّق من المعلومات الواردة في هذه القائمة وإبلاغ الاتحاد الدولي للاتصالات بأيّ
تعديلات تودّ إجراءها. واستمارة التبليغ متاحة في الموقع الإلكتروني للاتحاد على العنوان التالي:
http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx.

. ستُحَدَّث هذه القائمة بواسطة مجموعة مرقّمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. ا ولمعلومات الواردة في هذا
الملحق متاحة أيضاً في الموقع الإلكتروني للاتحاد.

. يُرجى إرسال أي تعليقات أو اقتراحات متعلقة بهذه القائمة إلى مدير مكتب تقييس الاتصالات:
+
--
[align=left]
الاتحاد الدولي للاتصالات (ITU) +
مدير مكتب تقييس الاتصالات +
الهاتف: +41 22 730 5211 +
الفاكس: +41 22 730 5853 +
البريد الإلكتروني: mailto:tsbtson@itu.int[]
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تعبّر عن أي رأي من جانب الاتحاد فيما يتعلق بالوضع القانوني
لأي بلد أو منطقة جغرافية أو لسلطات أيّ منهما.

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml,data_shared_mcc=../../datasets/1162-E.212-Shared-MCC/data.yaml,metadata_shared_mcc=../../datasets/1162-E.212-Shared-MCC/metadata.yaml,data_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/data.yaml,metadata_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/metadata.yaml,data_et=../../datasets/1162-E.212-ET/data.yaml,metadata_et=../../datasets/1162-E.212-ET/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "tables", data: data, metadata: metadata, data_shared_mcc: data_shared_mcc, metadata_shared_mcc: metadata_shared_mcc, data_shared_mcc_others: data_shared_mcc_others, metadata_shared_mcc_others: metadata_shared_mcc_others, data_et: data_et, metadata_et: metadata_et, lang: lang %}
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
تعُاد إلى مكتب تقييس الاتصالات التابع للاتحاد الدولي للاتصالات على رقم الفاكس التالي +41 22 730 5853
أو بالبريد الإلكتروني على العنوان التالي: mailto:tsbtson@itu.int[]

[align=center]
*تبليغ بتخصيص الرمز الدليلي للشبكة المتنقلة (MNC) أو سحبه من الخطة الدولية لتعرّف هوية الشبكات العمومية والاشتراكات* +
(وفقاً للتوصية ITU-T E.212)

ينبغي استخدام هذه الاستمارة لإبلاغ مدير مكتب تقييس الاتصالات بالرمز الدليلي للشبكة المتنقلة الذي خصّصته أو سحبته إحدى الدول الأعضاء
منذ التبليغ الأخير.

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

البلد/المنطقة:::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

المنظمة في الدولة العضو:::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

جهة الاتصال في الدولة العضو:::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

الاسم::::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

العنوان::::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

الهاتف::::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

الفاكس::::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

البريد الإلكتروني::::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="^,^",options="unnumbered"]
|===
| MCC + MNC
| اسم الشبكة/المشغل

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC : الرمز الدليلي القُطري للاتصالات المتنقلة Mobile Country Code / Indicatif de pays du mobile / +
MNC : الرمز الدليلي للشبكة المتنقلة Mobile Network Code / Code de réseau mobile /
----


== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
تعُاد إلى مكتب تقييس الاتصالات التابع للاتحاد الدولي للاتصالات على رقم الفاكس التالي +41 22 730 5853
أو بالبريد الإلكتروني على العنوان التالي: mailto:tsbtson@itu.int[]

[align=center]
*تبليغ باستعمال رمز ق طري للاتصالات المتنقلة/رمز شبكة متنقلة (MCC/MNC) أو إلغاء استعماله خارج الأراضي الإقليمية* +
()وفقاً للتوصية ITU-T E.212 ، الملحق E)

ينبغي لكلّ إدارة أن تستخدم هذه الاستمارة لإبلاغ مدير مكتب تقييس الاتصالات بموافقتها على أن يقوم مشغّل باستعمال/إلغاء استعمال رمز
قُطري للاتصالات المتنقلة+رمز شبكة متنقلة (MCC+MNC) لبلد معيّن )بلد A( في بلد آخر )بلد B

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*اسم جهة الاتصال في الإدارة:*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*العنوان:*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*الهاتف:*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*الفاكس:*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*البريد الإلكتروني:*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| اسم المشغل )المشغلون)
h| خارج الأراضي الإقليمية البلد B – حيث ي ستَعمَل رمز MCC/MNC
h| A سلسلة أرقام تعرف هوية المحطة المتنقلة المستعملة في بلد
h| B سلسلة أرقام تعرف هوية المحطة المتنقلة المستعملة في بلد

| | | | |
| | | | |
|===

== التعديلات

[cols="^,^,^",options="header,unnumbered"]
|===
| رقم التعديل
| رقم النشرة التشغيلية
| البلد/المنطقة

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----

