= Indicativos de red para el servicio móvil (MNC) del plan de identificación internacional para redes públicas y suscripciones (Según la Recomendación UIT-T E.212 (09/2016))
:bureau: T
:docnumber: 1162
:published-date: 2018-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Nota de la TSB

. Una Lista centralizada de los indicativos de red para el servicio móvil (MNC) del plan de identificación internacional para redes públicas y suscripciones fue creada, de la que la TSB es la depositaria.

. Esta Lista de los indicativos de red para el servicio móvil (MNC) será publicada en el Anexo al Boletín de Explotación de la UIT N.° 1162 de 15.XII.2018. Se solicita a las Administraciones que notifiquen a la UIT todas las modificaciones relacionadas sus informaciones en esta Lista.
El formulario de notificación se encuentra en el sitio web de la UIT, en la dirección: http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx.

. La Lista se actualizará por medio de enmiendas que se publicarán en el link:http://www.itu.int/pub/T-SP/es[Boletín de Explotación de la UIT]. Por otra parte, la información contenida en este Anexo está disponible en el link:https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[sitio web de la UIT].

. Sírvase comunicar sus comentarios o sugerencias con respecto a esta Lista al Director de la TSB:
Unión Internacional de Telecomunicaciones
+
--
[align=left]
Director de la TSB +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, por parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml,data_shared_mcc=../../datasets/1162-E.212-Shared-MCC/data.yaml,metadata_shared_mcc=../../datasets/1162-E.212-Shared-MCC/metadata.yaml,data_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/data.yaml,metadata_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/metadata.yaml,data_et=../../datasets/1162-E.212-ET/data.yaml,metadata_et=../../datasets/1162-E.212-ET/metadata.yaml]
----
{% assign lang = "es" %}
{% render "tables", data: data, metadata: metadata, data_shared_mcc: data_shared_mcc, metadata_shared_mcc: metadata_shared_mcc, data_shared_mcc_others: data_shared_mcc_others, metadata_shared_mcc_others: metadata_shared_mcc_others, data_et: data_et, metadata_et: metadata_et, lang: lang %}
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
Remítase a UIT/TSB Fax N.o +41 22 730 5853 / E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Formulario de notificación para la asignación/retirada de indicativos de red para el servicio móvil (MNC) del plan de indentificación internacional para redes públicas y suscripciones* +
(Según la Recomendación UIT-T E.212)

_Este formulario debe utilizarse para notificar al Director de la TSB los MNC que han sido asignados o retirados por un Estado Miembro desde la última notificación._

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

País/Zona&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Organización del Estado Miembro&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Persona encargada del Estado Miembro&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Nombre&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Dirección&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Tel&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Fax&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Correo-e&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="^,^",options="unnumbered"]
|===
| MCC + MNC | Nombre de la red/ operador

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC: Indicativo de país para el servicio móvil +
MNC: Indicativo de red para el servicio móvil
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
Remítase al número de Fax UIT/TSB No.: +41 22 730 5853/E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Formulario de notificación de utilización extraterritorial/cancelación de utilización extraterritorial de un MCC/MNC* +
(Según la Recomendación UIT-T E.212, Annexo E)

Las Administraciones emplearán este formulario para notificar al Director de la TSB que dan su acuerdo al operador para utilizar/cancelar la utilización de un MCC+MNC de País A en el País B.

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Nombre de la persona de contacto en la Administración&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Dirección&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Tel&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Fax&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Correo-e&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| Nombre del/de los operador(es)
h| País B – Donde se utiliza extraterritorialmente el MCC/MNC
h| Gama de MSIN que se utilizará en el País A
h| Gama de MSIN que se utilizará en el País B

| | | | |
| | | | |
|===

== ENMIENDAS

[cols="^,^,^",options="header,unnumbered"]
|===
| Enmienda N.°
| Boletín de Explotación N.°
| País o zona

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----

