= Коды сетей подвижной связи (MNC) для плана международной идентификации для сетей общего пользования и абонентов (Согласно Рекомендации МСЭ-Т E.212 (09/2016))
:bureau: T
:docnumber: 1162
:published-date: 2018-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:imagesdir: images
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Примечание БСЭ

. Централизованный список кодов сетей подвижной связи (MNC) для плана международной идентификации для сетей общего пользования и абонентов был составлен в БСЭ.

. Список кодов сетей подвижной связи (MNC) публикуется в качестве приложения к Оперативному бюллетеню МСЭ № 1162 от 15.XII.2018. Администрациям предлагается проверить информацию, включенную в настоящий Список, и информировать МСЭ о любых изменениях, которые они пожелают внести. Форма заявления размещена на веб-сайте МСЭ по адресу: http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx.

. Настоящий Список обновляется с помощью нумерованной серии поправок, публикуемых в link:http://www.itu.int/pub/T-SP[Оперативном бюллетене МСЭ]. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на link:https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[веб-сайте МСЭ].

. Любые замечания или предложения, касающиеся настоящего Списка, просим направлять Директору БСЭ:
+
--
[align=left]
International Telecommunication Union (ITU) +
Director of TSB +
Тел.: +41 22 730 5211 +
Факс: +41 22 730 5853 +
Эл. почта: mailto:tsbtson@itu.int[]
--

. Используемые в настоящем списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны или властей этой страны или географической зоны.

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml,data_shared_mcc=../../datasets/1162-E.212-Shared-MCC/data.yaml,metadata_shared_mcc=../../datasets/1162-E.212-Shared-MCC/metadata.yaml,data_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/data.yaml,metadata_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/metadata.yaml,data_et=../../datasets/1162-E.212-ET/data.yaml,metadata_et=../../datasets/1162-E.212-ET/metadata.yaml]
----
{% assign lang = "ru" %}
{% render "tables", data: data, metadata: metadata, data_shared_mcc: data_shared_mcc, metadata_shared_mcc: metadata_shared_mcc, data_shared_mcc_others: data_shared_mcc_others, metadata_shared_mcc_others: metadata_shared_mcc_others, data_et: data_et, metadata_et: metadata_et, lang: lang %}
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----

Направить в БСЭ МСЭ по факсу: +41 22 730 5853/эл. почте: mailto:tsbtson@itu.int[]

[align=center]
*Уведомление о присвоении или отзыве кода сети подвижной связи (MNC) для плана международной идентификации для сетей общего пользования и абонентов* +
(Согласно Рекомендации МСЭ-Т E.212)

_Настоящая форма должна использоваться для уведомления Директора БСЭ о присвоении или отзыве MNC Государством-Членом в период после последнего уведомления._

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

Страна/зона&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Организация Государства-Члена&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Лицо для контактов в Государстве-Члене&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Фамилия&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Адрес&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Тел.&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Факс&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Эл. почта&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="^,^",options="unnumbered"]
|===
| MCC + MNC | Название сети/Оператора

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC: Код страны в системе подвижной связи/Mobile Country Code +
MNC: Код сети подвижной связи/Mobile Network Code
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
Направить в БСЭ МСЭ по факсу: +41 22 730 5853/эл. почте: mailto:tsbtson@itu.int[]

[align=center]
*Уведомление об экстратерриториальном использовании или аннулировании экстратерриториального использования MCC/MNC* +
(Согласно Приложению Е к Рекомендации МСЭ-Т E.212)

Настоящая форма должна использоваться всеми администрациями для уведомления Директора БСЭ о согласии администрации с тем, что оператор может использовать/может аннулировать использование ресурса MCC+MNC страны А в стране В.

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Имя контактного лица в администрации&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Адрес&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Тел.&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Факс&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Эл. почта&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| Название(я) оператора(ов)
h| Страна B, в которой ресурс MCC/MNC должен использоваться экстратерриториально
h| Диапазон MSIN, используемый в стране A
h| Диапазон MSIN, используемый в стране B

| | | | |
| | | | |
|===

== ПОПРАВКИ

[cols="^,^,^",options="header,unnumbered"]
|===
| Поправка №
| Оперативный бюллетень №
| Страна/зона

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----

