= Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))
:bureau: T
:docnumber: 1162
:published-date: 2018-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Note from TSB

. A centralized List of Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions has been created within TSB.

. This List of Mobile Network Codes (MNC) is published as an annex to ITU Operational Bulletin No. 1162 of 15.XII.2018. Administrations are requested to verify the information in this List and to inform ITU on any modifications that they wish to make. The notification form can be found on the ITU website at link:https://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx[http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx].

. This List will be updated by numbered series of amendments published in the link:https://www.itu.int/pub/T-SP[ITU Operational Bulletin]. Furthermore, the information contained in this Annex is also available on the link:https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[ITU website].

. Please address any comments or suggestions concerning this List to the Director of TSB:
+
--
[align=left]
International Telecommunication Union (ITU) +
Director of TSB +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: tsbtson@itu.int
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml,data_shared_mcc=../../datasets/1162-E.212-Shared-MCC/data.yaml,metadata_shared_mcc=../../datasets/1162-E.212-Shared-MCC/metadata.yaml,data_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/data.yaml,metadata_shared_mcc_others=../../datasets/1162-E.212-MCC-Others/metadata.yaml,data_et=../../datasets/1162-E.212-ET/data.yaml,metadata_et=../../datasets/1162-E.212-ET/metadata.yaml]
----
{% assign lang = "en" %}
{% render "tables", data: data, metadata: metadata, data_shared_mcc: data_shared_mcc, metadata_shared_mcc: metadata_shared_mcc, data_shared_mcc_others: data_shared_mcc_others, metadata_shared_mcc_others: metadata_shared_mcc_others, data_et: data_et, metadata_et: metadata_et, lang: lang %}
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
To be returned to ITU/TSB Fax No. +41 22 730 5853 / E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Notification of assignment or withdrawal of Mobile Network Code (MNC) for the international identification plan for public networks and subscriptions* +
(According to Recommendation ITU-T E.212)

_This form should be used to notify the Director of TSB of MNC that have been assigned or withdrawn by a Member State since the last notification._

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

Country/Area&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Member State Organisation&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Member State contact-person&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Name&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Address&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Tel.&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Fax&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

E-mail&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="^,^",options="unnumbered"]
|===
| MCC + MNC | Name of Network / Operator

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC: Mobile Country Code +
MNC: Mobile Network Code
----

== {blank}

[yaml2text,data=../../datasets/1162-E.212/data.yaml,metadata=../../datasets/1162-E.212/metadata.yaml]
----
To be returned to ITU/TSB Fax No. +41 22 730 5853 / E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Notification of the use or cancellation of use of an MCC/MNC extra-territorially* +
(According to Recommendation ITU-T E.212, annex E)

This form should be used by each of the Administrations to notify the Director of TSB that the Administration has agreed that an operator can use/can cancel the use of an MCC+MNC of Country A in Country B.

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Administration Contact-Person Name&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Address&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Tel&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Fax&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*E-mail&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| Operator(s) Name
h| Country B – Where the MCC/MNC is to be used extra-territorially
h| MSIN range to be used in Country A
h| MSIN range to be used in Country B

| | | | |
| | | | |
|===

== Amendments

[cols="^,^,^",options="unnumbered"]
|===
| Amendment No.
| Operational Bulletin No.
| Country/area

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----

