= DIALLING PROCEDURES (INTERNATIONAL PREFIX, NATIONAL (TRUNK) PREFIX AND NATIONAL (SIGNIFICANT) NUMBER) (IN ACCORDANCE WITH ITU-T RECOMMENDATION E.164 (11/2010))
:bureau: T
:docnumber: 976
:published-date: 2011-12-15
:annex-title: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:keywords: 
:imagesdir: images
:docfile: T-SP-E.164C-2011-F.adoc
:language: fr
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:



== Note du TSB

. Cette Liste des «Procédures de numérotation» remplace celle qui avait été publiée dans l’Annexe au
Bulletin d'exploitation No 951 du 1.III.2010. La présente Liste récapitulative comprend tous les différents
amendements qui ont été publiés jusqu'au Bulletin d'exploitation No 994 du 15.XII.2011.

. La liste des «*Procédures de numérotation*» contient, le préfixe national (interurbain), le préfixe
international, l'indicatif de pays et le numéro national (significatif), conformément à la Recommandation UITT
E.164 (11/2010).

. Le *préfixe national (interurbain)* est un chiffre, ou une combinaison de chiffres, qu’il est nécessaire
de composer avant l'indicatif interurbain (zone) lorsque le demandeur et l'abonné appelé sont situés dans le
même pays mais pas dans la même zone de numérotage. Ce préfixe permet d’accéder à l'équipement
interurbain automatique sortant. Lorsque la case dans la colonne correspondante est laissée en blanc, cela
signifie que le pays en question a un plan national de numérotage simple sans indicatif de zone et que pour
tous les appels à l'intérieur du pays il faut composer tous les chiffres du numéro local.
+
--
De même, dans le service international, le préfixe interurbain du pays de destination ne doit pas être
composé. L'UIT-T recommande aux Administrations des pays qui ne disposent pas encore d'un préfixe
interurbain ou qui veulent le modifier d'adopter un préfixe à un seul chiffre, «0» de préférence.
--

. Le *préfixe international* est un chiffre, ou une combinaison de chiffres, qu’il est nécessaire de
composer avant l'indicatif de pays lorsqu'on appelle un correspondant situé dans un autre pays. Lorsque la
case dans la colonne correspondante est laissée en blanc , cela signifie que le pays en question ne dispose
pas d'un service international automatique (en d'autres termes, tous les appels internationaux dans ce pays
nécessitent l'intervention d'une opératrice).
+
--
L'UIT-T recommande aux Administrations des pays qui ne disposent pas encore d'un service
international automatique ou qui, pour des raisons diverses, veulent modifier leur plan de numérotage,
d'adopter le code «00» comme préfixe international (code d'accès au réseau automatique international).
--

. L'**indicatif de pays** est un chiffre, ou une combinaison de deux ou trois chiffres, qui caractérise le
pays appelé et qui est utilisé pour l'acheminement des appels vers le pays en question. Cet indicatif est
généralement composé après le préfixe international. La liste des indicatifs de pays est publiée également
dans la «Liste des indicatifs de pays de la Recommandation UIT-T E.164 attribués», en annexe au Bulletin
d’exploitation.

. Le *numéro national (significatif)* est le numéro qui est composé après le préfixe national
(interurbain) pour appeler un abonné situé dans le même pays que le demandeur mais en dehors du réseau
local ou de la zone de numérotage de ce demandeur. Le numéro national (significatif) est composé de
l’indicatif interurbain suivi du numéro d’abonné. Lorsque la case dans la colonne correspondante est laissée
en blanc, cela signifie que cette information manque.

. Pour votre information, la présente Liste est publiée comme Annexe au Bulletin d'exploitation de l'UIT.
En outre, les informations contenues dans cette Annexe sont également disponibles sur le site web de l’UIT
link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Tout a été mis en oeuvre pour que les informations contenues dans l'Annexe soient exactes. Les
Administrations sont invitées à nous faire parvenir toutes les modifications ou informations manquantes
concernant leurs préfixes nationaux (interurbains), les préfixes internationaux et la longueur de leurs
numéros nationaux (significatifs) en utilisant le formulaire ci-joint.

. Les appellations employées dans cette Liste et la présentation des données qui y figurent
n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones
géographiques, ou leurs autorités.


[yaml2text,T-SP-E.164C-2011.yaml,file]
----
{% assign lang = "fr" %}

== {{ file.metadata.title[lang] | split: " (" | first | downcase | capitalize }}

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign last_word = note_content.en | split: " " | last %}
    {% case last_word %}
        {% when "services)" %}
            {% assign note_1 = note_content[lang] %}
        {% when "countries." %}
            {% assign note_2 = note_content[lang] %}
        {% when "28'." %}
            {% assign note_3 = note_content[lang] %}
        {% when "Helena." %}
            {% assign note_4 = note_content[lang] %}
        {% when "'0039'." %}
            {% assign note_5 = note_content[lang] %}
        {% when "UTC+9." %}
            {% assign note_6 = note_content[lang] %}
        {% when "digits." %}
            {% assign note_7 = note_content[lang] %}
        {% when "'0101')." %}
            {% assign note_8 = note_content[lang] %}
        {% when "'0065'." %}
            {% assign note_9 = note_content[lang] %}
        {% when "UTC-7/DST-6." %}
            {% assign note_10 = note_content[lang] %}
        {% when "UTC-5/DST-4." %}
            {% assign note_11 = note_content[lang] %}
        {% when "(UTC+8)." %}
            {% assign note_12 = note_content[lang] %}
        {% when "Authority." %}
            {% assign note_13 = note_content[lang] %}
        {% when "code." %}
            {% assign note_14 = note_content[lang] %}
        {% when "scheme." %}
            {% assign note_15 = note_content[lang] %}
        {% when "'39')." %}
            {% assign note_16 = note_content[lang] %}
        {% when "UTC+11/DST+12." %}
            {% assign note_17 = note_content[lang] %}
        {% when "change)." %}
            {% assign note_18 = note_content[lang] %}
        {% when "Tanzania." %}
            {% assign note_19 = note_content[lang] %}
        {% when "only." %}
            {% assign note_20 = note_content[lang] %}
        {% when "UTC-10." %}
            {% assign note_21 = note_content[lang] %}
        {% when "070)." %}
            {% assign note_22 = note_content[lang] %}
        {% when "network." %}
            {% assign note_23 = note_content[lang] %}
    {% endcase %}
{% endfor %}

[cols="7*^",options="unnumbered"]
|===

h| {{ file.metadata.locale.country_or_area[lang] }}
h| {{ file.metadata.locale.country_code[lang] }}
h| {{ file.metadata.locale.international_prefix[lang] }}
h| {{ file.metadata.locale.national_prefix[lang] }}
h| {{ file.metadata.locale.national_sig_number[lang] }}
h| UTC/DST footnote:[UTC = Universal Time Coordinated, DST = Daylight Saving Time]
h| {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data %}
   <| {{ country_data.country_or_area[lang] }}
    | {{ country_data.country_code }}
    | {{ country_data.international_prefix }}
    | {{ country_data.national_prefix }}
    | {{ country_data.national_sig_number }}
    | {{ country_data.utc_dst }}
    |
    {%- assign last_word = country_data.note.en | split: " " | last -%}
    {%- case last_word -%}
        {%- when "services)" -%}
            <<note_1,1>>
        {%- when "countries." -%}
            <<note_2,2>>
        {%- when "28'." -%}
            <<note_3,3>>
        {%- when "Helena." -%}
            <<note_4,4>>
        {%- when "'0039'." -%}
            <<note_5,5>>
        {%- when "UTC+9." -%}
            <<note_6,6>>
        {%- when "digits." -%}
            <<note_7,7>>
        {%- when "'0101')." -%}
            <<note_8,8>>
        {%- when "'0065'." -%}
            <<note_9,9>>
        {%- when "UTC-7/DST-6." -%}
            <<note_10,10>>
        {%- when "UTC-5/DST-4." -%}
            <<note_11,11>>
        {%- when "(UTC+8)." -%}
            <<note_12,12>>
        {%- when "Authority." -%}
            <<note_13,13>>
        {%- when "code." -%}
            <<note_14,14>>
        {%- when "scheme." -%}
            <<note_15,15>>
        {%- when "'39')." -%}
            <<note_16,16>>
        {%- when "UTC+11/DST+12." -%}
            <<note_17,17>>
        {%- when "change)." -%}
            <<note_18,18>>
        {%- when "Tanzania." -%}
            <<note_19,19>>
        {%- when "only." -%}
            <<note_20,20>>
        {%- when "UTC-10." -%}
            <<note_21,21>>
        {%- when "070)." -%}
            <<note_22,22>>
        {%- when "network." -%}
            <<note_23,23>>
    {%- endcase %}
{% endfor %}

|===

{{ file.metadata.locale.note[lang] | append: "s"}}

. [[note_1]]{{ note_1 }}
. [[note_2]]{{ note_2 }}
. [[note_3]]{{ note_3 }}
. [[note_4]]{{ note_4 }}
. [[note_5]]{{ note_5 }}
. [[note_6]]{{ note_6 }}
. [[note_7]]{{ note_7 }}
. [[note_8]]{{ note_8 }}
. [[note_9]]{{ note_9 }}
. [[note_10]]{{ note_10 }}
. [[note_11]]{{ note_11 }}
. [[note_12]]{{ note_12 }}
. [[note_13]]{{ note_13 }}
. [[note_14]]{{ note_14 }}
. [[note_15]]{{ note_15 }}
. [[note_16]]{{ note_16 }}
. [[note_17]]{{ note_17 }}
. [[note_18]]{{ note_18 }}
. [[note_19]]{{ note_19 }}
. [[note_20]]{{ note_20 }}
. [[note_21]]{{ note_21 }}
. [[note_22]]{{ note_22 }}
. [[note_23]]{{ note_23 }}


== AMENDMENTS

[cols="^,^,^",options="unnumbered,header"]
|===
| Amendment No | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===


== Formulaire de notification

{% assign large_length = 100 %}

[align=center]
*PROCÉDURES DE NUMÉROTATION* +
*(Selon la Recommandation UIT-T E.164)*

Nom du pays&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Indicatif de pays&#58;:: 
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Préfixe international&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

National Prefix&#58;:: 
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Longueur du numéro national (significatif)&#58;::
+
--
minimum 
{% for i in (1..50) -%}
&#95;
{%- endfor %} +
maximum 
{% for i in (1..50) -%}
&#95;
{%- endfor %} +
(non compris le préfixe national)
--

Temps universel coordonné/Horaire d’été&#58;:: 
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Commentaires&#58;::
+
--
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}
--

Personne à contacter&#58;::
+
--
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Tél: +
{%- for i in (1..40) -%}
&#95;
{%- endfor %}
Fax: + 
{%- for i in (1..40) -%}
&#95;
{%- endfor %} +
E-mail: 
{%- for i in (1..85) -%}
&#95;
{%- endfor %}
--
----