= LISTA DE CÓDIGOS DE IDENTIFICACIÓN DE RED DE DATOS (CIRD)
:bureau: T
:docnumber: 977
:series: SEGÚN LA RECOMENDACIÓN UIT-T X.121 (10/2000)
:published-date: 2011-04-01
:status: in-force
:doctype: service-publication
:annex-id: No. 977
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. La Recomendación UIT-T X.121 especifica que la UIT administra la asignación de indicativos de país para datos (IPD). Cada administración efectuará la atribución de cifras de red para crear códigos de identificación de red de datos (CIRD). Las nuevas atribuciones, reatribuciones o supresiones de cifras de red deben notificarse a la TSB de la UIT, por medio del formulario de notificación que figura en la última página de la lista.

. Conforme a la Recomendación UIT-T X.121, la información sobre la asignación de códigos de identificación de red de datos (CIRD) se ha publicado por separado en el Boletín de Explotación de la UIT y posteriormente se ha incluido en una «Lista de códigos de identificación de red de datos (CIRD)».

. La Lista del corriente año reemplaza a la publicada en el Anexo al Boletín de Explotación de la UIT N.° 876 del 15 de enero de 2007 y refleja todas las enmiendas publicadas en los Boletines de Explotación de la UIT hasta el N.° 977 del 1 de abril de 2011.

. Para mantener actualizada esta Lista, se ruega a las administraciones que verifiquen la exactitud de las informaciones publicadas y que informen a la TSB sobre cualquier cambio que deba efectuarse para su actualización.

. Para las nuevas asignaciones de códigos de identificación de red de datos (CIRD), las administraciones deben cumplimentar el formulario de notificación (véase la última página de la lista) y remitirlo a la TSB, a la dirección indicada en el formulario.

. Se señala que esta Lista está disponible en la página web de la UIT:
+
--
[align=center]
link:https://www.itu.int/itu-t/bulletin/annex.html[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no entrañan, por parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.


== {blank}

[data2text,data=../../datasets/977-X.121B/data.yaml,metadata=../../datasets/977-X.121B/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== ENMIENDAS

[cols="^,^,^",options="unnumbered,header"]
|===
| Enmienda N.° | Boletín de Explotación N.° | País o zona geográfica

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----


== {blank}

[cols="1",options="unnumbered"]
|===
a| _Este formulario de notificación debe remitirse a:_ +
*Unión Internacional de Telecomunicaciones* +
*Oficina de Normalización de las Telecomunicaciones (TSB)* +
*Place des Nations* +
*CH -- 1211 Genève 20* +
*Suisse* +
*Tel.:   +41 22 730 5211     Fax:   +41 22 730 5853     E-mail:   tsbtson@itu.int*

|===


[cols="2",options="unnumbered"]
|===
2+^.^h| Notificación para la asignación de códigos de identificación de red de datos (CIRD) por las administraciones {blank}footnote:[Puede adjuntarse a este formulario, si se desea, una descripción de la red a la que se ha atribuido el CIRD.]

| Nombre y dirección de la administración: |
| CIRD N.°{blank}footnote:[Si el CIRD es compartido por varias redes, deberán mostrarse las asignaciones de la gama de números. Por ejemplo, del CIRD 750 1 compartido por varias redes, el número 750 11 está asignado a le «red A» y los números 750 12 a 750 14 están asignados a la «red B».]: |
| Nombre de la red a la cual se ha atribuido el CIRD {blank}footnote:[Deberá utilizarse un formulario aparte para cada CIRD.]: |
| Localidad de la red (país o zona geográfica): |
| Fecha de notificación: |
| Dirección postal de la entidad que presta el servicio y ala que se puede solicitar información adicional: | \_\____\__\_____\______\____

| Tel.: | \_\____\__\_____\______\____
| Fax: | \_\____\__\_____\______\____
| E-mail: | \_\____\__\_____\______\____

| Su referencia: |
| Fecha: |
| Firma: |
|===

