= LISTA DE INDICATIVOS DE PAÍS O ZONA GEOGRÁFICA PARA EL SERVICIO MOVÍL
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Nota de la TSB

. Esta Lista de indicativos de país o zona geográfica para el servicio movíl reemplaza la publicada en el Anexo al Boletín de Explotación de la UIT N.o 1005 del 1 de junio de 2012. Desde entonces, se han efectuado varias asignaciones nuevas, que se han publicado en diferentes números del Boletín de Explotación de la UIT.

. La presente Lista comprende:
+
--
* una lista de indicativos de país o zona geográfica para el servicio movíl - en orden numérico;
* una lista de indicativos de país o zona geográfica para el servicio movíl - en orden alfabético.
--

. La Lista se actualizará por series de enmiendas numeradas que se publicarán en el Boletín de Explotación de la UIT. Por otra parte, la información contenida en este Anexo está disponible en el sitio web de la UIT (link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Sírvase comunicar sus comentarios con respecto a esta publicación al Director de la TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
Email: mailto:tsbmail@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.

[yaml2text,data=../../datasets/1117-E.212A/data.yaml,metadata=../../datasets/1117-E.212A/metadata.yaml,data_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/data.yaml,metadata_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/metadata.yaml]
----
{% assign lang = "es" %}
{% render "tables", data: data, metadata: metadata, data_mcc_mnc: data_mcc_mnc, metadata_mcc_mnc: metadata_mcc_mnc, lang: lang %}

== Número de indicativos de país o zona geográfica para el servicio movíl UIT-T E.212 (MCCs) de reserva

[cols="^,^",options="unnumbered"]
|===
| Indicativos de país o zona geográfica para el servicio movíl, gama de números | Número de indicativos de país de reserva

| 000 - 099 | Reservado
| 100 - 199 | Reservado
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | Reservado
| 900 - 999 | 99
|===

== ENMIENDAS

[cols="^,^,^",options="unnumbered"]
|===
| Enmienda N.° | Boletín de Explotación N.° | País

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}

|===

----