= قائمة بالرموز الدليلة القُطرية أو الخاصة بالمناطق الجغرافية للاتصالات المتنقلة
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== ملاحظة من مكتب تقييس الاتصالات

. تحل قائمة الرموز الدليلية للبلدان أو للمناطق الجغرافية من أجل الاتصالات المتنقلة محل القائمة السابقة التي نُشرت في شكل
ملحق بالنشرة التشغيلية للاتحاد رقم 1005 بتاريخ 1 يونيو 2012 . ومنذ ذلك الحين، مُنحت توزيعات جديدة مختلفة ونُشرت
في النشرة التشغيلية للاتحاد.

. تشمل هذه القائمة:
+
--
* قائمة بالرموز الدليلية للبلدان أو للمناطق الجغرافية من أجل الاتصالات المتنقلة – بالترتيب العددي؛
* قائمة بالرموز الدليلية القطرية أو للمناطق الجغرافية من أجل الاتصالات المتنقلة – بالترتيب الهجاائ .
--

. وسيجاري تحديث القائمة من خلال سلسلة مرقّمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. وعلاوة على ذلك،
تتاح أيضا المعلومات الواردة في هذا الملحق في الموقع الإلكتروني للاتحاد:
link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. و يُرجى توجيه أي تعليقات تتعلق بهذا النشر إلى مدير مكتب تقييس الاتصالات:
+
--
الهاتف: +41 22 730 5887 +
الفاكس: +41 22 730 5853 +
البريد الإلكتروني: mailto:tsbmail@itu.int[]
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تعبّر عن أي رأي من جانب الاتحاد بشأن الوضع القانوني
لأي بلد أو منطقة جغرافية أو لسلطات أيّ منهما.

[yaml2text,data=../../datasets/1117-E.212A/data.yaml,metadata=../../datasets/1117-E.212A/metadata.yaml,data_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/data.yaml,metadata_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "tables", data: data, metadata: metadata, data_mcc_mnc: data_mcc_mnc, metadata_mcc_mnc: metadata_mcc_mnc, lang: lang %}

== وفقاً للتوصية ITU-T E.212 عدد الرموز الدليلية الاحتياطية للبلدان أو للمناطق الجغرافية من أجل الاتصالات المتنقلة (MCC)

[cols="^,^",options="unnumbered"]
|===
| الرموز الدليلية للبلدان أو للمناطق الجغرافيةمن أجل الاتصالات المنتقلة، سلسلة الأرقام
| عدد الرموز الدليلية الاحتياطية

| 000 - 099 | محجاوز
| 100 - 199 | محجاوز
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | محجاوز
| 900 - 999 | 99
|===

== التعديلات

[cols="^,^,^",options="unnumbered"]
|===
| رقم التعديل
| رقم النشرة التشغيلية
| البلد

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----
