= СПИСОК ПРИСВОЕННЫХ КОДОВ СТРАНЫ СОГЛАСНО РЕКОМЕНДАЦИИ МСЭ-Т E.164
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Примечание БСЭ

. Настоящий Список кодов страны или географической зоны для подвижной связи заменяет Список, ранее опубликованный в качестве Приложения к Оперативному бюллетеню МСЭ № 1005 от 1 июня 2012 года. С тех пор БСЭ были осуществлены различные новые присвоения, и они были опубликованы в Оперативном бюллетене МСЭ.

. Настоящий Список включает:
+
--
* список кодов страны или географической зоны для подвижной связи – в нумерационном порядке;
* список кодов страны или географической зоны для подвижной связи – в алфавитном порядке.
--

. Настоящий Список будет обновляться с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: www.itu.int/itu-t/bulletin/annex.html.

. Любые замечания, касающиеся настоящей публикации, просим направлять Директору БСЭ:
+
--
Тел.: +41 22 730 5887 +
Факс: +41 22 730 5853 +
Эл. почта: mailto:tsbmail@itu.int[]
--

. Используемые в настоящем Списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны или властей этой страны или географической зоны.


[yaml2text,data=../../datasets/1117-E.212A/data.yaml,metadata=../../datasets/1117-E.212A/metadata.yaml,data_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/data.yaml,metadata_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/metadata.yaml]
----
{% assign lang = "ru" %}
{% render "tables", data: data, metadata: metadata, data_mcc_mnc: data_mcc_mnc, metadata_mcc_mnc: metadata_mcc_mnc, lang: lang %}

== Количество резервных кодов страны или географической зоны для подвижной связи (MCC) согласно Рекомендации МСЭ-Т E.212

[cols="^,^",options="unnumbered"]
|===
| Коды страны или географической зоны для подвижной связи, диапазон номеров
| Количество резервных кодов

| 000 - 099 | зарезервированы
| 100 - 199 | зарезервированы
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | зарезервированы
| 900 - 999 | 99
|===

== ПОПРАВКИ

[cols="^,^,^",options="unnumbered"]
|===
| Поправка № | Оперативный бюллетень № | Страна

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===

----
