= LISTE DES INDICATIFS DE PAYS OU DE ZONES GÉOGRAPHIQUES DU MOBILE
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Note du TSB

. Cette Liste des indicatifs de pays ou de zones géographiques du mobile remplace celle qui avait été publiée dans l’Annexe au Bulletin d’exploitation de l'UIT No 1005 du 1 juin 2012.
Depuis lors, différentes assignations nouvelles sont apparues et ont été publiées séparément dans différents numéros du Bulletin d'exploitation de l'UIT.

. La présente Liste comprend:
+
--
* une liste des indicatifs de pays ou de zones géographiques du mobile - par ordre numérique;
* une liste des indicatifs de pays ou de zones géographiques du mobile - par ordre alphabétique.
--

. La mise à jour de cette liste se fera par des séries d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles sur le site web de l’UIT (à l'adresse link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Veuillez adresser vos commentaires concernant cette publication au Directeur du TSB:
+
--
Tél: +41 22 730 5857
Fax: +41 22 730 5853
Email: mailto:tsbmail@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.

[yaml2text,data=../../datasets/1117-E.212A/data.yaml,metadata=../../datasets/1117-E.212A/metadata.yaml,data_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/data.yaml,metadata_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "tables", data: data, metadata: metadata, data_mcc_mnc: data_mcc_mnc, metadata_mcc_mnc: metadata_mcc_mnc, lang: lang %}

== Nombre des indicatifs de pays ou de zones géographiques du mobile UIT-T E.212 (MCCs) en réserve

[cols="^,^",options="unnumbered"]
|===
| Indicatifs de pays ou de zones géographiques du mobile, série de numéros | Nombre des indicatifs de pays du mobile en réserve

| 000 - 099 | Réservé
| 100 - 199 | Réservé
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | Réservé
| 900 - 999 | 99
|===

== AMENDEMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendement N° | Bulletin d'exploitation N° | Pays

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}

|===

----

