= LIST OF MOBILE COUNTRY OR GEOGRAPHICAL AREA CODES
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Note from TSB

. This List of mobile country or geographical area codes replaces the previous one published
as Annex to ITU Operational Bulletin No. 1005 of 1 June 2012. Since then, various new
assignments have been made, and they have been published in the ITU Operational Bulletin.

. This List includes:
+
--
* a list of mobile country or geographical area codes - in numerical order;
* a list of mobile country or geographical area codes - in alphabetical order.
--

. This List will be updated by numbered series of amendments published in the ITU
Operational Bulletin. Furthermore, the information contained in this Annex is also available on the
ITU website link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Please address any comments concerning this publication to the Director of TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
Email: mailto:tsbmail@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the
expression of any opinion whatsoever on the part of ITU concerning the legal status of any country
or geographical area, or of its authorities.

[yaml2text,data=../../datasets/1117-E.212A/data.yaml,metadata=../../datasets/1117-E.212A/metadata.yaml,data_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/data.yaml,metadata_mcc_mnc=../../datasets/1117-E.212A-MCCMNC/metadata.yaml]
----
{% assign lang = "en" %}
{% render "tables", data: data, metadata: metadata, data_mcc_mnc: data_mcc_mnc, metadata_mcc_mnc: metadata_mcc_mnc, lang: lang %}

== Number of spare ITU-T E.212 Mobile Country or Geographical Area Codes (MCCs)

[cols="^,^",options="unnumbered"]
|===
| Mobile Country or Geographical Area Codes, number range | Number of spare codes

| 000 - 099 | reserved
| 100 - 199 | reserved
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | reserved
| 900 - 999 | 99
|===

== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendment No. | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===

----


