= Lista de las autoridades nacionales, encargadas de asignar los códigos de proveedor de terminal UIT-T T.35
:title-es: Lista de las autoridades nacionales, encargadas de asignar los códigos de proveedor de terminal UIT-T T.35
:annex-title-es: Anexo al Boletín de Explotación de la UIT
:annex-id: N.° 1001
:bureau: T
:docnumber: 1001
:published-date: 2012-04-01
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:
:language: es

[preface]
== Nota de TSB:

En la Recomendación UIT-T T.35 se describe un mecanismo para incluir facilidades no normalizadas, que se utilizan en distintos protocolos definidos en las Recomendaciones del UIT-T. En este mecanismo se utilizan tres tipos de códigos: (a) un indicativo de país, (b) un código de proveedor terminal (también conocido como código de fabricante) y (c) un código destinado al proveedor terminal. Los indicativos de país de la Recomendación UIT-T T.35 quedan definidos en esta Recomendación y el fabricante define los códigos destinados al proveedor terminal. No obstante, en cuanto al código de fabricante, la Recomendación UIT-T T.35 dispone lo siguiente: «Una administración o un organismo nacional designado por dicha administración tiene la responsabilidad de asignar y gestionar los códigos de proveedor terminal».

A fin de facilitar una lista centralizada de autoridades nacionales para asignación de los códigos de proveedor terminal UIT-T T.35 y ayudar a los fabricantes a obtener dichos códigos, la Recomendación UIT-T T.35 indica además: «Cuando una administración designa un organismo nacional, debe enviar su nombre y dirección al Director de la TSB».

Se ha elaborado una lista de las autoridades nacionales, encargadas de asignar los códigos de proveedor de terminal UIT-T T.35, según las respuestas a la Circular TSB 184 del 12 de septiembre de 2003 y al Addendum 1 del 30 de julio de 2004. +

Por medio del http://www.itu.int/ITU-T/inr/forms/files/T35-form-es.doc[formulario de notificación], se comunicará a la TSB toda información nueva o actualizada, referente a la identidad de la autoridad nacional vigente designada por cada administración para la asignación de los códigos de proveedor de terminal UIT-T T.35 a la TSB, E mail: mailto:tsbtson@itu.int[tsbtson@itu.int], Fax: +41 22 730 5853.

Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.

== {blank}

[yaml2text,data=../../datasets/1001-T.35B/data.yaml,metadata=../../datasets/1001-T.35B/metadata.yaml,acronyms=../../datasets/1001-T.35B/acronyms.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, acronyms: acronyms, lang: lang %}
----

<<<

[%unnumbered]
|===
Envíe las respuestas a esta notificación a TSB, E-mail: mailto:tsbtson@itu.int[tsbtson@itu.int], Fax: +41 22 730 5853.

|===

== Notificación de la Administración sobre la identificación de las autoridades nacionales encargadas de asignar los códigos de proveedor terminal definidos en la Recomendación UIT-T T.35

_Le rogamos que en sus respuestas nos facilite la mayor cantidad posible de detalles. Cuando no pueda darnos datos completos porque se trata de información delicada o confidencial, sírvase indicarlo. Las respuestas al cuestionario recibidas se utilizarán para actualizar la lista de las autoridades nacionales encargadas de asignar códigos de proveedor terminal definidos en la Recomendación UIT T T.35._

[class=steps]
. País y nombre de la Administración:

. ¿Existen en su país fabricantes de productos definidos en las:

* Recomendaciones UIT‑T de la serie H (videoconferencia, +
conferencias multimedios) ▭ Sí ▭ No

* Recomendaciones UIT‑T de la serie T (conferencias de datos, facsímil)? ▭ Sí ▭ No

* Recomendaciones UIT‑T de la serie V (equipos de módem) ▭ Sí ▭ No

. ¿En su país existe un organismo nacional u otra autoridad encargada de asignar códigos de proveedor terminal con arreglo a la Recomendación UIT‑T T.35? ▭ Sí ▭ No

. Según el caso, sírvase facilitar la información siguiente sobre *cada* autoridad de asignación (en caso de autoridades diferentes para tipos de terminal distintos):
+
--
[%unnumbered]
|===
h| Autoridad de asignación: a|
| Tipo de terminal{blank}footnote:[Márquense todos los aplicables y enumérese las "otras categorías"]: | ▭ Serie H ▭ Serie T ▭ Serie V ▭ Otras categorías:
| Persona a quien dirigirse: a|
| Organización: a|
| Departamento: a|
| Dirección: a|
| Teléfono: a|
| Telefax: a|
| E-mail: a|
| Enlaces correspondientes de Internet: a|

|===
--

. Comentarios

[%unnumbered]
|===
|

|===
