= قائمة ب رموز المشغلين الصادرة عن الاتحاد
:bureau: T
:docnumber: M.1400
:published-date: 2014-09-15
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1060
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== ملاحظة من مكتب تقييس الاتصالات

. نظراً لأن عدد مشغلي الاتصالات في كل بلد ينمو بسرعة، فإن عدد التوصيلات البينية لشبكاتهم يزداد بسرعة أكبر. ولذلك،
يحظى تقييس تسميات جميع التوصيلات البينية للشبكة بأهمية كبيرة لدى المشغلين المعنيين. وفي هذه الحالة سيكون بوسعهم توفير الخدمات
والصيانة بطريقة منهجية وفعالة.

. يتطلب الاستخدام السليم للتوصية ITU-T M.1400 تعرف هوية المشغلين الذين يتقاسمون التوصيل البيني. وبغية تحقيق ذلك،
سيكون من المفيد للغاية وضع قائمة شاملة بالمشغلين العاملين في بلد ما، مع مدونة موحدة ومعترف بها رسمي اً لكل منهم. وستم ك نهم هذه
القائمة من التعرف على بعضهم بعض اً بطريقة شاملة وفريدة من نوعها. وسيؤدي هذا الأمر في نهاية المطاف إلى وضع قاعدة بيانات واحدة
متكاملة لجميع التوصيلات وكذلك تحسين عمليات الشبكة وإدارتها لفائدة مقدمي الخدمات والزبائن على السواء.

. نظراً إلى تحرير الاتصالات واحتدام المنافسة في مجال صناعة الاتصالات، ثمة شرط إلزامي يقضي بضرورة تعرف هوية مشغلي
الاتصالات الذين يشغلون الشبكات تشغيلاً بيني اً. ووضعت قائمة مركزية برموز المشغلين (ICC) الخاصة بالاتحاد ويتولى مكتب تقييس
الاتصالات في الاتحاد حفظها. ومن المتوقع أن يقوم جميع المشغلين المحليين والدوليين بالتسجيل لدى مكتب تقييس الاتصالات في الاتحاد
للحصول على رمز المشغل. وبدلاً من قيام فرادى المشغلين بإرسال رموز المشغل لديهم الصاد رة عن الاتحاد إلى مكتب تقييس الاتصالات
من أجل تسجيلها، يُطلب من هيئات التنظيم الوطنية إرسال الرموز المتحقق منها والمعلومات ذات الصلة المتعلقة بمشغلي الشبكة المحليين
والدوليين إلى مكتب تقييس الاتصالات مباشرة وذلك من خلال استعمال استمارة التبليغ ICC المتاحة على الخط في العنوان
التالي:
link:https://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx[http://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx].

. وتسمح القائمة ICC بتعرف هوية المشغلين المعترف بهم لدى كل إدارة من إدارات الدول الأعضاء. وتتاح هذه القائمة في الموقع
الإلكتروني المركزي ICC ITU في العنوان التالي: T/inr/icc/index.html-www.itu.int/ITU . ويمكن استعمال الرموز ICC في التجارة الإلكترونية
بين المشغلين وفي تسمية موارد شبكاتهم على السواء. وهكذا، يمكن تخصيص هذه الرموز لكل من مشغلي الشبكة وموردي الخدمات.

. وتحل قائمة رموز المشغلين الصادرة عن الاتحاد هذه محل القائمة التي نُشرت في شكل ملحق بالنشرة التشغيلية للاتحاد رقم 981
المؤرخة 2011.VI.1 . ومنذ ذلك الحين، ورد عدد من التبليغات إلى مكتب تقييس الاتصالات ونشرت هذه التبليغات بشكل منفصل
في الأعداد المختلفة من النشرة التشغيلية للاتحاد. وتلخص هذه القائمة جميع التعديلات المختلفة التي نشرت حتى النشرة التشغيلية رقم 1060
المؤرخة
2014.IX.15.

. وسيجري تحديث القائمة من خلال سلسلة مرقمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. وعلاوة على ذلك، تتاح
أيضاً المعلومات الواردة في هذا الملحق في الموقع الإلكتروني للاتحاد:
link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/annex.html].

. ويرجى توجيه أي تعليقات أو اقتراحات أو تخصيصات جديدة تتعلق بهذه القائمة إلى مدير مكتب تقييس الاتصالات:
+
--
International Telecommunication Union +
Director of TSB +
+41 22 730 5853: الفاكس +
mailto:tsbtson@itu.int[]: البريد الإلكتروني
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تع بر عن أي رأي من جانب الاتحاد بشأن الوضع القانوني لأي بلد
أو منطقة جغرافية أو لسلطات أ ي منهما.


[%landscape]
<<<

== {blank}

[yaml2text,data=../../datasets/1060-M.1400/data.yaml,metadata=../../datasets/1060-M.1400/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

[%portrait]
<<<

== استمارة التبليغ المتعلقة بقائمة رموز المشغلين الصا ردة عن الاتحاد footnote:[http://www.itu.int/oth/T0206000006/en]

منذ 1 يناير 2004 ، أُلزم المشغلون الذين يستعملون التوصية ITU-T M.1400 بتقديم معرف هوية المشغل أو رمز المشغل الصادر عن الاتحاد (ICC)
في البنية المنقحة للطبقة 1 بغية تعريف هوية طرفي انتهاء المسير. والرمز ICC إلزامي في التوصيلات البينية بين المشغلين في مختلف البلدان
والمشغلين المختلفين في نفس البلد. ويُستعمل هذا الرمز في سجلات معلومات الطبقة 1 للتوصية ITU-T M.1400 للتعرف بدقة على هوية
طرفي انتهاء المسير. ويُستعمل أيضاً لأغراض تسجيل المشغل للمشغلين الذين لديهم توصيل بيني معه.

بغية وضع قائمة بالرموز ICC يمكن استعمالها لتعرف هوية مشغلي التوصيل البيني في سجلات التوصية ITU-T M.1400 على النحو الموضح
في هذه التوصية، يُطلب من هيئات التنظيم الوطنية استكمال استمارة التبليغ التالية مع الإشارة إلى الرموز المتحقق منها والمعلومات ذات
الصلة المتعلقة بالمشغلين المحليين والدوليين على السواء. وعند استكمال استمارة التبليغ، ينبغي إرسالها إلى مكتب تقييس الاتصالات مباشرة
إلى العنوان التالي:


مدير مكتب تقييس الاتصالات (TSB) +
الاتحاد الدولي للاتصالات (ITU) +
Place des Nations +
1211 Geneva 20 +
Switzerland +
البريد الإلكتروني: mailto:tsbtson@itu.int[] +
الفاكس: +41 22 730 58 53


. *الاسم الكامل للشركة:* +
(اسم المشغل)

. *رمز الشركة:*
+
--
[cols="6",options="unnumbered"]
|===
| | | | | |
|===

(الرمز الذي يرغب المشغل بموجبه أن يعرف هويته. وينبغي أن يكون هذا الرمز مؤلفاً من حروف أبجدية أو رموز رقمية ) A إلى Z (:) 0 إلى 9 ،
حتى ستة أحرف و/أو أرقام تُعد أقصى، وأن يمثل معرف هوية وحيداً لمشغل شبكة/مورد خدمة في كل بلد. وقد يكون هذا الرمز مستعملاً
فعلاً اليوم شريطة أن يطابق التعريف).
--

. *العنوان الرسمي للشركة:*

. *جهة الاتصال:*
+
--
الهاتف: + +
الفاكس: + +
البريد الإلكتروني:
--

*التاريخ:*


== التعديلات

[cols="^,^,^,^",options="unnumbered"]
|===
h| رقم التعديل
h| رقم النشرة التشغيلية
h| البلد/المنطقة
h| الرمز ICC

{% for i in (1..33) %}
| {{ i }} | | |
{% endfor %}
|===
----


