= List of Signalling Area/Network Codes (SANC) (Complement -- Recommendation ITU-T Q.708 (03/99))
:bureau: T
:docnumber: Q.708
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annextitle: Annex -- ITU Operational Bulletin
:annexid: No. 1125 - 1.VI.2017
:keywords: 
:imagesdir: images
:docfile: T-SP-Q.708A-2017-E.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:

[preface]
== Примечание БСЭ

. Настоящий Список зоновых/сетевых кодов сигнализации (SANC) заменяет Список, опубликованный в качестве Приложения к Оперативному бюллетеню МСЭ № 1066 от 15 декабря 2014 года. С тех пор были осуществлены различные новые присвоения, которые были опубликованы отдельно в разных выпусках Оперативного бюллетеня МСЭ. В настоящий Список включены все поправки, которые были опубликованы в номерах Оперативного бюллетеня до № 1125 от 1 июня 2017 года включительно.

. Настоящий Список включает:
+
--
* список кодов SANC в нумерационном порядке;
* список кодов SANC в алфавитном порядке названий стран/географических областей.
--

. В Рекомендации МСЭ-T Q.708 (03/99) указано, что административное управлением присвоением зоновых/сетевых кодов сигнализации (SANC) осуществляет БСЭ. Присвоение/отзыв кодов пунктов международной сигнализации (ISPC) будет выполняться каждой страной, которая далее уведомляет БСЭ.

. С запросом на SANC администрации следует обращаться в письменной форме к Директору БСЭ. Для запроса дополнительного SANC администрация должна предоставить Директору БСЭ уведомление о текущем присвоении кодов ISPC, осуществленном этой администрацией.

. Для информации: настоящий Список будет обновляться с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Странам, желающим участвовать в международной сети сигнализации или запросить дополнительный зоновый/сетевой код сигнализации (SANC), следует обращаться к Директору БСЭ с просьбой о присвоении имеющегося кода SANC. В своем запросе администрации могут указать предпочтительный имеющийся код SANC. Любые замечания просим направлять Директору БСЭ:
+
--
[align=left]
International Telecommunication Union +
Direc--r of the TSB +
Place des Nations +
CH-1211 GENEVA 20 +
Switzerland +
Тел.: +41 22 730 5887 +
Факс: +41 22 730 5853 +
Эл. почта: mail--:tsbmail@itu.int[]
--

. Используемые в настоящем Списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны или властей этой страны или географической зоны.


== {blank}

[yaml2text,T-SP-Q.708A-2017.yaml,file]
----
{% assign lang = "ru" %}

[cols="2",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.area_or_network[lang] }} -- нумерационный порядок

{% for network_data in file.data -%}
    | {{ network_data[1].code }} | {{ network_data[1].area_or_network[lang] }}
    {%- assign network_names = network_names | append: network_data[1].area_or_network[lang] | append: ", " -%}
{% endfor %}
|===


{% assign ordered_sequence = network_names | split: ", " | uniq | sort %}

[cols="2",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.area_or_network[lang] }} -- алфавитный порядок

{% for next_network in ordered_sequence -%}
    {%- for network_data in file.data -%}
        {%- if network_data[1].area_or_network[lang] == next_network -%}
            | {{ network_data[1].code }} | {{ network_data[1].area_or_network[lang] }}
        {%- endif -%}
    {%- endfor -%}
{%- endfor %}
|===


Примечания

* {{ file.data["7-213"].note[lang] }}


== Количество свободных зоновых/сетевых кодов (SANC) по Рекомендации МСЭ-T Q.708

[cols="^,^",options="unnumbered,header"]
|===
| Зоновые/сетевые коды сигнализации, диапазон нумерации
| Количество свободных кодов

| 0-000 -- 0-255 | Зарезервирован
| 1-000 -- 1-255 | Зарезервирован
| 2-000 -- 2-255 | 0
| 3-000 -- 3-255 | 86
| 4-000 -- 4-255 | 67
| 5-000 -- 5-255 | 122
| 6-000 -- 6-255 | 97
| 7-000 -- 7-255 | 120
|===

NOTE: Доля присвоенных кодов SANC составляет 67,97 %


== Поправки

[cols="^,^,^",options="unnumbered,header"]
|===
| Поправка № | Оперативный бюллетень № | Страна

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----








