= DIALLING PROCEDURES (INTERNATIONAL PREFIX, NATIONAL (TRUNK) PREFIX AND NATIONAL (SIGNIFICANT) NUMBER) (IN ACCORDANCE WITH ITU-T RECOMMENDATION E.164 (11/2010))
:bureau: T
:docnumber: 976
:published-date: 2011-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== Note from TSB

. This List of “Dialling Procedures” replaces the previous one published as an annex to the ITU
Operational Bulletin No. 951 of 1.III.2010. The present list recapitulates all the different amendments that
have been published up to Operational Bulletin No. 994 of 15.XII.2011.

. The list of *"Dialling Procedures"* contains the national (trunk) prefix, the international prefix, the
country code and the national (significant) number in accordance with ITU-T Recommendation E.164
(11/2010).

. The *national (trunk) prefix* is the digit, or combination of digits, which must be dialled before an area
(city) code when dialling a call to a subscriber from inside his own country but outside his own numbering
area. It provides access to the automatic outgoing trunk equipment. If the entry in this column is blank for a
particular country, it means that the country has a single nationwide numbering plan that does not use area
codes, and all calls to anywhere in the country are dialled by using the entire local number.
Accordingly, in the international service the trunk prefix of the country of destination must not be
dialled. ITU-T recommends that the Administrations of countries which have not yet adopted a trunk prefix or
are revising the prefix for access to their national trunk network should adopt a prefix composed of a single
digit, preferably “0”.

. The *international prefix* is the digit, or combination of digits, that must be dialled before a country
code when dialling a call to a country other than the one from which the call is being placed. If the entry in
this column is blank for a particular country, it means that the country does not have direct dialling facilities to
other countries (in other words, international calls must be placed through the assistance of an operator).
ITU-T recommends that the Administrations of countries that have not yet introduced automatic
international operation or are, for various reasons, revising their numbering plans, should adopt an
international prefix (a code for access to the international automatic network) composed of the two digits
“00”.

. The country code is composed of one digit or is the combination of two or three digits, characterizing
the called country which is used to route calls to the required country. It is usually dialled after the
international prefix. The List of country codes is also published in the "List of ITU-T Recommendation E.164
assigned country codes", as an annex to the Operational Bulletin.

. The *national (significant) number* is the number to be dialled following the national (trunk) prefix to
obtain a subscriber in the same country but in a different local network or numbering area. The national
(significant) number consists of the area code followed by the subscriber number. If the entry in this column
is blank for a particular country, it means that the information is missing.

. For your information, the present List is published as an annex to the ITU Operational Bulletin.
Furthermore, the information it contains is also available on the ITU website link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itut/bulletin/annex.html].

. Every effort has been made to ensure that the information contained in this Annex is accurate.
Administrations are requested to notify all modifications or missing information concerning their national
(trunk) prefix, international prefix and the length of their national (significant) number by using the attached
form.

. The designations employed and the presentation of material in this List do not imply the expression of
any opinion whatsoever on the part of the ITU concerning the legal status of any country or geographical
area, or of its authorities.


[yaml2text,data=../../datasets/994-E.164C/data.yaml,metadata=../../datasets/994-E.164C/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}


== AMENDMENTS

[cols="^,^,^",options="unnumbered,header"]
|===
| Amendment No | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===


== Notification Form

{% assign large_length = 100 %}

[align=center]
*DIALLING PROCEDURES* +
*(According to ITU-T Recommendation E.164)*

Name of Country&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Country code&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

International Prefix&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

National Prefix&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Length of national (significant) number&#58;::
+
--
minimum
{% for i in (1..50) -%}
&#95;
{%- endfor %} +
maximum
{% for i in (1..50) -%}
&#95;
{%- endfor %} +
(excluding the national prefix)
--

Universal Time Coordinated/Summer Time&#58;::
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Remarks&#58;::
+
--
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %} +
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}
--

Contact person&#58;::
+
--
{% for i in (1..large_length) -%}
&#95;
{%- endfor %}

Tel: +
{%- for i in (1..40) -%}
&#95;
{%- endfor %}
Fax: +
{%- for i in (1..40) -%}
&#95;
{%- endfor %} +
Email:
{%- for i in (1..85) -%}
&#95;
{%- endfor %}
--
----