= LISTE DES INDICATIFS DE PAYS OU DE ZONE GÉOGRAPHIQUE POUR LES FACILITÉS NON NORMALISÉES DANS LES SERVICES DE TÉLÉMATIQUE 
:bureau: T
:series: COMPLÉMENT À LA RECOMMANDATION UIT-T T.35 (02/2000)
:language: fr
:docnumber: 1002
:published-date: 2012-04-15
:status: published
:doctype: service-publication
:annextitle-fr: Annexe au Bulletin d'exploitation de l'UIT
:annexid: N° 1002
:keywords: 
:imagesdir: images
:docfile: T-SP-T.35-2012-OAS-MSW-F.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


// _Annexe au Bulletin d'exploitation de l'UIT__N° 1002 – 15.IV.2012_

[preface]
== Note du TSB

[class=steps]
. Le Directeur du Bureau de la normalisation des télécommunications (TSB) est responsable de l'attribution et de la gestion des indicatifs de pays.

. L'indicatif 1111 1111, figurant à la fin de la Liste ci‑après, est un code d'échappement qui sert à indiquer que l'octet suivant contient un indicatif donné dans une Liste complémentaire séparée. Chaque fois que l'indicatif 1111 1111 est utilisé dans le premier octet, l'indicatif de pays ou de zone géographique est celui qui figure dans la Liste complémentaire. Cette liste sera utilisée lorsque tous les indicatifs figurant dans la Liste ci‑dessous auront été attribués.
+
NOTE: Une fois qu'ils ont été émis, les indicatifs peuvent avoir été intégrés dans des équipe­ments terminaux, de sorte qu'ils ne doivent pas être modifiés ou réattribués même si l'appellation du pays ou de la zone géographique__n'est plus valable.

. Les Etats Membres de l'Union internationale des télécommunications (UIT) qui ne sont pas mentionnés dans cette Liste mais qui souhaitent obtenir un indicatif de pays ou de zone géographique sont invités à demander au Directeur du TSB que leur soit attribué un indicatif de pays disponible. Dans cette demande, ils peuvent indiquer un indicatif précis s'il est disponible. Veuillez adresser vos commentaires au Directeur du TSB:
+
Union internationale des télécommunications (UIT) 
+
Directeur du TSB 
+
Place des Nations 
+
CH-1211 GENÈVE 20 
+
Suisse 
+
Tél: +41 22 730 6805 
+
Fax: +41 22 730 5853 
+
E-mail: tsbmail@itu.int

. A titre d'information, cette Liste est également disponible sur le site web de l'UIT.
+
http://www.itu.int/itu-t/bulletin/annex.html[http://www.itu.int/itu-t/bulletin/annex.html]

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.


== {blank}

[yaml2text,T-SP-T.35-2012-OAS.yaml,file]
----
{% assign lang = "fr" %}

[%unnumbered,cols="10*"]
|===
9+^.^h| _{{ file.metadata.code_bit[lang] | remove: " Bit (b8 to b1)" }}_ +
Bit
^.^h| _{{ file.metadata.country_or_area[lang] }}_
 
h| b~8~ h| b~7~ h| b~6~ h| b~5~ | h| b~4~ h| b~3~ h| b~2~ h| b~1~ |  

{% for country_code in file.data.code_bit %}

| {{ country_code[1].code_bit | slice: 0 }}
| {{ country_code[1].code_bit | slice: 1 }}
| {{ country_code[1].code_bit | slice: 2 }}
| {{ country_code[1].code_bit | slice: 3 }}
|
| {{ country_code[1].code_bit | slice: 4 }}
| {{ country_code[1].code_bit | slice: 5 }}
| {{ country_code[1].code_bit | slice: 6 }}
| {{ country_code[1].code_bit | slice: 7 }}
| {{ country_code[1].country_or_area[lang] | replace: "NOTE 1","<<note1>>"}}

{% endfor %}

|===

[[note1]]
NOTE: {{ file.data.code_bit["11111111"].notes[lang] }}
----
