= LISTA DE INDICADORES DE DESTINO DE TELEGRAMAS
:bureau: T
:docnumber: F.32
:series: Según la Recomendación UIT-T F.32 (10/1995)
:published-date: 2011-05-15
:status: in-force
:doctype: service-publication
:annex-id: No. 980
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. Por Circular TSB 179 del 16 de octubre de 1995, la TSB ha anunciado la aprobación de la
Recomendación UIT-T F.32 (10/1995) (anteriormente F.96), de conformidad con la Resolución 1,
Sección 8 de la CMNT (Helsinki, 1993) y, por Circular TSB 104 del 23 de marzo de 1998, la TSB
ha anunciado la aprobación de la Recomendación UIT-T F.1 (03/1998): «Disposiciones aplicables
a la explotación del servicio público internacional de telegramas», cuyo texto ha sido revisado por
la Comisión de Estudio 2 del UIT-T.
+
--
Por consiguiente, la TSB ha preparado una Lista de indicadores de destino de telegramas
que recoge los indicadores asignados a países/zonas geográficas o redes (dos primeras letras) y
a oficinas telegráficas (tercera y cuarta letras), de conformidad con la Recomendación UIT-T F.32
(10/1995). La Lista contiene también los indicadores especiales de origen y los indicadores
utilizados para designar organizaciones internacionales en la línea de preámbulo de los
telegramas de Estado conformes a la disposición A218 de la Recomendación UIT-T F.1 (03/1998).
--

. La nueva lista publicada en Anexo al Boletín de Explotación de la UIT N.o 980 del
15 de mayo de 2011 sustituye a la publicada en Anexo al Boletín de Explotación de la UIT N.o 879
del 1 de marzo de 2007. Se han añadido a esta lista los países o zonas geográficas para los
cuales una información sobre a la cesación de servicio de telegramas ha sido publicada en el
Boletín de Explotación de la UIT (N.°).
+
--
Asimismo, se recuerda a las administraciones/EER que la
_Lista de códigos de identificación de red télex (CIRD)_
mencionada en el párrafo 7.3 de la Recomendación UIT-T F.32 (10/1995) se
publica ahora por separado, como anexo al Boletín de Explotación de la UIT y que la misma se
actualiza regularmente por medio de enmiendas.

Uno de los principales objetivos de la Recomendación UIT-T F.32 (10/1995) es incitar a las
Administraciones/EER a reducir el número de indicadores de destino atribuidos a sus redes de
telegramas. Durante los últimos años, un gran número de administraciones/EER ha adoptado un
solo indicador de destino (--XX) para todos los destinos o bien sólo ha asignado a sus redes de
telegramas un pequeño número de indicadores de destino. La TSB señala especialmente a la
atención de las administraciones/EER que según el Sección 6 de la Recomendación
UIT-T F.32 (10/1995), que estipula que «Los códigos de oficina (es decir, la tercera y cuarta letras
de un indicador de destino) asignados para cada código de red se deben mantener en un número
mínimo en cada red» y «cuando la red de destino es capaz de realizar el encaminamiento
nacional sin un código de oficina (por ejemplo, analizando la parte de dirección del telegrama así
como la línea piloto), se prefiere un solo código de oficina (XX)».
--

. Con el fin de mantener actualizada la lista, se ruega a las administraciones/EER que
comprueben la exactitud de la información publicada en la misma y que informen tan pronto como
sea posible a la TSB de cualquier cambio que deba realizarse (Fax: *+41 22 730 5853*, o
E-mail: *mailto:tsbtson@itu.int[]*). Los cambios se publicarán como enmiendas a la lista en el siguiente
Boletín de Explotación de la UIT.

. Asimismo, la información que contiene este Anexo al Boletín de Explotación de la
UIT N.° 980 está disponible en el sitio web de la UIT www.itu.int/itu-t/bulletin/annex.html .

. Las denominaciones empleadas en esta lista y la forma en que aparecen presentados los
datos que contiene no implican, por parte de la UIT, juicio alguno sobre la condición jurídica de los
países o zonas geográficas, o de sus autoridades.


[yaml2text,T-SP-F.32-2011.yaml,file]
----
{% assign lang = "es" %}

== {{ file.metadata.title[lang] }}

{% assign note_present = false %}
{% assign first_pass = true %}

{% for country_data in file.data -%}

  {%- assign country_batch = file.data | map: "country_or_area" | where: "en", country_data.country_or_area.en %}
  {%- assign network_roa_batch = file.data | where: "network_roa", country_data.network_roa %}

  {%- assign next_country = country_data.country_or_area[lang] %}
  {%- assign next_network_roa = country_data.network_roa %}
  {%- assign next_network_code = country_data.network_code %}
  {%- assign next_subarea = country_data.subarea[lang] %}


{% if next_country != current_country and note_present == true or first_pass == true -%}

{% unless first_pass == true %}
|===
{% endunless %}

[cols="5",options="unnumbered"]
|===

^h| {{ file.metadata.locale.country_or_area[lang] }}
^h| {{ file.metadata.locale.network_roa[lang] }}
^h| {{ file.metadata.locale.network_code[lang] }}
^h| {{ file.metadata.locale.telegraph_office_name[lang] }}
^h| {{ file.metadata.locale.office_code[lang] }}

^| 1 ^| 2 ^| 3 ^| 4 ^| 5

{% assign note_present = false %}
{% assign first_pass = false %}
{%- endif %}

{% if next_country != current_country %}

{% unless country_data.country_or_area.en == "INDIA" or country_data.country_or_area.en == "AUSTRALIA" or country_data.country_or_area.en == "CHILE" or country_data.country_or_area.en == "UNITED STATES" -%}
.{{ country_batch.size }}+
{%- endunless -%}
a| *{{ country_data.country_or_area.fr }}*
{% if country_data.country_or_area_note -%}
footnote:[{{ country_data.country_or_area_note[lang] }}]
{%- endif %} +
  *{{ country_data.country_or_area.en }}*
{% if country_data.country_or_area_note -%}
footnote:[{{ country_data.country_or_area_note[lang] }}]
{%- endif %} +
  *{{ country_data.country_or_area.es }}*
{% if country_data.country_or_area_note -%}
footnote:[{{ country_data.country_or_area_note[lang] }}]
{%- endif %}

{% if country_data.country_or_area.en == "SAUDI ARABIA" %}
  {%- assign saudi_batch = file.data | where: "network_code", "SJ - -" %}
  {%- for saudi_data in saudi_batch -%}
    {% if saudi_data.telegraph_office_name and saudi_data.notes %}
    . {{ saudi_data.telegraph_office_name[lang] }} footnote:[{{ saudi_data.notes[lang] }}]
    {% endif %}
  {%- endfor %}
{% endif %}

{% if country_data.country_or_area.en == "UNITED ARAB EMIRATES" -%}
  {{ country_data.subarea[lang] }}
{%- endif %}

{% if country_data.country_or_area.en == "UNITED STATES" -%}
  {{ country_data.subarea[lang] }}
{%- endif %}


{% assign current_country = next_country %}

{% elsif country_data.subarea -%}
  {% if next_subarea != current_subarea %}
    {% assign current_subarea = next_subarea %}
    {% if country_data.country_or_area.en == "AUSTRALIA" -%}
      a| {{ country_data.subarea.fr }} +
         {{ country_data.subarea.en }} +
         {{ country_data.subarea.es }}

    {% elsif country_data.country_or_area.en == "CHILE" or country_data.country_or_area.en == "UNITED STATES" and country_data.subarea.en contains "Network I"  %}
      | {{ country_data.subarea.fr | remove: "I" }} / {{ country_data.subarea.en | remove: "I" }} / {{ country_data.subarea.es }}
    {% elsif country_data.country_or_area.en != "UNITED ARAB EMIRATES" %}
      | {{ country_data.subarea[lang] }}
    {%- endif %}
  {% else %}
    {% if country_data.country_or_area.en != "UNITED ARAB EMIRATES" %}
      |
    {% endif %}
  {% endif %}

{% elsif country_data.country_or_area.en == "CHILE" or country_data.country_or_area.en == "UNITED STATES" %}
  |
{% endif %}

{% if next_network_roa != current_network_roa %}
  | {{ country_data.network_roa }}
  {%- if country_data.network_roa_note -%}
    footnote:[{{ country_data.network_roa_note[lang] }}]
  {%- endif %}
  {% assign current_network_roa = next_network_roa %}
{% else %}
  |
{% endif %}

{% if next_network_code != current_network_code %}
  | {{ country_data.network_code }}
  {%- if country_data.network_code_note -%}
    footnote:[{{ country_data.network_code_note[lang] }}]
  {%- endif %}
  {% assign current_network_code = next_network_code %}
{% else %}
  |
{% endif %}

| {{ country_data.telegraph_office_name[lang] }}
{%- if country_data.country_or_area.en == "BARBADOS" and country_data.notes -%}
  footnote:[{{ country_data.notes[lang] }}]
{%- endif -%}

| {{ country_data.office_code }}
{%- if country_data.office_code_note -%}
  footnote:[{{ country_data.office_code_note[lang] }}]
{%- endif -%}

{% if country_data.network_roa_note or country_data.network_code_note or country_data.notes or country_data.office_code_note or country_data.country_or_area_note %}
{% assign note_present = true %}
{% endif %}

{% endfor %}

|===
----
