= ДОПОЛНЕНИЕ К РЕКОМЕНДАЦИИ МСЭ-Т E.218 (05/2004)
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1125
:keywords: 
:imagesdir: images
:docfile: T-SP-E.218-2017-R.adoc
:language: ru
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Примечание БСЭ

. Настоящий Список – это Список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* согласно Рекомендации МСЭ-Т E.218.

. Настоящий Список включает:
+
--
* список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* − в нумерационном порядке;
* список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* − в алфавитном порядке.
--

. Настоящий Список будет обновляться с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Любые замечания, касающиеся данной публикации, просим направлять Директору БСЭ:
+
--
[align=left]
Тел.: +41 22 730 5887 +
Факс: +41 22 730 5853 +
Эл. почта: mailto:tsbmail@itu.int[]
--

. Используемые в настоящем Списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны либо их властей.


[yaml2text,T-SP-E.218-2017.yaml,file]
----
{% assign lang = "ru" %}


== {{ file.metadata.title[lang] }} - нумерационный порядок

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign note_first_word = note_content.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            {% assign note_a = note_content[lang] %}
        {% when "United" %}
            {% assign note_b = note_content[lang] %}
        {% when "This" %}
            {% assign note_c = note_content[lang] %}
    {% endcase %}
{% endfor %}


[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data -%}
    | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} | 
    {% assign note_first_word = country_data.note.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            <<note_a,a>>
        {% when "United" %}
            <<note_b,b>>
        {% when "This" %}
            <<note_c,c>>
    {% endcase %}
{%- endfor %}
|===


== {{ file.metadata.title[lang] }} - алфавитный порядок

{% assign ordered_sequence = file.data | map: "country_or_area" | sort: lang | uniq %}

[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for next_country in ordered_sequence -%}
    {%- for country_data in file.data -%}
        {%- if country_data.country_or_area[lang] == next_country[lang] -%}
            | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} | 
            {% assign note_first_word = country_data.note.en | split: " " | first %}
            {% case note_first_word %}
                {% when "Mobile" %}
                    <<note_a,a>>
                {% when "United" %}
                    <<note_b,b>>
                {% when "This" %}
                    <<note_c,c>>
            {% endcase %}
        {%- endif -%}
    {%- endfor %}
{%- endfor %}
|===


{{ file.metadata.locale.note[lang] | append: "s"}}:

. [[note_a]]{{ note_a }}
. [[note_b]]{{ note_b }}
. [[note_c]]{{ note_c }}


== ПОПРАВКИ

[cols="^,^,^",options="unnumbered"]
|===
| Поправка № | Оперативный бюллетень № | Страна

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----