= LISTE DES INDICATIFS DE PAYS POUR LE SERVICE MOBILE DE RADIOCOMMUNICATION DE TERRE À RESSOURCES PARTAGÉES
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1125
:keywords: 
:imagesdir: images
:docfile: T-SP-E.218-2017-E.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Note du TSB

. C’est la Liste des indicatifs de pays pour le service mobile de radiocommunication de Terre à ressources partagées selon la Recommandation UIT-T E.218.

. La présente Liste comprend:
+
--
* une Liste des indicatifs de pays pour le service mobile de radiocommunication de Terre à ressources partagées - par ordre numérique;
* une Liste des indicatifs de pays pour le service mobile de radiocommunication de Terre à ressources partagées - par ordre alphabétique.
--

. La mise à jour de cette liste se fera par des séries d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles sur le site web de l’UIT (à l'adresse link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Veuillez adresser vos commentaires concernant cette publication au Directeur du TSB:
+
--
[align=left]
Tél: +41 22 730 5857
Fax: +41 22 730 5853
Email: mailto:tsbmail@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.


[yaml2text,T-SP-E.218-2017.yaml,file]
----
{% assign lang = "fr" %}


== {{ file.metadata.title[lang] }} - numerical order

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign note_first_word = note_content.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            {% assign note_a = note_content[lang] %}
        {% when "United" %}
            {% assign note_b = note_content[lang] %}
        {% when "This" %}
            {% assign note_c = note_content[lang] %}
    {% endcase %}
{% endfor %}


[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data -%}
    | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} | 
    {% assign note_first_word = country_data.note.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            <<note_a,a>>
        {% when "United" %}
            <<note_b,b>>
        {% when "This" %}
            <<note_c,c>>
    {% endcase %}
{%- endfor %}
|===


== {{ file.metadata.title[lang] }} - alphabetical order

{% assign ordered_sequence = file.data | map: "country_or_area" | sort: lang | uniq %}

[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for next_country in ordered_sequence -%}
    {%- for country_data in file.data -%}
        {%- if country_data.country_or_area[lang] == next_country[lang] -%}
            | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} | 
            {% assign note_first_word = country_data.note.en | split: " " | first %}
            {% case note_first_word %}
                {% when "Mobile" %}
                    <<note_a,a>>
                {% when "United" %}
                    <<note_b,b>>
                {% when "This" %}
                    <<note_c,c>>
            {% endcase %}
        {%- endif -%}
    {%- endfor %}
{%- endfor %}
|===


{{ file.metadata.locale.note[lang] | append: "s"}}:

. [[note_a]]{{ note_a }}
. [[note_b]]{{ note_b }}
. [[note_c]]{{ note_c }}


== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendement N° | Bulletin d'exploitation N°. | Pays

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----
