= قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأ رض للاتصال البعيد
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== ملاحظة من مكتب تقييس الاتصالات

. ITU-T E. فيما يلي قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد وفقاً للتوصية 218
. تتضمن القائمة ما يلي:
+
--
* قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد - بالترتيب العددي؛
* قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد - بالترتيب الأبجدي.
--

. ستُحَدَّث هذه القائمة بواسطة مجموعة مرقّمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. وإضافة إلى ذلك، فإن المعلومات
. link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html] : الواردة في هذا الملحق متاحة أيضاً في الموقع الإلكتروني للاتحاد في العنوان التالي

. يُرجى إرسال أي تعليقات متعلقة بهذا المنشور إلى مدير مكتب تقييس الاتصالات:
+
--
+41 22 730 الهاتف: 5887 +
+41 22 730 الفاكس: 5853 +
mailto:tsbmail@itu.int[] : البريد الإلكتروني
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تعبّر عن أي رأي من جانب الاتحاد فيما يتعلق بالوضع القانوني
لأي بلد أو منطقة جغرافية أو لسلطات أيّ منهما.


[yaml2text,T-SP-E.218-2017.yaml,file]
----
{% assign lang = "ar" %}


== {{ file.metadata.title[lang] }} - بالترتيب العددي

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign note_first_word = note_content.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            {% assign note_a = note_content[lang] %}
        {% when "United" %}
            {% assign note_b = note_content[lang] %}
        {% when "This" %}
            {% assign note_c = note_content[lang] %}
    {% endcase %}
{% endfor %}


[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data -%}
    | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} |
    {% assign note_first_word = country_data.note.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            <<note_a,a>>
        {% when "United" %}
            <<note_b,b>>
        {% when "This" %}
            <<note_c,c>>
    {% endcase %}
{%- endfor %}
|===


== {{ file.metadata.title[lang] }} - بالترتيب الأبجدي

{% assign ordered_sequence = file.data | map: "country_or_area" | sort: lang | uniq %}

[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.tmcc_code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for next_country in ordered_sequence -%}
    {%- for country_data in file.data -%}
        {%- if country_data.country_or_area[lang] == next_country[lang] -%}
            | {{ country_data.tmcc_code }} | {{ country_data.country_or_area[lang] }} |
            {% assign note_first_word = country_data.note.en | split: " " | first %}
            {% case note_first_word %}
                {% when "Mobile" %}
                    <<note_a,a>>
                {% when "United" %}
                    <<note_b,b>>
                {% when "This" %}
                    <<note_c,c>>
            {% endcase %}
        {%- endif -%}
    {%- endfor %}
{%- endfor %}
|===


{{ file.metadata.locale.note[lang] | append: "s"}}:

. [[note_a]]{{ note_a }}
. [[note_b]]{{ note_b }}
. [[note_c]]{{ note_c }}


== التعديلات

[cols="^,^,^",options="unnumbered"]
|===
| البلد
| رقم النشرة التشغيلية
| رقم التعديل

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----


