= ДОПОЛНЕНИЕ К РЕКОМЕНДАЦИИ МСЭ-Т E.218 (05/2004)
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125
:imagesdir: images
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Примечание БСЭ

. Настоящий Список – это Список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* согласно Рекомендации МСЭ-Т E.218.

. Настоящий Список включает:
+
--
* список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* − в нумерационном порядке;
* список кодов страны для подвижной связи в системе *наземной транкинговой радиосвязи* − в алфавитном порядке.
--

. Настоящий Список будет обновляться с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Любые замечания, касающиеся данной публикации, просим направлять Директору БСЭ:
+
--
[align=left]
Тел.: +41 22 730 5887 +
Факс: +41 22 730 5853 +
Эл. почта: mailto:tsbmail@itu.int[]
--

. Используемые в настоящем Списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны либо их властей.


[yaml2text,data=../../datasets/1125-E.218/data.yaml,metadata=../../datasets/1125-E.218/metadata.yaml]
----
{% assign lang = "ru" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== ПОПРАВКИ

[cols="^,^,^",options="unnumbered"]
|===
| Поправка № | Оперативный бюллетень № | Страна

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----