= LIST OF TERRESTRIAL TRUNK RADIO MOBILE COUNTRY CODES
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note from TSB

. This is the List of terrestrial trunk radio mobile country codes according to Recommendation ITU-T E.218.

. This List includes:
+
--
* a list of terrestrial trunk radio mobile country codes - in numerical order;
* a list of terrestrial trunk radio mobile country codes - in alphabetical order.
--

. This List will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU website link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Please address any comments concerning this publication to the Director of TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
Email: mailto:tsbmail@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.


[yaml2text,data=../../datasets/1125-E.218/data.yaml,metadata=../../datasets/1125-E.218/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendment No. | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----