= قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأ رض للاتصال البعيد
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== ملاحظة من مكتب تقييس الاتصالات

. ITU-T E. فيما يلي قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد وفقاً للتوصية 218
. تتضمن القائمة ما يلي:
+
--
* قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد - بالترتيب العددي؛
* قائمة بالرموز الدليلية للبلدان للاتصالات الراديوية المتنقلة للأرض للاتصال البعيد - بالترتيب الأبجدي.
--

. ستُحَدَّث هذه القائمة بواسطة مجموعة مرقّمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. وإضافة إلى ذلك، فإن المعلومات
. link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html] : الواردة في هذا الملحق متاحة أيضاً في الموقع الإلكتروني للاتحاد في العنوان التالي

. يُرجى إرسال أي تعليقات متعلقة بهذا المنشور إلى مدير مكتب تقييس الاتصالات:
+
--
+41 22 730 الهاتف: 5887 +
+41 22 730 الفاكس: 5853 +
mailto:tsbmail@itu.int[] : البريد الإلكتروني
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تعبّر عن أي رأي من جانب الاتحاد فيما يتعلق بالوضع القانوني
لأي بلد أو منطقة جغرافية أو لسلطات أيّ منهما.


[yaml2text,data=../../datasets/1125-E.218/data.yaml,metadata=../../datasets/1125-E.218/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== التعديلات

[cols="^,^,^",options="unnumbered"]
|===
| البلد
| رقم النشرة التشغيلية
| رقم التعديل

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----


