= LISTA DE INDICATIVOS DE PAÍS PARA EL SERVICIO MÓVIL DE RADIOCOMUNICACIÓN CON CONCENTRACIÓN DE ENLACES TERRENALES
:bureau: T
:docnumber: E.218
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. Esta es la Lista de indicativos de país para el servicio móvil de radiocomunicación con concentración de enlaces terrenales

. La presente Lista comprende:
+
--
* una lista de indicativos de país para el servicio móvil de radiocomunicación con concentración de enlaces terrenales - en orden numérico;
* una lista de indicativos de país para el servicio móvil de radiocomunicación con concentración de enlaces terrenales - en orden alfabético.
--

. La Lista se actualizará por series de enmiendas numeradas que se publicarán en el Boletín de Explotación de la UIT. Por otra parte, la información contenida en este Anexo está disponible en el sitio web de la UIT (link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Sírvase comunicar sus comentarios con respecto a esta publicación al Director de la TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.


[yaml2text,data=../../datasets/1125-E.218/data.yaml,metadata=../../datasets/1125-E.218/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== ENMIENDAS

[cols="^,^,^",options="unnumbered"]
|===
| Enmienda N.° | Boletín de Explotación N.° | País

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----
