= Indicativos de red para el servicio móvil (MNC) del plan de identificación internacional para redes públicas y suscripciones (Según la Recomendación UIT-T E.212 (09/2016))
:bureau: T
:docnumber: 976
:published-date: 2018-12-15
:annex-title: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:keywords: 
:imagesdir: images
:docfile: T-SP-E.212B-2018-S.adoc
:language: es
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


[preface]
== Nota de la TSB

. Una Lista centralizada de los indicativos de red para el servicio móvil (MNC) del plan de identificación internacional para redes públicas y suscripciones fue creada, de la que la TSB es la depositaria.

. Esta Lista de los indicativos de red para el servicio móvil (MNC) será publicada en el Anexo al Boletín de Explotación de la UIT N.° 1162 de 15.XII.2018. Se solicita a las Administraciones que notifiquen a la UIT todas las modificaciones relacionadas sus informaciones en esta Lista.
El formulario de notificación se encuentra en el sitio web de la UIT, en la dirección: http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx.

. La Lista se actualizará por medio de enmiendas que se publicarán en el link:http://www.itu.int/pub/T-SP/es[Boletín de Explotación de la UIT]. Por otra parte, la información contenida en este Anexo está disponible en el link:https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[sitio web de la UIT].

. Sírvase comunicar sus comentarios o sugerencias con respecto a esta Lista al Director de la TSB:
Unión Internacional de Telecomunicaciones
+
--
[align=left]
Director de la TSB +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, por parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.



[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
{% assign lang = "es" %}

== {{ file.metadata.title[lang] }}

[cols="25%,55%,20%",options="header,unnumbered"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.networks[lang] }}
^| {{ file.metadata.locale.mcc_mnc_codes[lang] }}

{% assign country_names = file.data | map: "country_or_area" %}

{% for country_data in file.data %}
    {% assign next_country = country_data.country_or_area.en %}

    {% if current_country != next_country %}
        {% assign current_country = next_country %}
        {% assign country_batch = country_names | where: "en", country_data.country_or_area.en %}
        .{{ country_batch.size | plus: 1 }}+| {{ country_data.country_or_area[lang] }} | |
    {% endif %}
    | {{ country_data.networks | replace: "|", "\|"}}
    ^| {{ country_data.mcc_mnc_codes }}

{% endfor %}
|===

[yaml2text,T-SP-E.212B-2018.shared_mcc.yaml,file_two]
---

== {{ file_two.metadata.locale.shared_mcc[lang] }}

[cols="2",options="unnumbered,header"]
|===
^| {{ file_two.metadata.locale.networks[lang] }} 
^| {{ file_two.metadata.locale.mcc_mnc_codes[lang] }}

{% for network_data in file_two.data %}
     | {{ network_data[1].networks }} 
    ^| {{ network_data[0] }}
{% endfor %}
|===
---


[yaml2text,T-SP-E.212B-2018.shared_mcc_others.yaml,file_three]
---

== {{ file_three.metadata.locale.shared_mcc_others[lang] }}

[cols="<,<,^",options="unnumbered,header"]
|===
| | {{ file_three.metadata.locale.applicant[lang] }} | MCC + MNC codes

{% for code_data in file_three.data %}
    .2+| *{{ code_data[1].purpose[lang] }}* | |
       | {{ code_data[1].applicant }} +
    {% if code_data[1].temporary_assignment_to -%}
        (temporary assignment for trial until {{ code_data[1].temporary_assignment_to }})
    {%- endif %}
      ^| {{ code_data[0] }}
{% endfor %}
|===
---

[yaml2text,T-SP-E.212B-2018.et.yaml,file_four]
---

== {{ file_four.metadata.title[lang] | remove: "*" }} footnote:[{{ file_four.metadata.note_1[lang] }}]


[cols="4",options="unnumbered,header"]
|===
| {{ file_four.metadata.locale.country_or_area[lang] }}
| {{ file_four.metadata.locale.mcc_mnc[lang] }} footnote:[{{ file_four.metadata.note_2[lang] }}]
| {{ file_four.metadata.locale.msin_range[lang] }} footnote:[{{ file_four.metadata.note_3[lang] }}]
| {{ file_four.metadata.locale.operator_network[lang] }}


{% for i in file_four.data %}
    {% assign next_parameters = "" | append: i.country_or_area.en | append: ", " 
                                   | append: i.country_type | append: ", " 
                                   | append: i.mcc_mnc | append: ", "
                                   | append: i.operator_network %}

    {% if next_parameters != current_parameters %}
        {% assign current_parameters = next_parameters %}

        {% for j in file_four.data %}
            {% assign j_parameters = "" | append: j.country_or_area.en | append: ", " 
                                        | append: j.country_type | append: ", "
                                        | append: j.mcc_mnc | append: ", "
                                        | append: j.operator_network %}

            {% if j_parameters == current_parameters %}
                {% assign msin_parameters = msin_parameters | append: j.msin_range | append: ", " %}
            {% endif %}
        {% endfor %}

        {% assign msin_batch        = msin_parameters   | split: ", " %}
        {% assign last_msin_item    = msin_batch        | last %}
        {% assign msin_parameters   = nil %}

        | {{ i.country_or_area[lang] }} - País {{ i.country_type }}
        | {{ i.mcc_mnc }}
        |
        {% if i.country_or_area.en != "Switzerland" %}
            {% for item in msin_batch %}
                {% if item != last_msin_item %}
                    {{ item }}; +
                {% else %}
                    {{ item }}
                {% endif %}
            {% endfor %}
        {% else %}
            {{ msin_batch | join: ", " }}
        {% endif %}
        .^| {{ i.operator_network }}

    {% endif %}
{% endfor %}
|===
---

----


== {blank}

[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
Remítase a UIT/TSB Fax N.o +41 22 730 5853 / E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Formulario de notificación para la asignación/retirada de indicativos de red para el servicio móvil (MNC) del plan de indentificación internacional para redes públicas y suscripciones* +
(Según la Recomendación UIT-T E.212)

_Este formulario debe utilizarse para notificar al Director de la TSB los MNC que han sido asignados o retirados por un Estado Miembro desde la última notificación._

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

País/Zona&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Organización del Estado Miembro&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Persona encargada del Estado Miembro&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Nombre&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Dirección&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Tel&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Fax&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Correo-e&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}


[cols="^,^",options="unnumbered"]
|===
| MCC + MNC | Nombre de la red/ operador

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC: Indicativo de país para el servicio móvil +
MNC: Indicativo de red para el servicio móvil
----


== {blank}

[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
Remítase al número de Fax UIT/TSB No.: +41 22 730 5853/E-mail: mailto:tsbtson@itu.int[]

[align=center]
*Formulario de notificación de utilización extraterritorial/cancelación de utilización extraterritorial de un MCC/MNC* +
(Según la Recomendación UIT-T E.212, Annexo E)

Las Administraciones emplearán este formulario para notificar al Director de la TSB que dan su acuerdo al operador para utilizar/cancelar la utilización de un MCC+MNC de País A en el País B.


{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Nombre de la persona de contacto en la Administración&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Dirección&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Tel&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Fax&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Correo-e&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| Nombre del/de los operador(es)
h| País B – Donde se utiliza extraterritorialmente el MCC/MNC
h| Gama de MSIN que se utilizará en el País A
h| Gama de MSIN que se utilizará en el País B

| | | | |
| | | | |
|===


== ENMIENDAS

[cols="^,^,^",options="header,unnumbered"]
|===
| Enmienda N.°
| Boletín de Explotación N.°
| País o zona

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----


