= Codes de réseau mobile (MNC) pour le plan d'identification international pour les réseaux publics et les abonnements (Selon la Recommandation UIT-T E.212 (09/2016))
:bureau: T
:docnumber: 976
:published-date: 2018-12-15
:annex-title: Annex to ITU Operational Bulletin
:annex-id: No. 1162
:status: published
:doctype: service-publication
:keywords: 
:imagesdir: images
:docfile: T-SP-E.212B-2018-F.adoc
:language: fr
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:


[preface]
== Note du TSB

. Une Liste centralisée des codes de réseau mobile (MNC) pour le plan d'identification international pour les réseaux publics et les abonnements a été dressée, le TSB en étant le dépositaire.

. Cette Liste des codes de réseau mobile (MNC) est publiée en annexe au Bulletin d’exploitation de l’UIT N° 1162 du 15.XII.2018. Les Administrations sont priées de vérifier leurs informations dans cette Liste et d’informer l’UIT des modifications qu’elles veulent apporter.
Le formulaire de notification se trouve sur le site web de l’UIT, à l'adresse web : http://www.itu.int/en/ITU-T/inr/forms/Pages/mnc.aspx .

. La mise à jour de cette Liste se fera sous la forme d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles depuis le site web de l’UIT.

. Veuillez adresser vos commentaires ou suggestions concernant cette Liste au Directeur du TSB:
Union internationale des télécommunications (UIT)
+
--
[align=left]
Directeur du TSB +
Tél: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail : mailto:tsbtson@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques ou de leurs autorités.


[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
{% assign lang = "fr" %}

== {{ file.metadata.title[lang] }}

[cols="25%,55%,20%",options="header,unnumbered"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.networks[lang] }}
^| {{ file.metadata.locale.mcc_mnc_codes[lang] }}

{% assign country_names = file.data | map: "country_or_area" %}

{% for country_data in file.data %}
    {% assign next_country = country_data.country_or_area.en %}

    {% if current_country != next_country %}
        {% assign current_country = next_country %}
        {% assign country_batch = country_names | where: "en", country_data.country_or_area.en %}
        .{{ country_batch.size | plus: 1 }}+| {{ country_data.country_or_area[lang] }} | |
    {% endif %}
    | {{ country_data.networks | replace: "|", "\|"}}
    ^| {{ country_data.mcc_mnc_codes }}

{% endfor %}
|===

[yaml2text,T-SP-E.212B-2018.shared_mcc.yaml,file_two]
---

== {{ file_two.metadata.locale.shared_mcc[lang] }}

[cols="2",options="unnumbered,header"]
|===
^| {{ file_two.metadata.locale.networks[lang] }} 
^| {{ file_two.metadata.locale.mcc_mnc_codes[lang] }}

{% for network_data in file_two.data %}
     | {{ network_data[1].networks }} 
    ^| {{ network_data[0] }}
{% endfor %}
|===
---


[yaml2text,T-SP-E.212B-2018.shared_mcc_others.yaml,file_three]
---

== {{ file_three.metadata.locale.shared_mcc_others[lang] }}

[cols="<,<,^",options="unnumbered,header"]
|===
| | {{ file_three.metadata.locale.applicant[lang] }} | MCC + MNC codes

{% for code_data in file_three.data %}
    .2+| *{{ code_data[1].purpose[lang] }}* | |
       | {{ code_data[1].applicant }} +
    {% if code_data[1].temporary_assignment_to -%}
        (temporary assignment for trial until {{ code_data[1].temporary_assignment_to }})
    {%- endif %}
      ^| {{ code_data[0] }}
{% endfor %}
|===
---

[yaml2text,T-SP-E.212B-2018.et.yaml,file_four]
---

== {{ file_four.metadata.title[lang] | remove: "*" }} footnote:[{{ file_four.metadata.note_1[lang] }}]


[cols="4",options="unnumbered,header"]
|===
| {{ file_four.metadata.locale.country_or_area[lang] }}
| {{ file_four.metadata.locale.mcc_mnc[lang] }} footnote:[{{ file_four.metadata.note_2[lang] }}]
| {{ file_four.metadata.locale.msin_range[lang] }} footnote:[{{ file_four.metadata.note_3[lang] }}]
| {{ file_four.metadata.locale.operator_network[lang] }}


{% for i in file_four.data %}
    {% assign next_parameters = "" | append: i.country_or_area.en | append: ", " 
                                   | append: i.country_type | append: ", " 
                                   | append: i.mcc_mnc | append: ", "
                                   | append: i.operator_network %}

    {% if next_parameters != current_parameters %}
        {% assign current_parameters = next_parameters %}

        {% for j in file_four.data %}
            {% assign j_parameters = "" | append: j.country_or_area.en | append: ", " 
                                        | append: j.country_type | append: ", "
                                        | append: j.mcc_mnc | append: ", "
                                        | append: j.operator_network %}

            {% if j_parameters == current_parameters %}
                {% assign msin_parameters = msin_parameters | append: j.msin_range | append: ", " %}
            {% endif %}
        {% endfor %}

        {% assign msin_batch        = msin_parameters   | split: ", " %}
        {% assign last_msin_item    = msin_batch        | last %}
        {% assign msin_parameters   = nil %}

        | {{ i.country_or_area[lang] }} - Pays {{ i.country_type }}
        | {{ i.mcc_mnc }}
        |
        {% if i.country_or_area.en != "Switzerland" %}
            {% for item in msin_batch %}
                {% if item != last_msin_item %}
                    {{ item }}; +
                {% else %}
                    {{ item }}
                {% endif %}
            {% endfor %}
        {% else %}
            {{ msin_batch | join: ", " }}
        {% endif %}
        .^| {{ i.operator_network }}

    {% endif %}
{% endfor %}
|===
---

----


== {blank}

[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
A retourner à UIT/TSB Fax No +41 22 730 5853 / E-mail : mailto:tsbtson@itu.int[]

[align=center]
*Formulaire de notification pour l’attribution ou le retrait des Code de réseau mobile (MNC) pour le plan d'identification international pour les réseaux publics et les abonnements* +
(Selon la Recommandation UIT-T E.212)

_Le présent formulaire doit être utilisé pour notifier au Directeur du TSB les codes MNC qui ont été attribués ou retirés par un Etat Membre depuis la dernière notification._

{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

Pays/Zone&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Organisation de l’Etat Membre&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Personne représentant l’Etat Membre&#58;::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

Nom&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Adresse&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Tél.&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

Fax&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

E-mail&#58;:::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}


[cols="^,^",options="unnumbered"]
|===
| MCC + MNC | Nom du réseau/opérateur

{% for i in (1..28) %}
| |
{% endfor %}
|===

MCC: Indicatif de pays du mobile +
MNC: Code de réseau mobile
----


== {blank}

[yaml2text,T-SP-E.212B-2018.main.yaml,file]
----
A retourner à UIT/TSB Fax No +41 22 730 5853 / E-mail : mailto:tsbtson@itu.int[]

[align=center]
*Notification de l’utilisation ou de l'annulation de l'utilisation extraterritoriale de ressources MCC/MNC* +
(Selon la Recommandation UIT-T E.212, Annexe E)

Chacune des Administrations devrait utiliser ce formulaire pour indiquer au Directeur du TSB qu'elle a donné son accord pour qu'un opérateur puisse utiliser/annuler l'utilisation des ressources MCC+MNC du pays A dans le pays B.


{% assign width_1 = 100 %}
{% assign width_2 = width_1 | divided_by: 2 %}

*MCC/MNC&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Nom de la personne à contacter au sein de l’Administration&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Addresse&#58;*::
{% for i in (1..width_1) -%}
&#95;
{%- endfor %}

*Tél.&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*Télécopie&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

*E-mail&#58;*::
{% for i in (1..width_2) -%}
&#95;
{%- endfor %}

[cols="5",options="unnumbered"]
|===
^h| MCC/MNC
^h| Nom du ou des opérateurs
h| Pays B – Dans lequel les ressources MCC/MNC font l'objet d' une utilisation extraterritoriale
h| Série de numéros MSIN à utiliser dans le pays A
h| Série de numéros MSIN à utiliser dans le pays B

| | | | |
| | | | |
|===


== Amendments

[cols="^,^,^",options="header,unnumbered"]
|===
| Amendement No
| Bulletin d’exploitation No
| Pays ou zone

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----
