= List of Signalling Area/Network Codes (SANC) (Complement to Recommendation ITU-T Q.708 (03/99))
:bureau: T
:docnumber: Q.708
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125 - 1.VI.2017
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note by TSB

. This List of Signalling Area/Network Codes (SANC) replaces the previous one published as Annex to the ITU Operational Bulletin No. 1066 of 15.XII.2014. Since then, various new assignments have been made and they have been published separately in various issues of the ITU Operational Bulletin. The present List contains all the amendments that have been published up to Operational Bulletin No. 1125 of 1.VI.2017.

. The present List includes:
+
--
* a list of SANC codes in numerical order
* a list of SANC codes in alphabetical order of names of countries/geographical areas.
--

. Recommendation ITU-T Q.708 (03/99) states that the assignment of signalling area/network codes (SANC) is to be administered by the TSB. The assignment/withdrawal of international signalling point codes (ISPC) will be made by each country who will then notify the TSB.

. A request for a SANC is to be made by the Administration in writing to the Director of the TSB. In order to request an additional SANC an Administration must provide the Director of the TSB notification of the current assignment of ISPCs by that Administration.

. For information, this List will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU website www.itu.int/ITU-T/bulletin/annex.html .

. Countries who wish to take part in the international signalling network or require an additional signalling area/network code (SANC) should ask the Director of the TSB for the assignment of an available SANC code. In their request they may indicate the available SANC code preferred. Please address any comments to the Director of the TSB:
+
--
[align=left]
International Telecommunication Union +
Director of the TSB +
Place des Nations +
CH-1211 GENEVA 20 +
Switzerland +
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of the ITU concerning the legal status of any country or geographical area, or of its authorities.


== {blank}

[yaml2text,data=../../datasets/1125-Q.708A/data.yaml,metadata=../../datasets/1125-Q.708A/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== Number of spare ITU-T Q.708 Signalling Area Network Codes (SANCs)

[cols="^,^",options="unnumbered,header"]
|===
| Signalling Area Network Codes, numbering range
| Number of spare codes

| 0-000 to 0-255 | reserved
| 1-000 to 1-255 | reserved
| 2-000 to 2-255 | 0
| 3-000 to 3-255 | 86
| 4-000 to 4-255 | 67
| 5-000 to 5-255 | 122
| 6-000 to 6-255 | 97
| 7-000 to 7-255 | 120
|===

NOTE: Percentage of SANCs assigned = 67.97 %


== AMENDMENTS

[cols="^,^,^",options="unnumbered,header"]
|===
| Amendment No. | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----


