= (SANC) قائمة بالرموز الدليلية لمناطق/شبكات التشوير
:bureau: T
:docnumber: Q.708
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125 - 1.VI.2017
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== ملاحظة من مكتب تقييس الاتصالات

. تحل قائمة الرموز الدليلية لمناطق/شبكات التشوير (SANC) هذه محل القائمة السابقة التي نُشرت في شكل ملحق بالنشرة
التشغيلية للاتحاد رقم 1066 المؤرخة 2014.XII.15 . ومنذ ذلك الحين، مُنحت عدة تخصيصات جديدة ونُشرت هذه التخصيصات
بشكل منفصل في أعداد مختلفة من النشرة التشغيلية للاتحاد. وتلخص هذه القائمة جميع التعديلات التي نُشرت حتى النشرة
التشغيلية رقم 1125 المؤرخة 2017.VI.1 .

. تتضمّن هذه القائمة:
+
--
* قائمة بالرموز الدليلية لمناطق/شبكات التشوير (SANC) بالترتيب العددي
* قائمة بالرموز الدليلية لمناطق/شبكات التشوير (SANC) بالترتيب الأبجدي لأسماء البلدان/المناطق الجغرافية.
--

. تنصّ التوصية (99/03) ITU-T Q.708 على أن مكتب تقييس الاتصالات سيتولّّ تخصيص قائمة الرموز الدليلية
لمناطق/شبكات التشوير. وسيقوم كلّ بلد بتخصيص / سحب رموز نقاط التشوير الدولية (ISPC) وسيبلغ مكتب تقييس الاتصالات
بها فيما بعد.

. تقدّم الإدارة طلب الحصول على رمز دليلي لمناطق/شبكات التشوير خطياً إلّ مدير مكتب تقييس الاتصالات. ولطلب
رم وز إضافية، يجب أن تقدّم إلّ مدير مكتب تقييس الاتصالات تبليغاً بالتخصيص الحالي من جانب الإدارة لرموز نقاط التشوير
الدولية لديها.

. لمزيد من المعلومات، سيجري تحديث القائمة من خلال سلسلة مرقمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد.
وعلاوةً على ذلك، تتاح أيضاً المعلومات الواردة في هذا الملحق في الموقع الإلكتروني للاتحاد: -www.itu.int/ITUT/bulletin/annex.html .

. ينبغي للبلدان التي ترغب في المشاركة في شبكة التشوير الدولية أو تطلب رم ز اً دليلي اً إضافياً لمناطق/شبكات التشوير أن
تطلب إلّ مدير مكتب تقييس الاتصالات تخصيص رمز دليلي متوفر لمناطق/شبكات التشوير (SANC) . ويمكن أن تشير في طلبها
إلّ الرمز الذي تفضّله. ويرجى توجيه أي تعليقات إلّ مدير مكتب تقييس الاتصالات:
+
--
[align=left]
International Telecommunication Union +
Director of the TSB +
Place des Nations +
CH-1211 GENEVA 20 +
Switzerland +
الهاتف: +41 22 730 5887 +
الفاكس: +41 22 730 5853 +
البريد الإلكتروني: mailto:tsbmail@itu.int[]
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تع بر عن أي رأي من جانب الاتحاد بشأن الوضع القانوني لأي
بلد أو منطقة جغرافية أو لسلطات أ ي منهما.


== {blank}

[yaml2text,data=../../datasets/1125-Q.708A/data.yaml,metadata=../../datasets/1125-Q.708A/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== ITU T Q.708 وفقاً للتوصية (SANC) عدد الرموز الدليلية الاحتياطية لمناطق/شبكات التشوير

[cols="^,^",options="unnumbered,header"]
|===
| الرموز الدليلية لمناطق/شبكات التشوير، سلسلة الأرقام
|عدد الرموز الاحتياطية

| من 0-000 إلّ 0-255
| محجوز
| من 1-000 إلّ 1-255
| محجوز
| من 2-000 إلّ 2-255
| 0
| من 3-000 إلّ 3-255
| 86
| من 4-000 إلّ 4-255
| 67
| من 5-000 إلّ 5-255
| 122
| من 6-000 إلّ 6-255
| 97
| من 7-000 إلّ 7-255
| 120
|===

NOTE: نسبة الرموز الدليلية لمناطق/شبكات التشوير المخصصة = %67,97


== تعديلات

[cols="^,^,^",options="unnumbered,header"]
|===
| رقم التعديل
| رقم النشرة التشغيلية
| البلد

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===
----
