= Liste des codes de zone/réseau sémaphore (SANC) (Complément à la Recommandation UIT-T Q.708 (03/1999))
:bureau: T
:docnumber: Q.708
:published-date: 2017-06-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1125 - 1.VI.2017
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note du TSB

. Cette Liste des codes de zone/réseau sémaphore (SANC) remplace celle qui avait été publiée dans l’Annexe au Bulletin d’exploitation No 1066 du 15.XII.2014. Depuis ce jour, différentes assignations nouvelles sont apparues et ont été publiées séparément dans différents numéros du Bulletin d'exploitation de l'UIT. La présente Liste contient tous les amendements qui ont été publiés jusqu’au Bulletin d’exploitation No 1125 du 1.VI.2017.

. La présente Liste comprend:
+
--
* une liste des codes SANC par ordre numérique
* une liste des codes SANC par ordre alphabétique des noms de pays/zones géographiques.
--

. La Recommandation UIT-T Q.708 (03/99) mentionne que l'attribution des codes de zone/réseau sémaphore (SANC) doit être régie par le TSB. L'attribution ou le retrait des codes de points sémaphores internationaux (ISPC) sera fait par chaque pays qui en avisera le TSB.

. L’Administration doit présenter toute demande d’attribution d’un code SANC par écrit et l’adresser au Directeur du TSB. Pour demander un code SANC supplémentaire, une Administration doit informer le Directeur du TSB de la situation actuelle en ce qui concerne les attributions de codes ISPC par cette Administration.

. Pour information, la mise à jour de cette Liste se fera sous la forme d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles, sur le site web de l’UIT (à l'adresse link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Les pays qui désirent faire partie du réseau sémaphore international ou qui désirent un ou plusieurs codes de zone/réseau sémaphore (SANC) supplémentaires doivent demander au Directeur du TSB l'attribution d'un code SANC disponible. Dans leur demande, ils peuvent indiquer le code SANC disponible qu'ils préfèrent. Veuillez adresser vos commentaires au Directeur du TSB:
+
--
[align=left]
Union internationale des télécommunications +
Directeur du TSB +
Place des Nations +
CH-1211 GENÈVE 20 +
Suisse +
Tél: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques ou de leurs autorités.


== {blank}

[yaml2text,data=../../datasets/1125-Q.708A/data.yaml,metadata=../../datasets/1125-Q.708A/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== Nombre des codes de zone/réseau sémaphore UIT-T Q.708 (SANCs) en réserve

[cols="^,^",options="unnumbered,header"]
|===
| Codes de zone/réseau sémaphore, série de numéros
| Nombre de codes en réserve

| 0-000 à 0-255 | réservé
| 1-000 à 1-255 | réservé
| 2-000 à 2-255 | 0
| 3-000 à 3-255 | 86
| 4-000 à 4-255 | 67
| 5-000 à 5-255 | 122
| 6-000 à 6-255 | 97
| 7-000 à 7-255 | 120
|===

NOTE: Pourcentage de SANCs attribués = 67.97 %


== AMENDMENTS

[cols="^,^,^",options="unnumbered,header"]
|===
| Amendement N° | Bulletin d'exploitation N°. | Pays

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===

----