= VARIOUS TONES USED IN NATIONAL NETWORKS (ACCORDING TO ITU-T RECOMMENDATION E.180(03/1998))
:bureau: T
:docnumber: 955
:published-date: 2010-05-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 955
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Note by TSB

. The List of various tones used in national networks has now been updated by amendments published in ITU Operational Bulletin..

. Administrations are reminded of the advantages of standardizing audible tones as far as possible so that subscribers and operators may quickly recognize any tone transmitted of whatever origin.

. In order to have current information and to keep the List up-to-date, Administrations are strongly requested to submit a concise technical description of any new or changed network tones to the ITU/TSB whenever such tones are introduced, by using the attached Notification form.

. For your information, this list will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU web page http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html] .

. Please address any comments or any modifications concerning this List to the Director of the TSB:
+
--
International Telecommunication Union +
Director of the TSB +
Place des Nations +
CH-1211 GENEVA 20 +
Switzerland +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of the ITU concerning the legal status of any country or geographical area, or of its authorities.


[yaml2text,data=../../datasets/955-E.180/data.yaml,metadata=../../datasets/955-E.180/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== Explanation of symbols

Frequency in Hz::
stem:[f_1 xx f_2]::: stem:[f_1] is modulated by stem:[f_2]
stem:[f_1 + f_2]::: the juxtaposition of two frequencies stem:[f_1] and stem:[f_2] without modulation
stem:[f_1 // f_2]::: stem:[f_1] is followed by stem:[f_2]
stem:[f_1] // stem:[f_2]::: in some exchanges frequency stem:[f_1] is used and in others frequency stem:[f_2] is used.
Cadence in seconds:: ON – OFF
----
