= LIST OF DATA COUNTRY OR GEOGRAPHICAL AREA CODES
:bureau: T
:docnumber: 976
:published-date: 2011-03-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 976
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note from TSB

[class=steps]
. This List of data country or geographical area codes replaces the previous one published as Annex to ITU Operational Bulletin No. 875 of 1 January 2007. Since then, various new assignments have been made, and they have been published in the ITU Operational Bulletin .

. This List includes:

* a list of data country or geographical area codes (DCCs) - in numerical order;

. This List will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU website http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Please address any comments concerning this publication to the Director of TSB:
+
--
Tel: +41 22 730 5211

Fax: +41 22 730 5853

Email: tsbmail@itu.int
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.


[yaml2text,data=../../datasets/976-X.121A/data.yaml,metadata=../../datasets/976-X.121A/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== AMENDEMENTS

[%unnumbered]
|===
h| Amendment No. h| Operational Bulletin No. h| Country or Geographical Area

{% for i in (1..30) %}
^.^| {{ i }} | |
{% endfor %}
|===

----
