= LISTE DES INDICATIFS DE PAYS OU ZONES GÉOGRAPHIQUES POUR TRANSMISSION DE DONNÉES
:bureau: T
:docnumber: 976
:published-date: 2011-03-15
:annex-title-fr: Annexe au Bulletin d'exploitation de l'UIT
:annex-id: N° 976
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:
:language: fr


[preface]
== Note du TSB

[class=steps]
. Cette Liste des indicatifs de pays ou de zones géographiques sur les indicatifs de pays pour données (DCC), remplace celle qui avait été publiée dans l'Annexe au Bulletin d'exploitation de l'UIT N° 875 du 1 janvier 2007. Depuis lors, différentes assignations nouvelles sont apparues et ont été publiées séparément dans différents numéros du Bulletin d'exploitation de l'UIT.

. La présente Liste comprend:

* une liste des indicatifs de pays ou de zones géographiques pour transmission de données (DCC), - par ordre numérique;

. La mise à jour de cette liste se fera par des séries d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles sur le site web de l'UIT (à l'adresse http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Veuillez adresser vos commentaires concernant cette publication au Directeur du TSB:
+
--
Tél: +41 22 730 5211

Fax: +41 22 730 5853

Email: tsbmail@itu.int
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.


[yaml2text,data=../../datasets/976-X.121A/data.yaml,metadata=../../datasets/976-X.121A/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "table", data: data, metadata: metadata, lang: lang %}

== AMENDEMENTS

[%unnumbered]
|===
h| Amendement N° h| Bulletin d'exploitation N° h| Pays ou zone géographique

{% for i in (1..30) %}
^.^| {{ i }} | |
{% endfor %}
|===
----


