= СПИСОК ИДЕНТИФИКАЦИОННЫХ НОМЕРОВ ЭМИТЕНТОВ МЕЖДУНАРОДНОЙ КАРТЫ ДЛЯ РАСЧЕТОВ ЗА ЭЛЕКТРОСВЯЗЬ (СОГЛАСНО РЕКОМЕНДАЦИИ МСЭ-Т E.118 (05/2006))
:bureau: T
:docnumber: 1161
:published-date: 2018-12-01
:annex-title: Annex to ITU Operational Bulletin
:annex-id: No. 1161
:status: published
:doctype: service-publication
:keywords:
:imagesdir: images
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Примечание БСЭ

Данный список заменяет список, прилагаемый к Оперативному бюллетеню № 1088 от 15.IX.2015. В нем содержатся все идентификационные номера эмитентов (IIN), зарегистрированные МСЭ, о которых сообщалось в Оперативном бюллетене МСЭ № 1161 от 1.XII.2018 и в предыдущих оперативных бюллетенях.

Доводим до вашего сведения, что данный список будет уточняться путем публикации в link:https://www.itu.int/pub/T-SP/[Оперативном бюллетене МСЭ] серий пронумерованных поправок. Настоящее Приложение доступно для бесплатной загрузки на link:https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[веб-сайте МСЭ].

Номер IIN используется для идентификации компании электросвязи в стране, которая работает в международной среде. В соответствии со стандартом 7812-2 ИСО критерии утверждения или отклонения заявок являются следующими:

"_4.3.1 Критерии утверждения заявки на получение одиночного номера IIN_

Заявки на получение одиночного номера IIN должны соответствовать всем указанным ниже критериям утверждения и не должны соответствовать ни одному критерию отклонения, приведенному в п. 4.3.2:

. заявитель, подающий заявку на одиночный номер IIN, не должен иметь самостоятельно присвоенного номера IIN (не относящегося к какой-либо карточной системе);

. использование номера IIN должно начаться незамедлительно, предпочтительно в течение 12 месяцев считая с даты его выдачи;

. выпускаемая в обращение карта должна предназначаться для использования в среде международного обмена (см. ИСО/МЭК 7812-1);

. заявителем должно быть отдельное юридическое лицо, осуществляющее деятельность в соответствии с определенными законодательными нормами.

_4.3.2 Критерии отклонения заявки на получение одиночного номера IIN_

Заявитель, подающий заявку на получение одиночного номера IIN, должен получить отказ от ответственной организации при наличии любого из следующих условий:

. заявитель не является эмитентом карт;

. заявитель ранее самостоятельно осуществил присвоение номера IIN (вне рамок членства в какой-либо карточной системе), который используется им по настоящее время, и заявитель не предоставил надлежащей дополнительной информации в качестве обоснования выдачи дополнительного номера IIN (см. п. 4.2);

. карты, выпускаемые в обращение заявителем, не будут использоваться в среде международного и/или межотраслевого обмена;

. номер IIN будет использоваться для идентификации или различения продукции, услуг или технологий (т. е. включая, в том числе, карты с интегральными схемами), или только для облегчения маршрутизации, или для определения географического положения;

. номер IIN будет использоваться для идентификации или различения филиалов или дочерних организаций, входящих в организацию заявителя (т. е. данные филиалы или дочерние организации не являются самостоятельными юридическими лицами);

. заявитель подал заявку на конкретный номер или на резервирование в реестре конкретного номера, ии подал заявку, которая не подпадает под действие настоящей части стандарта ИСО/МЭК 7812;

. карты не будут выпущены в обращение незамедлительно, например в течение 12 месяцев считая с даты выдачи номера IIN.

МСЭ является центральным регистрационным органом идентификационных номеров эмитентов (IIN), с идентификатором основной отрасли (MII) для целей электросвязи.

В соответствии с пунктом 4.2 Рекомендации МСЭ-T E.118 МСЭ взимает разовый сбор за присвоение и регистрацию каждого нового идентификационного номера эмитента. С 1 января 2018 года регистрационный сбор составляет 150 швейцарских франков.

Для нечленов Секторов МСЭ-Т и МСЭ-R с 1 января 2018 года введен ежегодный сбор за обслуживание в размере 100 швейцарских франков за номер. Члены МСЭ-Т и МСЭ-R не должны платить ежегодный сбор за обслуживание.

Просим заявителей, подающих заявку на получение одиночного номера IIN, заполнить регистрационную форму и представить ее национальной администрации электросвязи (или должным образом уполномоченной координирующей организации в своей стране) для заполнения, прежде чем направить ее на регистрацию в МСЭ. К заявке должны быть приложены документы, подтверждающие уплату в МСЭ.

Для поддержания данного списка в актуальном состоянии просим перечисленные в нем компании направлять в МСЭ, TSB/OBNA, по факсу: +41 22 730 5853 или электронной почте: mailto:tsbtson@itu.int[] все изменения, касающиеся их и лиц для контактов, включая полный адрес и адрес электронной почты.

Обновления должны быть утверждены национальной администрацией или направлены национальной администрацией.

См. регистрационную форму и дополнительную информацию по адресу: www.itu.int/en/ITU-T/inr/forms/Pages/iin.aspx.

Используемые в настоящем списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны или властей этой страны или географической зоны.


== {blank}

[yaml2text,T-SP-E.118-2018.yaml,file]
----
{% assign lang = "ru" %}


[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}/{{ file.metadata.locale.company_address[lang] }}
| {{ file.metadata.locale.issue_id_number[lang] }}
| {{ file.metadata.locale.contact[lang] }}

{% for country_data in file.data -%}
    | *{{ country_data[1].country_or_area["en"] }}*
    | *{{ country_data[1].company_name }}* +
    {{ country_data[1].company_address_1 }} +
    {{ country_data[1].company_address_2 }}
    | *{{ country_data[0] }}*
    | {{ country_data[1].contact }} +
    {{ country_data[1].contact_address_1 }} +
    {{ country_data[1].contact_address_2 }} +
    Tel: {{ country_data[1].tel }} +
    Fax: {{ country_data[1].fax }} +
    E-mail: {{ country_data[1].email | join: "; " }}
{%- endfor %}
|===


== Поправки

[cols="^,^,^,^",options="unnumbered"]
|===
| № поправки | № Оперативного бюллетеня | Страна/географическая зона | IIN

{% for i in (1..33) -%}
    | {{ i }} | | |
{%- endfor %}
|===
----
