= LISTE DES NUMÉROS IDENTIFICATEURS D'ENTITÉS ÉMETTRICES POUR LES CARTES INTERNATIONALES DE FACTURATION DES TÉLÉCOMMUNICATIONS (SELON LA RECOMMANDATION UIT-T E.118 (05/2006))
:bureau: T
:docnumber: 1161
:published-date: 2018-12-01
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1161
:status: published
:doctype: service-publication
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note du TSB

La présente Liste remplace la Liste annexée au Bulletin d'exploitation de l'UIT N° 1088 du 15.XI.2015. Elle contient tous les numéros identificateurs d'entités émettrices (IIN-Issuer Identifier Number) enregistrés par l'UIT et qui ont fait l'objet d'une notification dans le Bulletin d'exploitation de l'UIT jusqu'au et y compris le N° 1161 du 1.XII.2018.

Pour information, la mise à jour de cette Liste se fera sous la forme d'amendements numérotés publiés dans le link:https://www.itu.int/pub/T-SP/fr[Bulletin d'exploitation de l'UIT]. Cette Annexe est disponible en téléchargement gratuit sur le link:http://www.itu.int/fr/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1[site web de l'UIT].

Le numéro IIN sert à identifier une entreprise de télécommunications dans un pays qui travaille dans un environnement international. D'après la Norme ISO 7812-2, les critères d'acceptation ou de rejet des demandes s'établissent comme suit:

"_4.3.1 Critères d'acceptation d'une demande d'un seul IIN_

Les demandes d'un seul IIN doivent répondre à tous les critères d'acceptation énumérés ci-après et ne doivent satisfaire à aucun des critères de rejet qui figurent en 4.3.2:

. le demandeur d'un seul IIN ne doit pas avoir reçu par le passé un IIN attribué à titre individuel (indépendamment d'un comité de cartes);
. l'IIN doit être destiné à une utilisation immédiate, de préférence dans les 12 mois suivant sa date d'émission;
. la carte émise doit être destinée à une utilisation dans un environnement d'échanges internationaux (voir ISO/CEI 7812-1);
. le demandeur doit être une personne morale distincte dans un cadre législatif spécifique.

_4.3.2 Critères de rejet d'une demande d'un seul IIN_

Une demande d'un seul IIN doit être rejetée par l'autorité de tutelle ou les membres du RMG si l'une des conditions suivantes est vérifiée:

. le demandeur n'est pas un émetteur de cartes;
. le demandeur a reçu par le passé un IIN attribué à titre individuel (indépendamment de son appartenance à un comité de cartes) dont il fait toujours usage et n'a pas fourni d'informations supplémentaires appropriées justifiant l'émission d'un autre IIN (voir paragraphe 4.2);
. les cartes émises par le demandeur ne seront pas utilisées dans un environnement d'échanges internationaux ou intersectoriels;
. l'IIN sera utilisé pour identifier ou distinguer des produits, des services ou des technologies (c'est-à-dire, notamment, les cartes de circuits intégrés, mais pas seulement) ou uniquement pour faciliter le routage, ou bien pour identifier un site géographique;
. l'IIN sera utilisé pour identifier ou distinguer des agences ou des filiales au sein de l'organisme du demandeur (ces agences ou filiales ne sont pas des entités légales distinctes);
. le demandeur a sollicité un numéro spécifique ou la réservation d'un tel numéro dans le registre ou a fait une demande qui n'est pas couverte par la présente section de ISO/IEC 7812;
. aucune carte ne sera émise pour un usage immédiat, c'est-à-dire dans les 12 mois à compter de la date d'émission d'un IIN."

L'UIT est l'organisme central d'enregistrement des numéros IIN avec l'identificateur d'activité économique (MII-Major Industry Identifier) "89" attribué pour les besoins des télécommunications.

En outre, en vertu du point 4.2 d) de la Recommandation UIT-T E.118, l'UIT perçoit une taxe pour l'attribution et l'enregistrement de chaque nouveau numéro identificateur d'entité émettrice (IIN). Depuis le 1er janvier 2018, le montant est fixé à 150 francs suisses.

Pour les entités qui ne sont pas Membres du Secteur de l'UIT-T ou de l'UIT-R, une taxe annuelle de maintenance de 100 francs suisses par numéro enregistré est appliquée à compter du 1er janvier 2018. Les entités Membres du Secteur de l'UIT-T ou de l'UIT-R ne sont pas tenues de payer la taxe annuelle de maintenance.

Les demandeurs sollicitant un seul numéro IIN doivent remplir le formulaire d'enregistrement et le soumettre pour accord à leur l'administration nationale des Télécommunications (ou par un organisme de coordination dûment habilité) avant de l'envoyer à l'UIT pour enregistrement, accompagné d'une preuve de paiement.

Les demandeurs trouveront sur le site web de l'UIT (link:https://www.itu.int/en/ITU-T/inr/forms/Pages/iin.aspx[www.itu.int/en/ITU-T/inr/forms/Pages/iin.aspx]) le formulaire d'enregistrement destiné à faciliter leurs demandes d'attribution et d'enregistrement, ainsi que des informations complémentaires.

Pour la mise à jour de la liste, les entreprises listées sont priées de faire part de toute modification les concernant et de signaler l'adresse des points de contact à l'UIT, TSB/OBNA, Fax: +41 22 730 5853; E-mail: mailto:tsbtson@itu.int[]. Les mises à jour doivent être approuvées ou envoyées par l'administration nationale.

Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.


== {blank}

[yaml2text,T-SP-E.118-2018.yaml,file]
----
{% assign lang = "fr" %}


[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}/{{ file.metadata.locale.company_address[lang] }}
| {{ file.metadata.locale.issue_id_number[lang] }}
| {{ file.metadata.locale.contact[lang] }}

{% for country_data in file.data -%}
    | *{{ country_data[1].country_or_area["en"] }}*
    | *{{ country_data[1].company_name }}* +
    {{ country_data[1].company_address_1 }} +
    {{ country_data[1].company_address_2 }}
    | *{{ country_data[0] }}*
    | {{ country_data[1].contact }} +
    {{ country_data[1].contact_address_1 }} +
    {{ country_data[1].contact_address_2 }} +
    Tel: {{ country_data[1].tel }} +
    Fax: {{ country_data[1].fax }} +
    E-mail: {{ country_data[1].email | join: "; " }}
{%- endfor %}
|===


== AMENDMENTS

[cols="^,^,^,^",options="unnumbered"]
|===
| Amendment N° | Bulletin d'exploitation N° | Pays/zone géographique | IIN

{% for i in (1..33) -%}
    | {{ i }} | | |
{%- endfor %}
|===
----