= LISTA DE INDICADORES DE DESTINO DE TELEGRAMAS
:bureau: T
:docnumber: F.32
:series: Según la Recomendación UIT-T F.32 (10/1995)
:published-date: 2011-05-15
:status: in-force
:doctype: service-publication
:annex-id: No. 980
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. Por Circular TSB 179 del 16 de octubre de 1995, la TSB ha anunciado la aprobación de la
Recomendación UIT-T F.32 (10/1995) (anteriormente F.96), de conformidad con la Resolución 1,
Sección 8 de la CMNT (Helsinki, 1993) y, por Circular TSB 104 del 23 de marzo de 1998, la TSB
ha anunciado la aprobación de la Recomendación UIT-T F.1 (03/1998): «Disposiciones aplicables
a la explotación del servicio público internacional de telegramas», cuyo texto ha sido revisado por
la Comisión de Estudio 2 del UIT-T.
+
--
Por consiguiente, la TSB ha preparado una Lista de indicadores de destino de telegramas
que recoge los indicadores asignados a países/zonas geográficas o redes (dos primeras letras) y
a oficinas telegráficas (tercera y cuarta letras), de conformidad con la Recomendación UIT-T F.32
(10/1995). La Lista contiene también los indicadores especiales de origen y los indicadores
utilizados para designar organizaciones internacionales en la línea de preámbulo de los
telegramas de Estado conformes a la disposición A218 de la Recomendación UIT-T F.1 (03/1998).
--

. La nueva lista publicada en Anexo al Boletín de Explotación de la UIT N.o 980 del
15 de mayo de 2011 sustituye a la publicada en Anexo al Boletín de Explotación de la UIT N.o 879
del 1 de marzo de 2007. Se han añadido a esta lista los países o zonas geográficas para los
cuales una información sobre a la cesación de servicio de telegramas ha sido publicada en el
Boletín de Explotación de la UIT (N.°).
+
--
Asimismo, se recuerda a las administraciones/EER que la
_Lista de códigos de identificación de red télex (CIRD)_
mencionada en el párrafo 7.3 de la Recomendación UIT-T F.32 (10/1995) se
publica ahora por separado, como anexo al Boletín de Explotación de la UIT y que la misma se
actualiza regularmente por medio de enmiendas.

Uno de los principales objetivos de la Recomendación UIT-T F.32 (10/1995) es incitar a las
Administraciones/EER a reducir el número de indicadores de destino atribuidos a sus redes de
telegramas. Durante los últimos años, un gran número de administraciones/EER ha adoptado un
solo indicador de destino (--XX) para todos los destinos o bien sólo ha asignado a sus redes de
telegramas un pequeño número de indicadores de destino. La TSB señala especialmente a la
atención de las administraciones/EER que según el Sección 6 de la Recomendación
UIT-T F.32 (10/1995), que estipula que «Los códigos de oficina (es decir, la tercera y cuarta letras
de un indicador de destino) asignados para cada código de red se deben mantener en un número
mínimo en cada red» y «cuando la red de destino es capaz de realizar el encaminamiento
nacional sin un código de oficina (por ejemplo, analizando la parte de dirección del telegrama así
como la línea piloto), se prefiere un solo código de oficina (XX)».
--

. Con el fin de mantener actualizada la lista, se ruega a las administraciones/EER que
comprueben la exactitud de la información publicada en la misma y que informen tan pronto como
sea posible a la TSB de cualquier cambio que deba realizarse (Fax: *+41 22 730 5853*, o
E-mail: *mailto:tsbtson@itu.int[]*). Los cambios se publicarán como enmiendas a la lista en el siguiente
Boletín de Explotación de la UIT.

. Asimismo, la información que contiene este Anexo al Boletín de Explotación de la
UIT N.° 980 está disponible en el sitio web de la UIT www.itu.int/itu-t/bulletin/annex.html .

. Las denominaciones empleadas en esta lista y la forma en que aparecen presentados los
datos que contiene no implican, por parte de la UIT, juicio alguno sobre la condición jurídica de los
países o zonas geográficas, o de sus autoridades.


[yaml2text,data=../../datasets/980-F.32/data.yaml,metadata=../../datasets/980-F.32/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----
