= LISTE DES INDICATEURS DE DESTINATION DES TÉLÉGRAMMES
:bureau: T
:docnumber: F.32
:series: Selon la Recommandation UIT-T F.32 (10/1995)
:published-date: 2011-05-15
:status: in-force
:doctype: service-publication
:annex-id: No. 980
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note du TSB

. Par la Circulaire TSB 179 du 16 octobre 1995, le TSB annonçait l’approbation de la
Recommandation UIT-T F.32 (10/1995) (antérieurement F.96), conformément aux dispositions de
la Résolution 1, Section 8 de la CMNT (Helsinki, 1993) et, par la Circulaire TSB 104 du
23 mars 1998, il annonçait l’approbation de la Recommandation UIT-T F.1 (03/1998): «Dispositions
applicables à l’exploitation du service public international des télégrammes» dont le texte a
été révisé par la Commission d’études 2 de l’UIT-T.
+
--
En conséquence, le TSB a établi une Liste des indicateurs de destination des télégrammes
attribués aux pays/zones géographiques ou réseaux (deux premières lettres) et aux bureaux
télégraphiques de destination (troisième et quatrième lettres), conformément à la Recommandation
UIT-T F.32 (10/1995). La Liste contient également les indicateurs spéciaux d’origine et les
indicateurs qui désignent les organisations internationales dans la ligne de préambule des télégrammes
d’État selon la disposition A218 de la Recommandation UIT-T F.1 (03/1998).
--

. La nouvelle Liste publiée en annexe au Bulletin d’exploitation de l’UIT No 980 du 15 mai 2011
remplace celle publiée en annexe au Bulletin d’exploitation de l’UIT N° 879 du 1 mars 2007. Les
pays ou zones géographiques pour lesquels des renseignements relatifs à la cessation du service
des télégrammes ont été publiés dans le bulletin d'exploitation de l'UIT (No) sont ajoutés à cette
liste.
+
--
Par ailleurs, il est rappelé aux administrations/ER que la Liste des codes d’identification des
réseaux télex (CIRT), dont il est question au paragraphe 7.3 de la Recommandation UIT-T F.32
(10/1995), est publiée séparément sous forme d’annexe au Bulletin d’exploitation de l’UIT et
qu’elle est régulièrement mise à jour par des amendements.

Un des principaux buts visés par la Recommandation UIT-T F.32 (10/1995) est d’inciter les
administrations/ER à réduire le nombre des indicateurs de destination attribués à leurs réseaux
télégraphiques. Depuis quelques années, un grand nombre d’administrations/ER ont adopté un
seul indicateur de destination (--XX) pour toutes les destinations, ou n’ont attribué qu’un nombre
très restreint d’indicateurs de destination à leurs réseaux. Le TSB attire plus particulièrement
l’attention des administrations/ER sur la Section 6 de la Recommandation UIT-T F.32 (10/1995)
qui dispose que «Les codes de bureau (c’est-à-dire les troisième et quatrième lettres d’un
indicateur de destination) qui sont attribués et qui correspondent à un code de réseau, doivent
rester aussi peu nombreux que possible dans chaque réseau.» et que «Lorsque le réseau de
destination est en mesure d’assurer l’acheminement au niveau national (par exemple, en
analysant la partie adresse du télégramme ainsi que la ligne pilote), l’utilisation d’un code de
bureau unique (XX) est choisie de préférence.»
--

. Pour permettre la tenue à jour de la liste, les administrations/ER sont priées de vérifier
l’exactitude des informations qu’elle contient et d’informer le TSB dès que possible de toute
modification qui serait nécessaire (Fax: *+41 22 730 5853*, ou E-mail: *mailto:tsbtson@itu.int[]*). Les
modifications seront publiées sous forme d’amendements à la liste dans le Bulletin d’exploitation
de l’UIT suivant.

. En outre, les renseignements contenus dans cette Annexe au Bulletin d’exploitation de l’UIT
N° 980 peuvent également être consultés sur le site web de l'UIT à l'adresse suivante:
link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]

. Les appellations employées dans cette liste et la présentation des données qui y figurent
n’impliquent, de la part de l’UIT, aucune prise de position quant au statut juridique des pays ou
zones géographiques, ou de leurs autorités.


[yaml2text,data=../../datasets/980-F.32/data.yaml,metadata=../../datasets/980-F.32/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----



