= SYSTÈMES DE RAPPEL (CALL-BACK) ET PROCÉDURES D'APPEL ALTERNATIVES
:bureau: T
:docnumber: PP-2006
:published-date: 2011-11-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: N.° 991 - 1.XI.2011
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== Note du TSB

. Pour que la Liste puisse être tenue à jour, les Administrations sont priées d'aviser le TSB de
toute modification concernant les systèmes de rappel (Call-Back) dans leur pays, en utilisant
l'adresse indiquée ci-dessous.

. Veuillez adresser vos commentaires concernant cette Liste au Directeur du TSB:
Union internationale des télécommunications
+
--
Directeur du TSB +
Place des Nations +
CH-1211 GENÈVE 20 +
Suisse +
Tél: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: tsbtson@itu.int
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent
n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou
zones géographiques ou de leurs autorités.


[yaml2text,data=../../datasets/991-PP.RES.21.pp/data.yaml,metadata=../../datasets/991-PP.RES.21.pp/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----