= COMUNICACIONES POR INTERMEDIARO (CALL-BACK) Y PROCEDIMIENTOS ALTERNATIVOS DE LLAMADA
:bureau: T
:docnumber: PP-2006
:published-date: 2011-11-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: N.° 991 - 1.XI.2011
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:



== Nota de la TSB

. Para mantener la Lista al día, se solicita a las administraciones que notifiquen a la TSB, a la
dirección indicada más abajo, cualquier modificación en su país relativa a las comunicaciones por
intermediario (Call-Back).

. Sírvase comunicar sus comentarios o modificaciones con respecto a esta Lista al Director de
la TSB:
+
--
[align=left]
Unión Internacional de Telecomunicaciones +
Director de la TSB +
Place des Nations +
CH-1211 GINEBRA 20 +
Suiza +
Tel: +41 22 730 5211 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los
datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de
países o zonas geográficas, o de sus autoridades.


[yaml2text,data=../../datasets/991-PP.RES.21.pp/data.yaml,metadata=../../datasets/991-PP.RES.21.pp/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----
