# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ituob.gemspec
gemspec

gem "bundler"
gem "rake"
gem "rspec"
gem "prosemirror", path: "../prosemirror"
