= LIST OF MOBILE COUNTRY OR GEOGRAPHICAL AREA CODES
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1117
:keywords: 
:imagesdir: images
:docfile: T-SP-E.212A-2017-E.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Note from TSB


. This List of mobile country or geographical area codes replaces the previous one published
as Annex to ITU Operational Bulletin No. 1005 of 1 June 2012. Since then, various new
assignments have been made, and they have been published in the ITU Operational Bulletin.

. This List includes:
+
--
* a list of mobile country or geographical area codes - in numerical order;
* a list of mobile country or geographical area codes - in alphabetical order.
--

. This List will be updated by numbered series of amendments published in the ITU
Operational Bulletin. Furthermore, the information contained in this Annex is also available on the
ITU website link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Please address any comments concerning this publication to the Director of TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
Email: mailto:tsbmail@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the
expression of any opinion whatsoever on the part of ITU concerning the legal status of any country
or geographical area, or of its authorities.


[yaml2text,T-SP-E.212A-2017.main.yaml,file]
----
{% assign lang = "en" %}

== {{ file.metadata.title[lang] }} - numerical order

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign note_first_word = note_content.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            {% assign note_a = note_content[lang] %}
        {% when "Dubai:" %}
            {% assign note_b = note_content[lang] %}
        {% when "Associated" %}
            {% assign note_c = note_content[lang] %}
        {% when "This" %}
            {% assign note_d = note_content[lang] %}
    {% endcase %}
{% endfor %}


[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data -%}
    | {{ country_data.code }} | {{ country_data.country_or_area[lang] }} | 
    {% assign note_first_word = country_data.note.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            <<note_a,a>>
        {% when "Dubai:" %}
            <<note_b,b>>
        {% when "Associated" %}
            <<note_c,c>>
        {% when "This" %}
            <<note_d,d>>
    {% endcase %}
{%- endfor %}

|===


== {{ file.metadata.title[lang] }} - alphabetical order

{% assign ordered_sequence = file.data | map: "country_or_area" | sort: lang | uniq %}

[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for next_country in ordered_sequence -%}
    {%- for country_data in file.data -%}
        {%- if country_data.country_or_area[lang] == next_country[lang] -%}
            | {{ country_data.code }} | {{ country_data.country_or_area[lang] }} | 
            {% assign note_first_word = country_data.note.en | split: " " | first %}
            {% case note_first_word %}
                {% when "Mobile" %}
                    <<note_a,a>>
                {% when "Dubai:" %}
                    <<note_b,b>>
                {% when "Associated" %}
                    <<note_c,c>>
                {% when "This" %}
                    <<note_d,d>>
            {% endcase %}
        {%- endif -%}
    {%- endfor %}
{%- endfor %}
|===


{{ file.metadata.locale.note[lang] | append: "s"}}:

. [[note_a]]{{ note_a }}

. [[note_b]]{{ file.data | map: "country_or_area" | where: "en", "United Arab Emirates" | map: lang | uniq }}, {{ note_b }}

. [[note_c]]{{ note_c }}
+
--
[yaml2text,T-SP-E.212A-2017.mcc_mnc.yaml,file_two]
---

[cols="^,^,^",options="unnumbered"]
|===
| {{ file_two.metadata.locale.network[lang] }} | {{ file_two.metadata.locale.mcc_mnc[lang] }} | {{ file_two.metadata.locale.status[lang] }}

{% for company in file_two.data %}
<| {{ company[1].network }} | {{ company[1].mcc_mnc }} | {{ company[1].status | replace: "assigned", file_two.metadata.locale.assigned[lang] }}
{% endfor %}

|===
---
--
. [[note_d]]{{ note_d }}


== Number of spare ITU-T E.212 Mobile Country or Geographical Area Codes (MCCs)


[cols="^,^",options="unnumbered"]
|===
| Mobile Country or Geographical Area Codes, number range | Number of spare codes

| 000 - 099 | reserved
| 100 - 199 | reserved
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | reserved
| 900 - 999 | 99
|===


== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendment No. | Operational Bulletin No. | Country

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}
|===

----



