= LISTA DE INDICATIVOS DE PAÍS O ZONA GEOGRÁFICA PARA EL SERVICIO MOVÍL
:bureau: T
:docnumber: E.212
:published-date: 2017-02-01
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1117
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Nota de la TSB

. Esta Lista de indicativos de país o zona geográfica para el servicio movíl reemplaza la publicada en el Anexo al Boletín de Explotación de la UIT N.o 1005 del 1 de junio de 2012. Desde entonces, se han efectuado varias asignaciones nuevas, que se han publicado en diferentes números del Boletín de Explotación de la UIT.

. La presente Lista comprende:
+
--
* una lista de indicativos de país o zona geográfica para el servicio movíl - en orden numérico;
* una lista de indicativos de país o zona geográfica para el servicio movíl - en orden alfabético.
--

. La Lista se actualizará por series de enmiendas numeradas que se publicarán en el Boletín de Explotación de la UIT. Por otra parte, la información contenida en este Anexo está disponible en el sitio web de la UIT (link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html]).

. Sírvase comunicar sus comentarios con respecto a esta publicación al Director de la TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
Email: mailto:tsbmail@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas, o de sus autoridades.


[yaml2text,T-SP-E.212A-2017.main.yaml,file]
----
{% assign lang = "es" %}

== {{ file.metadata.title[lang] }} - numerical order

{% assign notes = file.data | map: "note" | uniq %}

{% for note_content in notes %}
    {% assign note_first_word = note_content.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            {% assign note_a = note_content[lang] %}
        {% when "Dubai:" %}
            {% assign note_b = note_content[lang] %}
        {% when "Associated" %}
            {% assign note_c = note_content[lang] %}
        {% when "This" %}
            {% assign note_d = note_content[lang] %}
    {% endcase %}
{% endfor %}


[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for country_data in file.data -%}
    | {{ country_data.code }} | {{ country_data.country_or_area[lang] }} |
    {% assign note_first_word = country_data.note.en | split: " " | first %}
    {% case note_first_word %}
        {% when "Mobile" %}
            <<note_a,a>>
        {% when "Dubai:" %}
            <<note_b,b>>
        {% when "Associated" %}
            <<note_c,c>>
        {% when "This" %}
            <<note_d,d>>
    {% endcase %}
{%- endfor %}

|===


== {{ file.metadata.title[lang] }} - alphabetical order

{% assign ordered_sequence = file.data | map: "country_or_area" | sort: lang | uniq %}

[cols="3",options="unnumbered"]
|===
| {{ file.metadata.locale.code[lang] }} | {{ file.metadata.locale.country_or_area[lang] }} | {{ file.metadata.locale.note[lang] }}

{% for next_country in ordered_sequence -%}
    {%- for country_data in file.data -%}
        {%- if country_data.country_or_area[lang] == next_country[lang] -%}
            | {{ country_data.code }} | {{ country_data.country_or_area[lang] }} |
            {% assign note_first_word = country_data.note.en | split: " " | first %}
            {% case note_first_word %}
                {% when "Mobile" %}
                    <<note_a,a>>
                {% when "Dubai:" %}
                    <<note_b,b>>
                {% when "Associated" %}
                    <<note_c,c>>
                {% when "This" %}
                    <<note_d,d>>
            {% endcase %}
        {%- endif -%}
    {%- endfor %}
{%- endfor %}
|===


{{ file.metadata.locale.note[lang] | append: "s"}}:

. [[note_a]]{{ note_a }}

. [[note_b]]{{ file.data | map: "country_or_area" | where: "en", "United Arab Emirates" | map: lang | uniq }}, {{ note_b }}

. [[note_c]]{{ note_c }}
+
--
[yaml2text,T-SP-E.212A-2017.mcc_mnc.yaml,file_two]
---
[cols="^,^,^",options="unnumbered"]
|===
| {{ file_two.metadata.locale.network[lang] }} | {{ file_two.metadata.locale.mcc_mnc[lang] }} | {{ file_two.metadata.locale.status[lang] }}

{% for company in file_two.data %}
<| {{ company[1].network }} | {{ company[1].mcc_mnc }} | {{ company[1].status | replace: "assigned", file_two.metadata.locale.assigned[lang] }}
{% endfor %}
|===
---
--

. [[note_d]]{{ note_d }}


== Número de indicativos de país o zona geográfica para el servicio movíl UIT-T E.212 (MCCs) de reserva

[cols="^,^",options="unnumbered"]
|===
| Indicativos de país o zona geográfica para el servicio movíl, gama de números | Número de indicativos de país de reserva

| 000 - 099 | Reservado
| 100 - 199 | Reservado
| 200 - 299 | 47
| 300 - 399 | 66
| 400 - 499 | 55
| 500 - 599 | 72
| 600 - 699 | 44
| 700 - 799 | 79
| 800 - 899 | Reservado
| 900 - 999 | 99
|===


== ENMIENDAS

[cols="^,^,^",options="unnumbered"]
|===
| Enmienda N.° | Boletín de Explotación N.° | País

{% for i in (1..30) %}
| {{ i }} | |
{% endfor %}

|===

----