= СПИСОК КОДОВ МСЭ ОПЕРАТОРОВ СВЯЗИ (СОГЛАСНО РЕКОМЕНДАЦИИ МСЭ-Т M.1400 (03/2013)
:bureau: T
:docnumber: M.1400
:published-date: 2014-09-15
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1060
:keywords: 
:imagesdir: images
:docfile: T-SP-M.1400-2014-R.adoc
:language: ru
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:


[preface]
== Примечание БСЭ

. Число операторов электросвязи в каждой стране растет быстрыми темпами, в результате чего число присоединений между их сетями увеличивается еще быстрее. Вследствие этого, для участвующих операторов большую значимость представляет стандартизация пунктов назначения всех сетевых присоединений. Только при таком условии они могут систематически и эффективно осуществлять предоставление и техническое обслуживание.

. Надлежащее использование Рекомендации МСЭ-Т M.1400 требует идентификации операторов связи, участвующих в присоединении. Для этой цели весьма полезен общий список операторов, работающих в стране, и официально признанных и стандартизированных кодов каждого из них. С помощью такого списка операторы будут иметь возможность полной и уникальной идентификации друг друга. В результате будет сформирована единая комплексная база данных для всех соединений, что, в свою очередь, улучшит функционирование и администрирование сетей на благо и поставщиков, и их клиентов.

. Либерализация электросвязи и возросшая конкуренция в отрасли электросвязи обусловили обязательное требование идентификации взаимодействующих операторов электросвязи. БСЭ МСЭ составило Централизованный список кодов МСЭ операторов связи (ICC) в качестве репозитория. Ожидается, что все национальные и международные операторы зарегистрируют в БСЭ МСЭ коды операторов связи. Вместо того чтобы каждый оператор направлял свой ICC в БСЭ для регистрации, предлагаем регуляторным органам представить действительные коды международных и национальных операторов сетей и относящуюся к ним информацию непосредственно в БСЭ, используя форму уведомления об ICC, доступную в онлайновом режиме по адресу: http://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx.

. По списку ICC идентифицируются операторы, признаваемые всеми администрациями Государств-Членов. Этот список размещен на центральном веб-сайте МСЭ в относящемся к ICC разделе по адресу: link:https://www.itu.int/oth/T0201[www.itu.int/ITU-T/inr/icc/index.html]. Коды ICC могут использоваться для операций электронной коммерции между операторами и для обозначения ресурсов в их сетях. Таким образом, ICC могут присваиваться и операторам сетей, и поставщикам услуг.

. Список кодов МСЭ операторов связи заменяет Список, опубликованный в качестве Приложения к Оперативному бюллетеню МСЭ № 981 от 1.VI.2011. С тех пор БСЭ был получен ряд уведомлений, которые были опубликованы отдельно в разных выпусках Оперативного бюллетеня МСЭ. В настоящий Список включены все различные поправки, которые были опубликованы в номерах Оперативного бюллетеня до № 1060 от 15.IX.2014.

. Настоящий Список обновляется с помощью нумерованной серии поправок, публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Любые замечания, предложения или сведения о новых присвоениях, касающиеся настоящего Списка, просим направлять Директору БСЭ:
+
--
International Telecommunication Union +
Director of TSB +
Факс: +41 22 730 5853 +
Эл. почта: tsbtson@itu.int
--

. Используемые в настоящем списке обозначения и способ подачи материала не подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении правового статуса какой-либо страны или географической зоны или властей этой страны или географической зоны.


[%landscape]
<<<

== {blank}

[yaml2text,T-SP-M.1400-2014.yaml,file]
----
{% assign lang = "ru" %}


NOTE: {{ file.metadata.note[lang] }}

[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}
| {{ file.metadata.locale.carrier_code[lang] }}
| {{ file.metadata.locale.contact[lang] }}


{% for country_data in file.data -%}
    | *{{ country_data.country_or_area[lang] }} / {{ country_data.iso_code }}*
    | *{{ country_data.company_name }}* +
    {{ country_data.address_line_1 }} +
    {{ country_data.address_line_2 }}
    | *{{ country_data.carrier_code }}*
    |
        {% if country_data.contact %}
            {{ country_data.contact }} +
        {% endif %}

        {% if country_data.tel %}
            {{ file.metadata.locale.tel[lang] }}: {{ country_data.tel }} +
        {% endif %}
    
        {% if country_data.fax %}
            {{ file.metadata.locale.fax[lang] }}: {{ country_data.fax }} +
        {% endif %}

        {% if country_data.email %}
            {{ file.metadata.locale.email[lang] }}: {{ country_data.email }}
        {% endif %}
{%- endfor %}
|===


[%portrait]
<<<

== Форма уведомления для списка кодов МСЭ операторов связи footnote:[http://www.itu.int/oth/T0206000006/en]

Начиная с 1 января 2004 года для операторов, использующих Рекомендацию МСЭ-Т М.1400, обязательно наличие идентификатора оператора или кода МСЭ оператора связи (ICC) в пересмотренной структуре уровня 1 для определения оконечных пунктов маршрута. Код ICC обязателен для осуществления присоединений между операторами различных стран и между различными операторами той же страны. Этот код используется в записях уровня 1 Рекомендации МСЭ-Т М.1400 для однозначной идентификации оконечных пунктов маршрута. Он используется также в целях регистрации оператором тех операторов, с которыми осуществляется присоединение.

Для того чтобы составить список кодов ICC, который можно использовать для идентификации осуществляющих присоединение операторов в записях МСЭ-Т М.1400, описанных в Рекомендации МСЭ-Т М.1400, предлагаем национальным регуляторным органам заполнить настоящую Форму уведомления, указав действительные коды международных и национальных операторов и относящуюся к ним информацию. После заполнения настоящую Форму уведомления следует направить непосредственно в БСЭ по следующему адресу:

Director of TSB +
International Telecommunication Union +
Place des Nations +
1211 Geneva 20 +
Switzerland +
Эл. почта: mailto:tsbtson@itu.int[] +
Факс: +41 22 730 58 53


. *Полное название компании:* +
(название оператора)

. *Код компании:*
+
--
[cols="6",options="unnumbered"]
|===
| | | | | |
|===

(Код, которым оператор желает идентифицировать себя. Этот код должен быть буквенным или цифровым (A–Z):(0–9) не более шести знаков и/или цифр, и должен быть уникальным идентификатором оператора сети/поставщика услуг в пределах каждой страны. Этим кодом может быть код, используемый в настоящее время, при условии что он соответствует настоящему определению).
--

. *Официальный адрес компании:*

. *Для контактов:*
+
--
Тел.: + +
Факс: + +
Эл. почта:
--

*Дата:*


== Поправки

[cols="^,^,^,^",options="unnumbered"]
|===

h| Поправка № h| Оперативный бюллетень № h| Страна или зона h| ICC

{% for i in (1..33) %}
| {{ i }} | | |
{% endfor %}
|===
----

