= LISTA DE CÓDIGOS DE OPERADOR DE LA UIT (SEGÚN LA RECOMENDACIÓN UIT-T M.1400 (03/2013))
:bureau: T
:docnumber: M.1400
:published-date: 2014-09-15
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1060
:keywords: 
:imagesdir: images
:docfile: T-SP-M.1400-2014-S.adoc
:mn-document-class: ituob
:mn-output-extensions: xml,html,doc,rxl
:local-cache-only:
:data-uri-image:
:stem:

[preface]
== Nota de la TSB

. El rápido crecimiento del número de operadores de telecomunicaciones en cada país hace
que el número de interconexiones entre sus redes aumente a velocidad todavía mayor. Por
consiguiente, la normalización de las designaciones de todas las interconexiones de red es de
gran interés para los operadores, puesto que les permiten explotar y mantener las redes de forma
sistemática y eficiente.

. La utilización adecuada de la Recomendación UIT-T M.1400 exige la identificación de los
operadores que comparten la interconexión. A tal fin, la lista general de operadores que trabajan
en un país, con un código oficialmente reconocido y normalizado para cada uno de ellos, es una
gran ayuda, pues las permite la identificarse entre sí de forma completa y unívoca. Dicha lista se
convertirá en una base de datos integrada para todas las conexiones que, a su vez, mejorará la
explotación y administración de la red en beneficio de los proveedores y clientes.

. Debido a la liberalización de las telecomunicaciones y a la intensificación de la competencia
en dicha industria, se exige la identificación de los operadores o empresas de explotación que
mantienen relaciones de interfuncionamiento. La TSB de la UIT ha creado una Lista centralizada
de códigos de operador de la UIT (ICC, ITU carrier codes), de la que la Oficina es la depositaria.
Se espera que todos los operadores nacionales e internacionales registren su código de operador
en la TSB/UIT. En lugar de que los operadores envíen individualmente sus ICC a la TSB para su
registro, se solicita que las autoridades de regulación nacionales proporcionen a la TSB los
códigos validados y las informaciones asociadas a los operadores de redes internacionales y
nacionales directamente a la TSB mediante el formulario de notificación de ICC en:
link:https://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx[http://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx].

. La lista de ICC identifica a los operadores reconocidos por las Administraciones de cada
Estado Miembro. Dicha lista figura en el sitio web central de la UIT para los ICC en
link:https://www.itu.int/ITU-T/inr/icc/index.html[www.itu.int/ITU-T/inr/icc/index.html].
Estos códigos de operador pueden ser utilizados tanto para el
comercio electrónico entre operadores como para la designación de recursos en sus redes. Por lo
tanto, los ICC pueden ser asignados a operadores de red y a proveedores de servicio

. Esta Lista de los códigos de operador de la UIT reemplaza la publicada en el Anexo al
Boletín de Explotación N.o 981 de 1.VI.2011. Desde entonces, se han recibido en la TSB y
publicado por separado en diferentes números del Boletín de Explotación de la UIT diferentes
notificaciones. La presente Lista recapitulativa comprende todas las enmiendas publicadas hasta
el Boletín de Explotación N.o 1060 de 15.IX.2014.

. La Lista se actualizará por medio de enmiendas que se publicarán en el Boletín de
Explotación de la UIT. Por otra parte, la información contenida en este Anexo está disponible para
el sitio web de la UIT link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Sírvase comunicar sus comentarios, sugerencias o nueva atribución con respecto a esta
Lista al Director de la TSB:
+
--
[align=left]
Unión Internacional de Telecomunicaciones +
Director de la TSB +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los
datos que contiene no implican, de parte de la UIT, juicio alguno sobre la condición jurídica de
países o zonas geográficas, o de sus autoridades.


[%landscape]
<<<

== {blank}

[yaml2text,T-SP-M.1400-2014.yaml,file]
----
{% assign lang = "es" %}


NOTE: {{ file.metadata.note[lang] }}

[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}
| {{ file.metadata.locale.carrier_code[lang] }}
| {{ file.metadata.locale.contact[lang] }}


{% for country_data in file.data -%}
    | *{{ country_data.country_or_area[lang] }} / {{ country_data.iso_code }}*
    | *{{ country_data.company_name }}* +
    {{ country_data.address_line_1 }} +
    {{ country_data.address_line_2 }}
    | *{{ country_data.carrier_code }}*
    |
        {% if country_data.contact %}
            {{ country_data.contact }} +
        {% endif %}

        {% if country_data.tel %}
            {{ file.metadata.locale.tel[lang] }}: {{ country_data.tel }} +
        {% endif %}
    
        {% if country_data.fax %}
            {{ file.metadata.locale.fax[lang] }}: {{ country_data.fax }} +
        {% endif %}

        {% if country_data.email %}
            {{ file.metadata.locale.email[lang] }}: {{ country_data.email }}
        {% endif %}
{%- endfor %}
|===


[%portrait]
<<<

== Formulario de notificación de la lista de códigos de operador de la UIT footnote:[http://www.itu.int/oth/T0206000006/en]

A partir del 1 de enero de 2004, es obligatorio que los operadores que utilizan la
Recomendación UIT-T M.1400, tengan un código de operador de la UIT (ICC) en la estructura de
la Capa 1 revisada para identificar las terminaciones de encaminamiento. Este código es
indispensable para las interconexiones entre operadores de diferentes países y entre diferentes
operadores del mismo país. Además, este código se utiliza en los registros de la Capa 1 de la
Recomendación UIT-T M.1400 para identificar unívocamente las terminaciones de
encaminamiento, así como para que un operador registre sus operadores de interconexión.

A fin de elaborar una lista de los ICC que pueda utilizarse para identificar a los operadores de
interconexión mediante registros de la Recomendación UIT-T M.1400, como se explica en esa
misma Recomendación, se solicita a las autoridades nacionales de regulación que cumplimenten el
presente formulario, indicando los códigos validados e información conexa de cada operador
internacional o nacional. Una vez cumplimentado, deberá enviarse el formulario directamente a la
TSB a la siguiente dirección:

Director of TSB +
Unión Internacional de Telecomunicaciones +
Place des Nations +
1211 Ginebra 20 +
Suiza +
Correo-e: mailto:tsbtson@itu.int[] +
Fax: +41 22 730 58 53


. *Nombre completo de la empresa:* +
(nombre del operador)

. *Código de la empresa:*
+
--
[cols="6",options="unnumbered"]
|===
| | | | | |
|===

(Código mediante el cual el operador desea identificarse. Este código constará de hasta seis
caracteres alfabéticos (A-Z) o numéricos (0-9) y será un identificador de operador de red/proveedor
de servicio único en el país correspondiente. El código puede ser uno de los códigos utilizados
actualmente, siempre que se atenga a la definición.)
--

. *Dirección oficial de la empresa:*

. *Contacto:*
+
--
Tel.: + +
Fax: + +
Correo-e:
--

*Fecha:*


== ENMIENDAS

[cols="^,^,^,^",options="unnumbered"]
|===

h| Enmienda N.° h| Boletín de Explotación N.° h| País o zona h| ICC

{% for i in (1..33) %}
| {{ i }} | | |
{% endfor %}
|===
----

