= LISTE DES CODES DE TRANSPORTEUR DE L’UIT (SELON LA RECOMMANDATION UIT-T M.1400 (03/2013))
:bureau: T
:docnumber: E.212
:published-date: 2014-09-15
:status: published
:doctype: service-publication
:annextitle: Annex to ITU Operational Bulletin
:annexid: No. 1060
:keywords:
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:
:stem:


[preface]
== Note du TSB

. Etant donné que le nombre d'opérateurs de télécommunication dans chaque pays ne
cesse de croître, le nombre d'interconnexions entre leurs réseaux augmente encore plus
rapidement. La normalisation des désignations de toutes les interconnexions de réseau est donc
une préoccupation majeure pour les opérateurs concernés. Ce n'est que lorsque cette
normalisation aura été effectuée que les opérateurs pourront procéder de manière systématique et
efficace aux travaux de mise en service et de maintenance.

. La bonne application de la Recommandation UIT-T M.1400 passe par l'identification des
opérateurs qui utilisent en commun l'interconnexion. A cette fin, une liste générale des opérateurs
en activité dans un pays, disposant chacun d'un code normalisé officiellement reconnu, serait très
utile à ceux-ci pour s'identifier mutuellement de manière précise et unique. Une telle liste permettra
à terme d'établir une base de données intégrée pour toutes les connexions, laquelle améliorera la
gestion et l'exploitation du réseau dans l'intérêt des fournisseurs de services et des clients.

. En raison de la libéralisation des télécommunications et de l'intensification de la
concurrence dans le secteur, il est devenu impératif d'identifier les opérateurs de
télécommunication dont les réseaux sont en interfonctionnement. Une Liste centralisée des codes
de transporteur de l’UIT (ICC, ITU carrier codes) a été dressée, l'UIT/TSB en étant le dépositaire.
Tous les exploitants nationaux et internationaux sont appelés à s'enregistrer auprès de l'UIT/TSB
afin d'obtenir un code de transporteur. Plutôt que de laisser chaque opérateur communiquer son
code de transporteur au TSB pour enregistrement, il est demandé aux autorités nationales
chargées de la réglementation de communiquer directement au TSB, les codes validés ainsi que
les informations connexes concernant les opérateurs de réseaux internationaux et nationaux, en
utilisant le formulaire de notification pour ICC disponible en ligne, à l'adresse:
link:https://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx[http://www.itu.int/en/ITU-T/inr/forms/Pages/carrier.aspx].

. Cette liste permet d'identifier les opérateurs reconnus par chaque administration des Etats
membres. Elle est disponible sur le site Web central ICC de l'UIT à l'adresse
link:http://www.itu.int/ITU-T/inr/icc/index.html[www.itu.int/ITU-T/inr/icc/index.html].
Les ICC peuvent être utilisés pour le commerce électronique
entre opérateurs et pour la désignation des ressources de réseau. Ils peuvent donc être assignés
aux opérateurs de réseau et aux fournisseurs de services.

. Cette Liste des codes de transporteur de l’UIT remplace celle qui avait été publiée dans
l’Annexe du Bulletin d'exploitation No 981 du 1.VI.2011. Depuis ce jour, différentes notifications ont
été reçues au TSB et ont été publiées séparément dans différents numéros du Bulletin
d'exploitation de l'UIT. La présente Liste récapitule tous les différents amendements qui ont été
publiés jusqu'au Bulletin d'exploitation No 1060 du 15.IX.2014.

. La mise à jour de cette Liste se fera sous la forme d'amendements numérotés publiés dans
le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont
disponibles sur le site web de l’UIT, à l'adresse link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Veuillez adresser vos commentaires, suggestions ou une nouvelle attribution concernant
cette Liste au Directeur du TSB:
+
--
Union internationale des télécommunications +
Directeur du TSB +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbtson@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent
n'impliquent, de la part de l'UIT, aucune prise de position quand au statut juridique des pays ou
zones géographiques ou de leurs autorités.


[%landscape]
<<<

== {blank}

[yaml2text,T-SP-M.1400-2014.yaml,file]
----
{% assign lang = "fr" %}

NOTE: {{ file.metadata.note[lang] }}

[cols="4",options="unnumbered,header"]
|===
| {{ file.metadata.locale.country_or_area[lang] }}
| {{ file.metadata.locale.company_name[lang] }}
| {{ file.metadata.locale.carrier_code[lang] }}
| {{ file.metadata.locale.contact[lang] }}


{% for country_data in file.data -%}
    | *{{ country_data.country_or_area[lang] }} / {{ country_data.iso_code }}*
    | *{{ country_data.company_name }}* +
    {{ country_data.address_line_1 }} +
    {{ country_data.address_line_2 }}
    | *{{ country_data.carrier_code }}*
    |
        {% if country_data.contact %}
            {{ country_data.contact }} +
        {% endif %}

        {% if country_data.tel %}
            {{ file.metadata.locale.tel[lang] }}: {{ country_data.tel }} +
        {% endif %}

        {% if country_data.fax %}
            {{ file.metadata.locale.fax[lang] }}: {{ country_data.fax }} +
        {% endif %}

        {% if country_data.email %}
            {{ file.metadata.locale.email[lang] }}: {{ country_data.email }}
        {% endif %}
{%- endfor %}
|===


[%portrait]
<<<

== Formulaire de notification pour la liste des codes de transporteur de l'UIT footnote:[http://www.itu.int/oth/T0206000006/en]

Depuis le 1er janvier 2004, les opérateurs qui utilisent l'identificateur d'opérateur ou le code
d'exploitant de l'UIT (ICC) conformes à la Recommandation UIT-T M.1400 dans la structure
révisée de la couche 1, ont l'obligation d'identifier les extrémités de route. Un code ICC est
obligatoire pour les interconnexions entre opérateurs de pays différents ainsi qu'entre opérateurs
différents d'un même pays. Ce code est utilisé dans les informations de couche 1 UIT-T M.1400
pour l'identification univoque des extrémités de route. Il est également utilisé pour l'enregistrement
des opérateurs qui s'interconnectent avec un opérateur donné.

Afin d'établir une liste des codes ICC qui puisse être utilisée pour identifier les opérateurs en
interconnexion dans les informations de désignation UIT-T M.1400, comme expliqué dans la
Recommandation UIT-T M.1400, les organismes de réglementation nationaux sont invités à remplir
le présent formulaire de notification en indiquant les codes validés et les informations associées
concernant les opérateurs internationaux et les opérateurs nationaux. Une fois rempli, ce formulaire
de notification devra être envoyé directement au TSB, à l'adresse suivante:

Directeur du TSB +
Union internationale des télécommunications +
Place des Nations +
1211 Genève 20 +
Suisse +
E-mail: mailto:tsbtson@itu.int[] +
Fax: +41 22 730 58 53


. *Nom complet de la société:* +
(name of operator)

. *Code de la Société:*
+
--
(The code by which the operator wishes to identify itself. This code shall be alphabetic or alphanumeric
(A to Z):(0 to 9)), up to six characters and/or digits long, and shall be a unique identifier of a network
operator/service provider within each country. This code may be one that is in use today, provided it fits
the definition.)
--

. *Adresse officielle de la société:*

. *Contact:*
+
--
[cols="6",options="unnumbered"]
|===
| | | | | |
|===

Tél.: + +
Fax: + +
Courriel:
--


*Date:*


== AMENDMENTS

[cols="^,^,^,^",options="unnumbered"]
|===

h| Amendement N° h| Bulletin d’exploitation N° h| Pays ou zone h| ICC

{% for i in (1..33) %}
| {{ i }} | | |
{% endfor %}
|===
----

