= قائمة بالرموز الدليلية للبلدان المخصصة  ITU-T E.164وفقاً للتوصية
:bureau: T
:docnumber: 976
:published-date: 2016-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:language: ar
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== ملاحظة من مكتب تقييس الاتصالات

. تحل قائمة الرموز الدليلية للبلدان المخصصة وفقاً للتوصية ITU-T E.164 محل القائمة السابقة المنشورة في ملحق النشرة
التشغيلية للاتحاد رقم 991 الصادرة بتاريخ 1 نوفمبر 2011 . وقد أجريت مذذاك تخصيصات جديدة متعددة نُشرت في النشرات
التشغيلية حتى النشرة رقم 1114 الصادرة في 15 ديسمبر 2016 .

. تتضمن القائمة ما يلي:
+
--
* قائمة بالرموز الدليلية للبلدان المخصصة وفقاً للتوصية ITU-T E.164 - بالترتيب العددي؛
* قائمة بالرموز الدليلية للبلدان المخصصة وفقاً للتوصية ITU-T E.164 - بالترتيب الأبجدي.
--

. ستُحَدَّث هذه القائمة بواسطة مجموعة مرقّمة من التعديلات المنشورة في النشرة التشغيلية للاتحاد. وإضافة إلى ذلك، فإن المعلومات
الواردة في هذا الملحق متاحة أيضاً في الموقع الإلكتروني للاتحاد في العنوان التالي: t/bulletin/annex.html-www.itu.int/itu .

. يُرجى إرسال أي تعليقات أو اقتراحات أو تعديلات متعلقة بهذه القائمة إلى مدير مكتب تقييس الاتصالات:
+
--
الهاتف: +41 22 730 5887
الفاكس: +41 22 730 5853
البريد الإلكتروني: mailto:tsbmail@itu.int[]
--

. التسميات المستخدمة والمواد المعروضة في هذه القائمة لا تعبّر عن أي رأي من جانب الاتحاد فيما يتعلق بالوضع القانوني
لأي بلد أو منطقة جغرافية أو لسلطات أيّ منهما.


[yaml2text,data=../../datasets/1114-E.164D/data.yaml,metadata=../../datasets/1114-E.164D/metadata.yaml,data_n=../../datasets/1114-E.164D-Note-N/data.yaml,metadata_n=../../datasets/1114-E.164D-Note-N/metadata.yaml,data_o=../../datasets/1114-E.164D-Note-O/data.yaml,metadata_o=../../datasets/1114-E.164D-Note-O/metadata.yaml,data_pq=../../datasets/1114-E.164D-Note-PQ/data.yaml,metadata_pq=../../datasets/1114-E.164D-Note-PQ/metadata.yaml]
----
{% assign lang = "ar" %}
{% render "tables", data: data, metadata: metadata, metadata_n: metadata_n, metadata_o: metadata_o, metadata_pq: metadata_pq, lang: lang %}

== الرموز الدليلية الاحتياطية التي يمكن أن تخصَّص كرموز لبلدان أو لخدمات عالمية

_الرموز الدليلية المشفوعة بملاحظة_

280, 281, 282, 283, 284, 285, 286, 287, 288, 289 +
801, 802, 803, 804, 805, 806, 807, 809 +
830, 831, 832, 833, 834, 835, 836, 837, 838, 839 +
890, 891, 892, 893, 894, 895, 896, 897, 898, 899

_الرموز الدليلية غير المشفوعة بملاحظة_

210, 214, 215, 217, 219 +
259, 292, 293, 294, 295, 296 +
384 +
422, 424, 425, 426, 427, 428, 429 +
671, 684, 693, 694, 695, 696, 697, 698, 699 +
851, 854, 857, 858, 859 +
871, 872, 873, 874 +
884, 885, 887, 889 +
978, 990, 997


== التعديلات

[cols="^,^,^",options="unnumbered"]
|===
| رقم التعديل
| رقم النشرة التشغيلية
| البلد

{% for i in (1..30) -%}
    | {{ i }} | |
{%- endfor %}
|===
----
