= LIST OF RECOMMENDATION ITU-T E.164 ASSIGNED COUNTRY CODES
:bureau: T
:docnumber: 976
:published-date: 2016-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

== Note from TSB

. This List of Recommendation ITU-T E.164 assigned country codes replaces the previous one published as Annex to the ITU Operational Bulletin No. 991 of 1 November 2011. Since then, various new assignments have been made, and they have been published in the ITU Operational Bulletin up to No. 1114 of 15 December 2016.

. This List includes:
+
--
* a list of Rec. ITU-T E.164 assigned country codes - numerical order;
* a list of Rec. ITU-T E.164 assigned country codes - alphabetical order.
--

. This List will be updated by numbered series of amendments published in the ITU Operational Bulletin. Furthermore, the information contained in this Annex is also available on the ITU website www.itu.int/itu-t/bulletin/annex.html .

. Please address any comments, suggestions or modifications concerning this publication to the Director of TSB:
+
--
[align=left]
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of the ITU concerning the legal status of any country or geographical area, or of its authorities.

[yaml2text,data=../../datasets/1114-E.164D/data.yaml,metadata=../../datasets/1114-E.164D/metadata.yaml,data_n=../../datasets/1114-E.164D-Note-N/data.yaml,metadata_n=../../datasets/1114-E.164D-Note-N/metadata.yaml,data_o=../../datasets/1114-E.164D-Note-O/data.yaml,metadata_o=../../datasets/1114-E.164D-Note-O/metadata.yaml,data_pq=../../datasets/1114-E.164D-Note-PQ/data.yaml,metadata_pq=../../datasets/1114-E.164D-Note-PQ/metadata.yaml]
----
{% assign lang = "en" %}
{% render "tables", data: data, metadata: metadata, metadata_n: metadata_n, metadata_o: metadata_o, metadata_pq: metadata_pq, lang: lang %}

== Spare codes that may be allocated as country codes or global service codes

_Spare codes with a note_

280, 281, 282, 283, 284, 285, 286, 287, 288, 289 +
801, 802, 803, 804, 805, 806, 807, 809 +
830, 831, 832, 833, 834, 835, 836, 837, 838, 839 +
890, 891, 892, 893, 894, 895, 896, 897, 898, 899

_Spare codes without a note_

210, 214, 215, 217, 219 +
259, 292, 293, 294, 295, 296 +
384 +
422, 424, 425, 426, 427, 428, 429 +
671, 684, 693, 694, 695, 696, 697, 698, 699 +
851, 854, 857, 858, 859 +
871, 872, 873, 874 +
884, 885, 887, 889 +
978, 990, 997

== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendment No. | Operational Bulletin No. | Country

{% for i in (1..30) -%}
    | {{ i }} | |
{%- endfor %}
|===
----



