= LISTA DE INDICATIVOS DE PAÍS DE LA RECOMENDACIÓN UIT-T E.164 ASIGNADOS
:bureau: T
:docnumber: 976
:published-date: 2016-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:language: es
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== Nota de la TSB

. Esta Lista de indicativos de país de la Recomendación UIT-T E.164 reemplaza la publicada en el Anexo al Boletín de Explotación de la UIT N.o 991 del 1 de noviembre de 2011. Desde entonces, se han efectuado varias asignaciones nuevas, que se han publicado en diferentes números del Boletín de Explotación de la UIT hasta el N.o 1114 del 15 de diciembre de 2016.

. La presente Lista comprende:
+
--
* una lista de los indicativos de país de la Recomendación UIT-T E.164 asignados - orden numérico;
* una lista de los indicativos de país de la Recomendación UIT-T E.164 asignados - orden alfabético.
--

. La Lista se irá actualizando por medio de enmiendas que se publicarán en el Boletín de Explotación de la UIT. Por otra parte, las informaciones que figuran en este anexo están disponibles en la página de sitio web de la UIT link:http://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Sírvase comunicar sus comentarios, sugerencias o modificaciones con respecto a esta publicación al Director de la TSB:
+
--
Tel: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. Las denominaciones empleadas en esta Lista y la forma en que aparecen presentados los datos que contiene no entrañan, por parte de la UIT, juicio alguno sobre la condición jurídica de países o zonas geográficas o de sus autoridades.




[yaml2text,data=../../datasets/1114-E.164D/data.yaml,metadata=../../datasets/1114-E.164D/metadata.yaml,data_n=../../datasets/1114-E.164D-Note-N/data.yaml,metadata_n=../../datasets/1114-E.164D-Note-N/metadata.yaml,data_o=../../datasets/1114-E.164D-Note-O/data.yaml,metadata_o=../../datasets/1114-E.164D-Note-O/metadata.yaml,data_pq=../../datasets/1114-E.164D-Note-PQ/data.yaml,metadata_pq=../../datasets/1114-E.164D-Note-PQ/metadata.yaml]
----
{% assign lang = "es" %}
{% render "tables", data: data, metadata: metadata, metadata_n: metadata_n, metadata_o: metadata_o, metadata_pq: metadata_pq, lang: lang %}

== Indicativos de reserva que pueden atribuirse como indicativos de país o indicativos de servicio mundial

_Indicativos de reserva con nota_

280, 281, 282, 283, 284, 285, 286, 287, 288, 289 +
801, 802, 803, 804, 805, 806, 807, 809 +
830, 831, 832, 833, 834, 835, 836, 837, 838, 839 +
890, 891, 892, 893, 894, 895, 896, 897, 898, 899

_Indicativos de reserva sin nota_

210, 214, 215, 217, 219 +
259, 292, 293, 294, 295, 296 +
384 +
422, 424, 425, 426, 427, 428, 429 +
671, 684, 693, 694, 695, 696, 697, 698, 699 +
851, 854, 857, 858, 859 +
871, 872, 873, 874 +
884, 885, 887, 889 +
978, 990, 997


== ENMIENDAS

[cols="^,^,^",options="unnumbered"]
|===
| Enmienda N.° | Boletín de Explotación N.° | País

{% for i in (1..30) -%}
    | {{ i }} | |
{%- endfor %}
|===
----




