= LISTE DES INDICATIFS DE PAYS DE LA RECOMMANDATION UIT-T E.164 ATTRIBUÉS
:bureau: T
:docnumber: 976
:published-date: 2016-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:language: fr
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== Note du TSB

. Cette Liste des indicatifs de pays de la Recommandation UIT-T E.164 attribués remplace celle qui avait été publiée dans l’Annexe au Bulletin d’exploitation de l'UIT No 991 du 1 novembre 2011. Depuis lors, différentes assignations nouvelles sont apparues et ont été publiées séparément dans différents numéros du Bulletin d'exploitation de l'UIT, jusqu’au No 1114 du 15 décembre 2016.

. La présente Liste comprend:
+
--
* une liste des indicatifs de pays de la Recommandation UIT-T E.164 attribués - ordre numérique;
* une liste des indicatifs de pays de la Recommandation UIT-T E.164 attribués - ordre alphabétique.
--

. La mise à jour de cette Liste se fera sous la forme d'amendements numérotés publiés dans le Bulletin d'exploitation de l'UIT. D'autre part, les informations contenues dans cette Annexe sont disponibles dans la page du site web de l’UIT link:https://www.itu.int/itu-t/bulletin/annex.html[www.itu.int/itu-t/bulletin/annex.html].

. Veuillez adresser vos commentaires, suggestions ou modifications concernant cette publication au Directeur du TSB:
+
--
Tél: +41 22 730 5887 +
Fax: +41 22 730 5853 +
E-mail: mailto:tsbmail@itu.int[]
--

. Les appellations employées dans cette Liste et la présentation des données qui y figurent n'impliquent, de la part de l'UIT, aucune prise de position quant au statut juridique des pays ou zones géographiques, ou de leurs autorités.



[yaml2text,data=../../datasets/1114-E.164D/data.yaml,metadata=../../datasets/1114-E.164D/metadata.yaml,data_n=../../datasets/1114-E.164D-Note-N/data.yaml,metadata_n=../../datasets/1114-E.164D-Note-N/metadata.yaml,data_o=../../datasets/1114-E.164D-Note-O/data.yaml,metadata_o=../../datasets/1114-E.164D-Note-O/metadata.yaml,data_pq=../../datasets/1114-E.164D-Note-PQ/data.yaml,metadata_pq=../../datasets/1114-E.164D-Note-PQ/metadata.yaml]
----
{% assign lang = "fr" %}
{% render "tables", data: data, metadata: metadata, metadata_n: metadata_n, metadata_o: metadata_o, metadata_pq: metadata_pq, lang: lang %}

== Indicatifs de réserve qui peuvent être attribués comme indicatifs de pays ou indicatifs du service mondial

_Indicatifs de réserve avec une note_

280, 281, 282, 283, 284, 285, 286, 287, 288, 289 +
801, 802, 803, 804, 805, 806, 807, 809 +
830, 831, 832, 833, 834, 835, 836, 837, 838, 839 +
890, 891, 892, 893, 894, 895, 896, 897, 898, 899

_Indicatifs de réserve sans note_

210, 214, 215, 217, 219 +
259, 292, 293, 294, 295, 296 +
384 +
422, 424, 425, 426, 427, 428, 429 +
671, 684, 693, 694, 695, 696, 697, 698, 699 +
851, 854, 857, 858, 859 +
871, 872, 873, 874 +
884, 885, 887, 889 +
978, 990, 997


== AMENDMENTS

[cols="^,^,^",options="unnumbered"]
|===
| Amendement N° | Bulletin d'exploitation N°. | Pays

{% for i in (1..30) -%}
    | {{ i }} | |
{%- endfor %}
|===
----