= СПИСОК ПРИСВОЕННЫХ КОДОВ СТРАНЫ СОГЛАСНО РЕКОМЕНДАЦИИ МСЭ-Т E.164
:bureau: T
:docnumber: 976
:published-date: 2016-12-15
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 994
:status: published
:doctype: service-publication
:imagesdir: images
:language: ru
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


== Примечание БСЭ

. Настоящий Список присвоенных кодов страны согласно Рекомендации МСЭ-Т E.164
заменяет предыдущий Список, опубликованный в качестве Приложения к Оперативному
бюллетеню МСЭ № 991 от 1 ноября 2011 года. С того времени выполнены различные новые
присвоения, которые публиковались в Оперативных бюллетенях МСЭ вплоть до № 1114 от
15 декабря 2016 года.

. Этот Список включает:
+
--
* список присвоенных кодов страны согласно Рекомендации МСЭ-Т E.164 −
в нумерационном порядке;
* список присвоенных кодов страны согласно Рекомендации МСЭ-Т E.164 −
в алфавитном порядке.
--

. Настоящий Список будет обновляться с помощью нумерованной серии поправок,
публикуемых в Оперативном бюллетене МСЭ. Наряду с этим информация, содержащаяся в
настоящем Приложении, размещена также на веб-сайте МСЭ по адресу: www.itu.int/itut/
bulletin/annex.html.

. Любые замечания, предложения или изменения, касающиеся данной публикации,
просим направлять Директору БСЭ:
+
--
[align=left]
Тел.: +41 22 730 5887 +
Факс: +41 22 730 5853 +
Эл. почта: mailto:tsbmail@itu.int[]
--

. Используемые в настоящем Списке обозначения и способ подачи материала не
подразумевают выражения какого бы то ни было мнения со стороны МСЭ в отношении
правового статуса какой-либо страны или географической зоны либо их властей.



[yaml2text,data=../../datasets/1114-E.164D/data.yaml,metadata=../../datasets/1114-E.164D/metadata.yaml,data_n=../../datasets/1114-E.164D-Note-N/data.yaml,metadata_n=../../datasets/1114-E.164D-Note-N/metadata.yaml,data_o=../../datasets/1114-E.164D-Note-O/data.yaml,metadata_o=../../datasets/1114-E.164D-Note-O/metadata.yaml,data_pq=../../datasets/1114-E.164D-Note-PQ/data.yaml,metadata_pq=../../datasets/1114-E.164D-Note-PQ/metadata.yaml]
----
{% assign lang = "ru" %}
{% render "tables", data: data, metadata: metadata, metadata_n: metadata_n, metadata_o: metadata_o, metadata_pq: metadata_pq, lang: lang %}

== Резервные коды, которые могут быть распределены в качестве кодов страны или кодов глобальной услуги

_Резервные коды с примечанием_

280, 281, 282, 283, 284, 285, 286, 287, 288, 289 +
801, 802, 803, 804, 805, 806, 807, 809 +
830, 831, 832, 833, 834, 835, 836, 837, 838, 839 +
890, 891, 892, 893, 894, 895, 896, 897, 898, 899

_Резервные коды без примечания_

210, 214, 215, 217, 219 +
259, 292, 293, 294, 295, 296 +
384 +
422, 424, 425, 426, 427, 428, 429 +
671, 684, 693, 694, 695, 696, 697, 698, 699 +
851, 854, 857, 858, 859 +
871, 872, 873, 874 +
884, 885, 887, 889 +
978, 990, 997


== ПОПРАВКИ

[cols="^,^,^",options="unnumbered"]
|===
| Поправка № | Оперативный бюллетень № | Страна

{% for i in (1..30) -%}
    | {{ i }} | |
{%- endfor %}
|===
----
