= LIST OF COUNTRY OR GEOGRAPHICAL AREA CODES FOR NON-STANDARD FACILITIES IN TELEMATIC SERVICES
:bureau: T
:series: COMPLEMENT TO ITU-T RECOMMENDATION T.35 (02/2000)
:language: en
:docnumber: 1002
:published-date: 2012-04-15
:status: published
:doctype: service-publication
:annex-title-en: Annex to ITU Operational Bulletin
:annex-id: No. 1002
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:


[preface]
== Note from TSB

[class=steps]
. The Director of the Telecommunication Standardization Bureau of ITU (TSB) has the responsibility for the allocation and management of the country codes.

. The code 1111 1111, at the end of the List below, is an escape code used to indicate that the next octet contains a code given in a separate extension List. Whenever the code 1111 1111 is used in the first octet, the country or geographical area code will be found in the extension List. This list will be implemented when all the codes in the List below have been allocated.
+
NOTE: Codes once issued may have been imbedded in terminal equipment and therefore should not be changed or reassigned even if the designation of the country or geographical area is no longer valid.

. The Member States of the International Telecommunication Union (ITU) not mentioned in this List who wish to obtain a country or geographical area code should ask the Director of TSB for the assignment of an available country code. In their request, they may indicate a specific code if it is available. Please address any comments to the Director of TSB:
+
International Telecommunication Union (ITU)
+
Director of TSB
+
Place des Nations
+
CH-1211 GENEVA 20
+
Switzerland
+
Tel: +41 22 730 6805
+
Fax: +41 22 730 5853
+
E-mail: tsbmail@itu.int

. For information, this List is also available on the ITU web page .
+
http://www.itu.int/itu-t/bulletin/annex.html[http://www.itu.int/itu-t/bulletin/annex.html]

. The designations employed and the presentation of material in this List do not imply the expression of any opinion whatsoever on the part of ITU concerning the legal status of any country or geographical area, or of its authorities.

== {blank}

[yaml2text,data=../../datasets/1002-T.35/data.yaml,metadata=../../datasets/1002-T.35/metadata.yaml]
----
{% assign lang = "en" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----
