= LISTA DE INDICATIVOS DE PAÍS O DE ZONA GEOGRÁFICA PARA FACILIDADES NO NORMALIZADAS DE LOS SERVICIOS TELEMÁTICOS
:bureau: T
:series: COMPLEMENTO DE LA RECOMENDACIÓN UIT- T.35 (02/2000)
:language: es
:docnumber: 1002
:published-date: 2012-04-15
:status: published
:doctype: service-publication
:annex-title-es: Anexo al Boletín de Explotación de la UIT
:annex-id: N.° 1002
:imagesdir: images
:mn-document-class: itu
:mn-output-extensions: xml,html,pdf,doc,rxl
:local-cache-only:

[preface]
== Nota de la TSB

[class=steps]
. El Director de la Oficina de Normalización de las Telecomunicaciones (TSB) está encargado de asignar y gestionar los indicativos de país.

. El indicativo 1111&nbsp;1111 que se encuentra al final de la siguiente Lista es un código de escape, que se utiliza para indicar que el siguiente octeto contiene un código dado en una Lista de extensiones distinta. Cuando el código 1111&nbsp;1111 se utiliza en el primer octeto, el indicativo de país o de zona geográfica se encontrará en la Lista de extensiones. Esta lista se aplicará cuando todos los indicativos de la Lista que figura a continuación hayan sido asignados.
+
NOTE: Una vez expedidos, cabe la posibilidad de que los códigos se incorporen en el equipo terminal y, por tanto, no deberían modificarse o reasignarse, incluso cuando la designación del país o la zona geográfica de que se trate no sea ya válida._

. Los Estados Miembros de la Unión Internacional de Telecomunicaciones (UIT) no mencionados en esta Lista que deseen obtener un indicativo de país o de zona geográfica deben pedir al Director de la TSB que les asigne uno disponible. En su solicitud pueden señalar el indicativo específico que desean, siempre que éste se encuentre disponible. Sírvase comunicar sus comentarios al Director de la TSB:
+
Unión Internacional de Telecomunicaciones (UIT)
+
Director de la TSB
+
Place des Nations
+
CH-1211 GINEBRA 20
+
Suiza
+
Tel: +41 22 730 6805
+
Fax: +41 22 730 5853
+
E-mail: tsbmail@itu.int

. Se señala que esta Lista está disponible en el sitio web de la UIT .
+
http://www.itu.int/itu-t/bulletin/annex.html

. Las denominaciones utilizadas y la presentación de la información en esta Lista no entrañan opinión alguna de la UIT en cuanto a la situación jurídica de cualquier país o zonas geográfica, o de sus autoridades.

== {blank}


[yaml2text,data=../../datasets/1002-T.35/data.yaml,metadata=../../datasets/1002-T.35/metadata.yaml]
----
{% assign lang = "es" %}
{% render "table", data: data, metadata: metadata, lang: lang %}
----
