name: Validate Datasets

on:
  pull_request:
    paths:
      - 'datasets/**/*.yaml'
      - 'datasets/**/*.yml'
      - 'schema-metadata.yaml'
  push:
    branches: [ main ]
    paths:
      - 'datasets/**/*.yaml'
      - 'datasets/**/*.yml'
      - 'schema-metadata.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Validate datasets
      run: bundle exec ituob dataset validate
